<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/additionaluses.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/additionaluses.js");
?>
	<div id="content0">
		<div class="centredcontent">
			
			<div id=content0title><div class="mediumheader">ADDITIONAL USES</div></div>
				<div id="topdlbutton">ENABLE YOUR SITE</div>
								
		</div>	
	</div>	
	
	<div id="content1">
		<div class="centredcontent">
			<div id="content1title"><div class="mediumheader">EDUCATION</div></div>
						
			<div class="content1text"><div class="alltext">Use co-browsing for tasks ranging from<br>joint research to
classroom simulations<br>for enhanced distance learning.<br></div>
			<a href="http://www.samesurf.com">Learn More</a></div>
				<div class="bluecircle">
					<div id="icon01"></div>
				</div>
		</div>
	</div>	
	
	<div id="content2">
		<div class="centredcontent">
			<div class="greencircle">
				<div id="icon02"></div>
			</div>
			
			<div id="content2title"><div class="mediumheader">HEALTH CARE</div></div>
			<div class="content2text"><div class="alltext">Enhance patient care through privacy<br>conscious tools
for collaboration with<br>medical and insurance information. <br></div>
			<a href="http://www.samesurf.com">Learn More</a></div>
				
		</div>
	</div>
	
		<div id="content5">
		<div class="centredcontent">
			<div id="content5title"><div class="mediumheader">SEARCH TOGETHER</div></div>
						
			<div class="content5text"><div class="alltext">Transform search into a true collaboration<br>by co-browsing
		all of the search engines<br>together from a single source.<br></div>
			<a href="http://www.samesurf.com">Learn More</a></div>
				<div class="yellowcircle">
					<div id="icon05"></div>
				</div>
		</div>
	</div>	
	
		<div id="content6">
		<div class="centredcontent">
			<div class="purplecircle">
				<div id="icon06"></div>
			</div>
			
			<div id="content6title"><div class="mediumheader">MARKET RESEARCH</div></div>
			<div class="content6text"><div class="alltext">Achieve major cost efficiencies and deeper<br>insights by leveraging
more diverse sample<br>sets to conduct market research online.<br></div>
			<a href="http://www.samesurf.com">Learn More</a></div>
				
		</div>
	</div>
	
	<div id="content7">
		<div class="centredcontent">
			<div id="content7title"><div class="mediumheader">BROWSER TESTING</div></div>
						
			<div class="content7text"><div class="alltext">Conduct install-free compatibility testing<br>to preview
your web projects on different<br>browsers and devices at the same time.<br></div>
			<a href="http://www.samesurf.com">Learn More</a></div>
				<div class="redcircle">
					<div id="icon07"></div>
				</div>
		</div>
	</div>
	
	<div id="content8">
		<div class="centredcontent">
			<div class="pinkcircle">
				<div id="icon08"></div>
			</div>
			
			<div id="content8title"><div class="mediumheader">USABILITY TESTING</div></div>
			<div class="content8text"><div class="alltext">Perform usability testing that leverages<br>diverse response
pools to achieve cost<br>efficiencies and clearly deeper insights.<br></div>
			<a href="http://www.samesurf.com">Learn More</a></div>
				
		</div>
	</div>	
	
	<div id="content9">
		<div class="centredcontent">
						
			<div class="content9text"><div class="mediumheader">HOW DO YOU USE SAMESURF?</div></div>
				<div class="smalltext"><div class="alltext">Let us know.</div></div>
				
				<form>	
					<div id="forminput">
						<textarea id="formtextarea">e.g. For Collaboration at Work</textarea>
					</div>
				</form>	
				<div id="formsubmit">SUBMIT</div>
			
		</div>
	</div>	
	



