<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/app.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/app.js");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>
	<div id="content0">
		<div class="centredcontent">
			
			<div id=content0title><div class="mediumheader">CO-BROWSE THE ENTIRE WEB TOGETHER</div></div>
					
		</div>	
	</div>	
	
	<div id="content1">
		<div class="centredcontent2">
		
			<div id="circlegrid">
				<div id="osiconcircle1">
					<div id="osicon1"></div>
				</div>
				
				<div id="osiconcircle2">
					<div id="osicon2"></div>
				</div>
				
				<div id="osiconcircle3">
					<div id="osicon3"></div>
				</div>
				
				<div id="osiconcircle4">
					<div id="osicon4"></div>
				</div>
				
				<div id="osiconcircle5">
					<div id="osicon5"></div>
				</div>
					
			</div>
		
		
			<div id="content1title"><div class="mediumheader">GET THE SAMESURF APP</div></div>
						

			<div class="content1text">
				<div class="alltext">Enjoy built-in functionality such as HD video<br/>
			chat, screen sharing and parallel co-browse<br/>
			sessions by downloading the samesurf app.<br/>
			<a href="/http://www.samesurf.com">Experience the difference.</a>
				</div>
			</div>
				<div id="content1button">
					<div id="buttonicon"></div>
					<div id="content1buttontext">DOWNLOAD NOW</div>
				</div>
			<div id="underbuttontext">WINDOWS: SP2+ &nbsp;&nbsp;MAC: 10.6+</div>	
		</div>
	</div>	
	
	<div id="content2">
		<div class="centredcontent">
			<div id="content2image"></div>	
				<div id="content2title"><div class="mediumheader">WHY DOWNLOAD THE SAMESURF APP?</div></div>
					<div id="grid">
						<div class="bulletbox">
							<div class="bulletptblue"></div>
						Synced co-browsing throughout the entire web
						</div>
					
						<div class="bulletbox2">
							<div class="bulletptorange"></div>
						Single click access to all of the primary features
						</div>
					
						<div class="bulletbox">
							<div class="bulletptred"></div>
						Cutting edge speed, security and functionality
						</div>
					
						<div class="bulletbox2">
							<div class="bulletptgreen"></div>
						Unified chat across your favorite social networks
						</div>
					
						<div class="bulletbox">
							<div class="bulletptgreen"></div>
						Fully integrated high-def audio and video chat  
						</div>
					
						<div class="bulletbox2">
							<div class="bulletptred"></div>
						Seamless co-browsing across virtually all devices
						</div>
					
						<div class="bulletbox">
							<div class="bulletptorange"></div>
						Built-in screen sharing for viewing offline content
						</div>
					
						<div class="bulletbox2">
							<div class="bulletptblue"></div>
						Familiar use and design of the Chromium browser
						</div>
					</div>
							
		</div>	
	</div>	
	
	<div id="content3">
		<div class="centredcontent">
			<div id="key_uses_box_container">
	<div id="key_uses_box">
		<div id="key_uses_text">
			USES
		</div>
		<div id="circles_div">
			<a href="">
			<div class="key_uses_circles">
				<div id="headphones_circle">
				</div>
			</div>
			</a>
			<div class="key_uses_circles">
				<div id="hand_shake">
				</div>
			</div>
			<div class="key_uses_circles">
				<div id="high_five">
				</div>
			</div>
			<div class="key_uses_circles">
				<div id="whiteboard">
				</div>
			</div>
			<div class="key_uses_circles">
				<div id="trolley">
				</div>
			</div>
			<div class="key_uses_circles">
				<div id="blackboard">
				</div>
			</div>
			<div class="key_uses_circles">
				<div id="three_heads">
				</div>
			</div>
			<div class="key_uses_circles">
				<div id="mortar_board">
				</div>
			</div>
		</div>	
	</div>
</div>
		
		</div>
	</div>
	
	<div id="content4">
		<div class="centredcontent">
			<div id="samesurfvideo">
			<iframe src="//player.vimeo.com/video/53180842?title=0&amp;byline=0&amp;portrait=0" width="917" height="520" allowfullscreen></iframe>
			</div>
			
		</div>
	</div>		
	
	
	<div id="content5">
		<div class="centredcontent">
			<div id="content5title"><div class="mediumheader">ONLINE SHARING REIMAGINED</div></div>
						
			<div class="content5text"><div class="alltext">Samesurf transitions web sharing from a myriad <br/>
of posts, tweets and pins into a world of shared <br/>experiences that live directly on every website.    </div></div>
				<div id="content5image"></div>
		</div>
	</div>		
	
	
	<div id="content6">
		<div class="centredcontent">
			<div id="content6image"></div>
				<div id="content6title"><div class="mediumheader">CUTTING EDGE FEATURES</div></div>
						
			<div class="content6text"><div class="alltext">Advanced features such as HD video chat<br/>and install-free screen sharing into mobile<br/>devices heighten the shared experience.</div></div>
		</div>
	</div>	
	

	
	<div id="content7">
		<div class="centredcontent">
			<div id="content7title"><div class="mediumheader">FEATURES</div></div>
				<div id="grid2">
					<div class="iconsq01">
						<div id="icon01"></div>
					</div>
					
					<div class="iconsq02">
						<div id="icon02"></div>
					</div>
					
					<div class="iconsq03">
						<div id="icon03"></div>
					</div>
					
					<div class="iconsq04">
						<div id="icon04"></div>
					</div>
					
					<div class="iconsq05">
						<div id="icon05"></div>
					</div>
					
					<div class="iconsq06">
						<div id="icon06"></div>
					</div>
					
					<div class="iconsq07">
						<div id="icon07"></div>
					</div>
					
					<div class="iconsq08">
						<div id="icon08"></div>
					</div>
				</div>		
			
		</div>
	</div>
		
