<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/benefits.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/benefits.js");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>
	<div id="content1">
		<div class="centredcontent">
			<div class="subtitle"><div class="mediumheader">BENEFITS FOR E-COMMERCE SITES</div></div>
				<div id="content1button">
					<a href="http://amazon.com" target="_blank" class="enablesite">VISIT ACTIVE SITE</a>
				</div>
					<div id="ecommerce"></div>
					
					<div class="grid">
						<div class="textbox">
							<div class="textcontainer">
								<div class="textboxtext"><div class="mediumheader">Increase Revenues: </div>
								Improve conversion rates by enabling users to instantly validate their online buying decisions.</div>
							</div>
						</div>	
						<div class="textbox">
							<div class="textcontainer">
								<div class="textboxtext"><div class="mediumheader">Drive Targeted Traffic: </div>
								Convert customers into recruiters who deliver targeted, high value traffic to your website.<br><br></div>
							</div>
						</div>	
						<div class="textbox">
							<div class="textcontainer">
								<div class="textboxtext"><div class="mediumheader">Heighten Dwell Times: </div>
								Boost time on site levels by enabling 
								features like social messaging, invites and video chat.</div>
							</div>
						</div>	
						<div class="textbox">
							<div class="textcontainer">
								<div class="textboxtext"><div class="mediumheader">Simple Button Integration: </div>
								Start button installs seamlessly within 
minutes by integrating a single line of 
code on one page of the website.
</div>
							</div>		
						</div>	
						<div class="textbox">
							<div class="textcontainer">
								<div class="textboxtext"><div class="mediumheader">Gain Key Insights: </div>
								Acquire valuable analytics to craft
offerings that reflect the preferences  
and requirements of your user base.
</div>
							</div>
						</div>	
						<div class="textbox">
							<div class="textcontainer">
								<div class="textboxtext"><div class="mediumheader">Modernize Your Brand: </div>
								Deploy cutting edge offerings that signal 
								your commitment to high impact customer care.</div>
							</div>
						</div>	
					</div>
		</div>			
	</div>	
	
	<div id="content2">
		<div class="centredcontent">
			<div class="subtitle"><div class="mediumheader">BENEFITS FOR CONTENT SITES</div></div>
				<div id="content2button">
					<a href="http://publicrooms.com" target="_blank" class="enablesite">VISIT ACTIVE SITE</a>
				</div>
					<div id="contentsite"></div>
					
					<div class="grid">
						<div class="textbox">
							<div class="textcontainer">
								<div class="textboxtext"><div class="mediumheader">Increase Revenues: </div>
								Utilize instant invites and shared 
browsing to elevate the incidence 
of searches, clicks and views.    
</div>
							</div>
						</div>	
						<div class="textbox">
							<div class="textcontainer">
								<div class="textboxtext"><div class="mediumheader">Drive Targeted Traffic: </div>
								Enable existing users to recruit friends, family and colleagues directly to your website.  
								 </div>
							</div>
						</div>	
						<div class="textbox">
							<div class="textcontainer">
								<div class="textboxtext"><div class="mediumheader">Heighten Dwell Times: </div>
								Boost time on site levels by enabling features 
								like social messaging, invites and video chat.</div>
							</div>
						</div>	
						<div class="textbox">
							<div class="textcontainer">
								<div class="textboxtext"><div class="mediumheader">Simple Button Integration: </div>
								Start button installs seamlessly within 
minutes by integrating a single line of 
code on one page of the website.
</div>
							</div>		
						</div>	
						<div class="textbox">
							<div class="textcontainer">
								<div class="textboxtext"><div class="mediumheader">Gain Key Insights: </div>
								Acquire valuable analytics to help craft more effective 
								products and promotional 
								campaigns.</div>
							</div>
						</div>	
						<div class="textbox">
							<div class="textcontainer">
								<div class="textboxtext"><div class="mediumheader">Modernize Your Brand: </div>
								Deploy cutting edge offerings that signal your commitment to high impact user experiences.</div>
							</div>
						</div>	
					</div>
		</div>	
	</div>