<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/boardofadvisors.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/boardofadvisors.js");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>
	<div id="content0">		
		<div class="centredcontent">
			<div id="title"><div class="mediumheader">BOARD OF ADVISORS</div></div>
			<a href="/pages/team">
				<div id="topdlbutton" class="enablesite">VIEW TEAM</div>
			</a>	
		</div>
	</div>		
	
	<div id="maincontent">
		<div class="centredcontent">					
				<div id="grid">	
					<div class="contentbox">
						<div class="contentboxtitle"><div class="mediumheader">JENNIFER PRINCE</div></div>
						
						<a href="http://www.linkedin.com/in/jenmprince" target="_blank">
							<div class="twitterlogo">
							</div>
						</a>	
						<div id="logo1"></div>
						<div class="downarrow"></div><div class="contentboxsubtitle">Lead Monetization Advisor</div>
						<div class="contentboxtext"><div class="alltext">
						Jennifer Prince serves as the Company's Lead Monetization Advisor who is entrusted with helping 
							guide Samesurf's monetization initiatives. She is responsible for Media &amp; Entertainment 
							partnerships and revenue at Twitter, overseeing movie studios and TV networks nationally. 
							Prior to joining Twitter in August 2013, Jennifer was Head of Industry for Film &amp; Television 
							at Google and years prior as a Regional Manager at YouTube.  Earlier, Jennifer was SVP of 
							Advertising at Demand Media where she launched their Ad Sales division while helping the company 
							through its IPO. Jennifer has spent more than 20 years in advertising and 17 years focusing on 
							digital.<br/><br/>
							She earned a BA Communications degree from University of California, Santa Barbara. 
							In addition to Jennifer’s advisory role at Samesurf, she has served on the boards of ThinkLA 
							&amp; City of Hope. Jennifer lives in Los Angeles and keeps busy with her three little girls.
						</div></div>
					</div>
						
					<div class="contentbox">
						<div class="contentboxtitle"><div class="mediumheader">CHRISTOPHER BUCHANAN</div></div>
						<a href="http://www.linkedin.com/in/chrisbuchanan" target="_blank">
							<div class="linkedinlogo">
							</div>
						</a>	
						<div id="logo2"></div>
						<div class="downarrow"></div><div class="contentboxsubtitle">Lead Entertainment Industry Advisor</div>
						<div class="contentboxtext"><div class="alltext">
						Christopher Buchanan serves as the Company's Lead Entertainment Industry Advisor who is entrusted 
						with helping guide Samesurf's initiatives within the entertainment industry. He has deep 
						entertainment experience managing companies, content &amp; artists and frontline entrepreneurial 
						expertise in new media with a focus on consumer engagement, strategic partnerships and revenue generation.<br/><br/>

						Chris recently joined Samsung Electronics' newly formed Global Media Group as Director. This Group is
						responsible for leading advertising and n-service gaming, and developing worldwide content n-service 
						alliances across mobile, tablet, display (television), PC, and digital appliances.  <br/><br/>

						Previously, he was Vice President, Business Development for Thismoment, where Chris was responsible 
						for Thismoment's Partner Network, representing the Company's strategic relationships with agencies, 
						developers and technology providers. Thismoment's Distributed Engagement Channel (DEC) is a cloud-based 
						enterprise platform for digital experience marketing used to create, distribute and measure dynamic 
						brand experiences across multiple sites and devices by hundreds of Fortune 500 brands. At Amazon.com, 
						he drove an original entertainment content initiative for Jeff Bezos, now launched as Amazon Studios, 
						a collaborative online motion picture development process. As a part of the content acquisition team, 
						Chris also licensed film &amp; television programming for Amazon Video On Demand.  <br/><br/>

						As President of Joss Whedon's company at 20th Century Fox Television (Mutant Enemy), he oversaw the 
						critically acclaimed series "Buffy the Vampire Slayer," "Angel," and "Firefly." Chris also produced 
						Whedon's feature debut, "Serenity," at Universal Pictures. Earlier at Warner Bros., he ran Jerry 
						Weintraub Productions where Chris developed a slate of films including "Ocean's Eleven," which 
						grossed $450M at the box office worldwide. <br/><br/>

						In 2000, he co-founded Flixer, a venture backed, technology start-up providing digital marketing 
						services to major media clients. As CCO, Chris drove product, oversaw revenue strategy and business 
						development. He also founded the United Talent Agency's independent film department, where he 
						represented cutting edge filmmakers and packaged their productions. Chris began his career as a 
						programming and acquisitions executive for Sony Pictures Entertainment in New York.
						</div></div>
					</div>
					
					<div class="contentbox">
						<div class="contentboxtitle"><div class="mediumheader">TODD TAPPIN</div></div>						
						<div id="logo3"></div>
						<div class="downarrow"></div>
						<div class="contentboxsubtitle">Lead Financial Advisor</div>
						<div class="contentboxtext"><div class="alltext">
						Todd Tappin serves as the Company's Lead Financial Advisor who is entrusted with helping guide Samesurf's 
						finance initiatives.  As Chief Operating Officer and Chief Financial Officer of Rubicon Project, Todd is 
						responsible for the administrative operations of the company, finance, M&amp;A, legal and the execution of its 
						operating and financial plan. Prior to Rubicon Project, he was the CEO of SocialVibe, a leader in engagement 
						and value exchange advertising. Prior to that, Todd served as Managing Director of The Gores Group, an L.A. 
						based private equity firm. <br/><br/> 

						Earlier in his career, he was the founding CFO of Overture, the pioneer in paid search. Todd built and oversaw 
						all strategic planning, finance, legal, M&amp;A and administrative functions, led the company’s IPO and secondary 
						public offerings, was instrumental in the company’s international expansion and key affiliate deals and co-led 
						the sale of the company to Yahoo!. Prior to Overture, he spent six years as a senior executive at News Corporation, 
						where Todd ultimately held three simultaneous positions as Senior Vice President of Finance for Twentieth Century 
						Fox Home Entertainment, the Senior Vice President of Finance for Fox Interactive, and General Manager for 
						Twentieth Century Fox Home Entertainment, Canada.
						</div></div>
					</div>
					
					<div class="contentbox">
						<div class="contentboxtitle"><div class="mediumheader">HENRY "QUE" GASKINS</div></div>
						<a href="http://www.linkedin.com/in/quegaskins" target="_blank">
							<div class="linkedinlogo">
							</div>
						</a>						
						<div id="logo4"></div>
						<div class="downarrow"></div>
						<div class="contentboxsubtitle">Lead Marketing Advisor</div>
						<div class="contentboxtext"><div class="alltext">
						Henry "Que" Gaskins serves as the Company's Lead Marketing Advisor who is entrusted with helping shape 
						Samesurf's marketing initiatives. He is a marketing visionary and game changer known for championing 
						ideas that stretch boundaries, challenge assumptions and deliver breakthrough business results. Que is
						best known for helping Reebok transform itself from an athletic shoe company to a lifestyle brand by 
						leading the RBK division and forging pioneering relationships with Allen Iverson, Jay-Z, 50 Cent, 
						Pharrell, NBA, NFL and other cultural icons.<br/><br/> 

						Most recently, he founded QUE-IN: a forward thinking brand strategy, creative solutions and ideas 
						agency that is known for its ability to QUE-IN on brand, consumer and cultural shifts. A current 
						roster of QUE-IN’s clients include: Revolt TV &amp; Media, Li-Ning Sports, Barclays US, AFROPUNK and 
						FaceReview. Prior to this endeavor, he held senior executive marketing positions at Nike, American 
						Eagle Outfitters, Reebok, Dayton-Hudson, and most recently as the Chief Marketing Officer of the 
						digital start-up, Personal. In his first taste of entrepreneurship, Que co-founded the ad*itive, 
						an advertising and lifestyle marketing agency. Clients of the ad*itive included brands such as Yum! 
						Brands, truth, Colgate, Ultra Sheen, Gentle Treatment, Timberland, Sprite, Amtrak, Choice Hotels, 
						Bermuda Department of Tourism, McDonalds, Reebok and Volkswagen.<br/><br/>

						He graduated #1 in his class from Florida A&amp;M University's School of Business &amp; Industry and earned 
						his MBA from the J.L. Kellogg Graduate School of Management at Northwestern University.
						</div></div>
					</div>
					
					<div class="contentbox">
						<div class="contentboxtitle"><div class="mediumheader">ANDREW MACEY</div></div>
						<a href="http://www.linkedin.com/in/andrewmacey" target="_blank">
							<div class="linkedinlogo">
							</div>
						</a>						
						<div id="logo5"></div>
						<div class="downarrow"></div>
						<div class="contentboxsubtitle">Lead Strategy Advisor</div>
						<div class="contentboxtext"><div class="alltext">
						Andrew Macey serves as the Company’s Lead Strategy Advisor with responsibility for helping guide Samesurf's 
						strategy within the verticals it operates. He currently serves as Vice President of Digital Strategy &amp; 
						Innovation at CVS Health.  Prior to this role, Andy served as Group Vice President of Digital at Luxottica 
						and Vice President of Strategy at Sapient in a role he held for over a decade. In his role at Sapient, 
						he worked with such industry leaders as Lenscrafters, Sunglass Hut, Dunkin' Brands, Staples, Royal Ahold, 
						PetSmart, Tesco, P&amp;G, Coca-Cola, Dell, Carrier, GE, Forrester Research, Gartner and The Royal Mail.<br/><br/> 

						Andy's experience includes business change through new growth initiatives with a focus on digital strategy 
						and the convergence of channels across e-commerce, mobile, social and stores.  He also focuses on changes 
						in publishing and content-driven businesses, customer experience design, multichannel investment strategy 
						and operational and organizational effectiveness to evolve multichannel capabilities. He began his career 
						at Bain, where he led work in go-to-market, operations and M&amp;A strategy. Andy also worked with two software 
						companies in senior operating roles: first as VP Sales &amp; Services at OAT Systems (now part of Checkpoint) 
						and as VP &amp; MD Europe for Formation Systems (now part of Infor). He was also SVP of Operations for the 
						consumer products company AWC and COO of HLB, a product development firm turnaround discussed in a 
						Harvard Business School case.<br/><br/> 

						Andy is also a mentor, judge or board member with several organizations involved in start-ups, business 
						competitions and new thinking around digital convergence; these include competitions at Harvard Business 
						School, the MIT Sloan School, MITX and Mass Challenge. He is also a board member of the start-up investment 
						group CommonAngels and serves on an advisory board for the MIT Enterprise Forum, a community of ~100,000 
						entrepreneurs in 28 international chapters. <br/><br/>

						Andy has an AB from Harvard College and an MBA from the Harvard Graduate School of Business.
						</div></div>
					</div>
					
					<div class="contentbox">
						<div class="contentboxtitle"><div class="mediumheader">JON SNODDY</div></div>
						<a href="http://www.linkedin.com/pub/jon-snoddy/0/10b/913" target="_blank">
							<div class="linkedinlogo">
							</div>
						</a>						
						<div id="logo6"></div>
						<div class="downarrow"></div>
						<div class="contentboxsubtitle">Chief Technical Advisor</div>
						<div class="contentboxtext"><div class="alltext">
						Jon Snoddy serves as the Company's Chief Technical Advisor with responsibility for helping shape 
						Samesurf's technical pursuits and promoting visibility for the Company’s offerings. He currently 
						serves as Vice President of Research &amp; Development at Walt Disney Imagineering. Prior to Jon’s 
						role at Disney, he worked at Big Stage Entertainment (CTO and Co-Founder), TimePlay Entertainment 
						(CCO/CTO), GameWorks (CCO), Sega GameWorks (CCO), Walt Disney Imagineering (Director, Senior Concept 
						Designer, Senior Show Designer), LucasFilm (Project Director) and National Public Radio (Technical 
						Director, Recording Engineering). <br/><br/>

						Jon has a BA Degree in Journalism from the University of South Carolina and an AS Degree in 
						Electronics Engineering from Piedmont Institute of Technology.. 
						</div></div>
					</div>
					
					<div class="contentbox">
						<div class="contentboxtitle"><div class="mediumheader">BENJAMIN NAZARIAN</div></div>
						<a href="http://www.linkedin.com/pub/benjamin-nazarian/a/1a4/868" target="_blank">
							<div class="linkedinlogo">
							</div>
						</a>						
						<div id="logo7"></div>
						<div class="downarrow"></div>
						<div class="contentboxsubtitle">Lead Wireless Industry Advisor</div>
						<div class="contentboxtext"><div class="alltext">
						Benjamin Nazarian serves as the Company's Lead Wireless Industry Advisor who is entrusted with 
						helping guide Samesurf's initiatives within the wireless and related online sectors. He is currently 
						Founder and CEO of WannaGo, a start-up software company that helps users keep track and share their 
						favorite places with their friends. Ben is also a Managing Partner and member of the investment 
						committee of Omninet Capital, LLC, a private investment firm focused on real estate and venture 
						capital investments that was established by the co-founders of Qualcomm (NASDAQ: QCOM).  He has 
						served on the board of a number of private companies playing a critical role in their development, 
						including advising on strategy, hiring and operational decisions.  Ben also serves on the Board of 
						Councilors of the Law Center at the University of Southern California and is a member of the 
						Young Presidents Organization (YPO). <br/><br/>
						
						He received his Juris Doctorate from the Law Center at the University of Southern California and
						holds a Bachelor of Science degree in Accounting, Cum Laude, from the University of Southern California.
						</div></div>
					</div>
					
					<div class="contentbox">
						<div class="contentboxtitle"><div class="mediumheader">BEAU LASKEY</div></div>
						<a href="http://www.linkedin.com/in/pub/beau-laskey/0/1b/504" target="_blank">
							<div class="linkedinlogo">
							</div>
						</a>						
						<div id="logo8"></div>
						<div class="downarrow"></div>
						<div class="contentboxsubtitle">Lead Operations Advisor</div>
						<div class="contentboxtext"><div class="alltext">
						Beau Laskey serves as the Company’s Lead Operations Advisor who is entrusted with helping guide 
						Samesurf's operational initiatives. He is a Managing Director with SVB Capital and is responsible 
						for sourcing and executing direct venture capital and private equity investments. Beau has spent 
						the last 15 years in technology, finance and operational leadership roles where he focused on media, 
						technology and consumer internet investment opportunities<br/><br/>

						Prior to joining SVB, Beau was a Managing Director with Steamboat Ventures, The Walt Disney Company’s 
						venture capital investment group. Earlier in his career, he was a Managing Director of EDF Ventures in 
						San Diego, an early stage venture capital fund. A few of his key investments are Arbor Networks, GoPro, 
						Greenplum, Photobucket, Sometrics and Zyray Wireless. Beau started his career as an officer in the SEAL 
						Teams and deployed around the globe with several SEAL Teams. Beau received a BS in Economics and General 
						Engineering with Merit as a graduate of the US Naval Academy, and received an MBA with Distinction in 
						Entrepreneurship and Corporate Strategy from The University of Michigan Business School. <br/><br/>

						Beau and his wife have three children that are avid skiers and sports enthusiasts. In his effort to help 
						those that have served others, Beau is a supporter and committee member of the Navy SEAL Foundation and 
						The Mission Continues. 
						</div></div>
					</div>
					
					<div class="contentbox">
						<div class="contentboxtitle"><div class="mediumheader">LEORA KADISHA</div></div>
						<a href="http://www.linkedin.com/pub/leora-kadisha/30/aba/875" target="_blank">
							<div class="linkedinlogo">
							</div>
						</a>						
						<div id="logo9"></div>
						<div class="downarrow"></div>
						<div class="contentboxsubtitle">Lead Fashion Industry Advisor</div>
						<div class="contentboxtext"><div class="alltext">
						Leora Kadisha serves as the Company's Lead Fashion Industry Advisor who is entrusted with helping guide 
						Samesurf's initiatives within the fashion marketing industries. Leora was the founder and CEO of StyledOn.com, 
						a company that was recently acquired by shopping search engine, Wantering.  She now serves as a Board Member 
						and the VP of Business Development at Wantering. Leora concurrently serves as Director of New Investments for 
						Omninet Capital, where she is responsible for expanding their portfolio in the technology sector. With a keen 
						sense of style and an innate entrepreneurial spirit, Leora’s experience is focused in Venture Capital and social 
						commerce. She holds a B.S. in Business Administration with a concentration in Finance from Boston University.
						</div></div>
					</div>
					
					<div class="contentbox">
						<div class="contentboxtitle"><div class="mediumheader">ZACH KATZ</div></div>						
						<div id="logo10"></div>
						<div class="downarrow"></div>
						<div class="contentboxsubtitle">Lead Music Industry Advisor</div>
						<div class="contentboxtext"><div class="alltext">
						Zach Katz serves as the Company's Lead Monetization Advisor who is entrusted with helping guide 
						Samesurf's initiatives within the music industry. He currently serves as the Executive VP Creative, 
						North America at BMG Chrysalis. Zach earned his Juris Doctorate from Loyola School of Law in 1996 
						and directly thereafter went into private practice. <br/><br/>

						From 2001 to 2002, he served as GM of Groove Attack USA when the German record label opened a US division. 
						In 2002-2005, Zach worked closely with Dr. Dre's Aftermath Entertainment by managing Rakim and the label's 
						top producers and songwriters. In 2005, he discovered, developed and continues to manage super-music producer
						Jonathan "J.R." Rotem. In 2006, Zach co-founded Beluga Heights, a record label and publishing company, 
						with partners J.R. Rotem and Tommy Rotem. He served as CEO, co-A&amp;R and co-Executive Producer of every 
						record they created. In the past 6 years, Beluga Heights has sold more than 30 million singles and 5 
						million albums with artists like Sean Kingston and Jason Derulo. From 2010 -2012, Zach and Beluga Heights 
						served as A&amp;R Consultants for Island/Def Jam, reporting directly to LA Reid.
						 </div></div>
					</div>
					
					<div class="contentbox">
						<div class="contentboxtitle"><div class="mediumheader">KRISTIN LUCK</div></div>
						<a href="http://www.linkedin.com/in/kristinluck" target="_blank">
							<div class="linkedinlogo">
							</div>
						</a>						
						<div id="logo11"></div>
						<div class="downarrow"></div>
						<div class="contentboxsubtitle">Lead Market Research Advisor</div>
						<div class="contentboxtext"><div class="alltext">
						Kristin Luck serves as the Company’s Lead Market Research Advisor who is entrusted with helping guide 
						Samesurf's initiatives within the market research industry. She currently serves as President and brand 
						evangelist for Decipher. Decipher is a marketing research services provider that specializes in online 
						survey programming, data collection, data processing/report and custom technology development. Kristin’s 
						diverse background includes a strong technical knowledge of online research systems and new product 
						development, combined with traditional research experience.<br/><br/> 

						She was one of the original pioneers of the multimedia online research business when she joined ACNielsen 
						to assist in the development of proprietary capabilities for testing full screen video and other multimedia 
						materials securely online. As the Co-Founder of OTX (Online Testing Exchange), Kristin built and managed 
						the operational and client management infrastructure for a start-up online market research firm that became 
						the fastest growing research company in the US in 2002 and 2003 (Advertising Age, Honomichl Report). OTX 
						was acquired in January 2004 by Zelnick Media Group and Pilot Group for $30MM and again, in January 2010 
						by Ipsos for $65MM. She left OTX in December 2005 to start Forefront Consulting Group, a research services 
						consulting firm. Forefront was acquired in June 2007 by Decipher. <br/><br/>

						Along with establishing operational infrastructures firmly rooted in traditional market research methodologies, 
						Kristin has helped blaze a new paradigm for online research tools and data reporting and has infused 
						traditional corporate planning and product development with a bold usage of new and developing technologies 
						and research methods. The result has been the creation of world-class research and development teams that 
						specialize in innovative research solutions combined with cutting edge technologies<br/><br/>

						She is a regular speaker at industry conferences and a columnist for Research Business Report where she 
						explores emerging research methods. Kristin’s a 2010 recipient of the American Marketing Association's 4 
						Under 40 Award, is a 2010 Stevie Awards finalist and was recently named to Oregon's Accomplished Under 40. 
						She has been an instructor at UCLA since 2001 and a guest lecturer at SUNY Albany, where she has taught courses 
						on global entertainment marketing and research. Kristin has over fourteen years of management experience in 
						both domestic and international custom market and social science research with companies such as Oregon Center 
						for Applied Science, Lieberman Research Worldwide, ACNielsen and OTX.
						</div></div>
					</div>
					
					<div class="contentbox">
						<div class="contentboxtitle"><div class="mediumheader">BEN SYKES</div></div>
						<a href="http://www.linkedin.com/in/bsykes" target="_blank">
							<div class="linkedinlogo">
							</div>
						</a>						
						<div id="logo12"></div>
						<div class="downarrow"></div>
						<div class="contentboxsubtitle">Lead User Experience Design Advisor</div>
						<div class="contentboxtext"><div class="alltext">
						Ben Sykes serves as the Company's User Experience Design Advisor who is entrusted with helping guide the 
						continued creation of a seamless and enjoyable user experience for the Samesurf user base. He started taking 
						web development clients in 1995, which led to the creation of his first design consultancy. Ben’s consultancy 
						serviced upwards of 200 clients such as Warner Brothers Music, Artisan Entertainment and Digital Evolution.<br/><br/>

						In 2003, he joined the Marine Corps Reserves and was deployed to Iraq during Operation Iraqi Freedom. Upon his 
						return, Ben continued to work with such companies as (1) Oversee.net where he designed and developed the meta 
						search engine information.com; (2) American Idol Underground where he led the art direction of a web based 
						version of the TV show; (3) NASA, NSA &amp; Oracle where he created faceted search prototypes via Siderean 
						Software; (4) Microsoft where he led multiple UX initiatives; (5) Cisco where he managed and built the Irish 
						UX team and helped integrate WebEx / CUPC; (6) YouSendit where he led the shared workspace design and product 
						offering; and (7) Google where he was a lead on the AdWords team and was instrumental in the creation of 
						multiple features such as the Display Targeting Tab, Alerts, AdWords and Google Help. Ben then went on to 
						lead the design of the big data visualization of self-service dashboards backed by the Google Data Warehouse. 
						He first worked with the Samesurf team in 2010 and led the development of the Company's initial interaction 
						models and UI specifications.
						</div></div>
					</div>
					
					<div class="contentbox">
						<div class="contentboxtitle"><div class="mediumheader">LARRY RUSS</div></div>
						<a href="http://www.linkedin.com/in/larrycruss" target="_blank">
							<div class="linkedinlogo">
							</div>
						</a>						
						<div id="logo13"></div>
						<div class="downarrow"></div>
						<div class="contentboxsubtitle">Lead Legal Advisor</div>
						<div class="contentboxtext"><div class="alltext">
						Larry Russ serves as the Company's Lead Legal Advisor who is entrusted with helping guide Samesurf 
						with regard to legal matters tied to intellectual property protection. He is a founding partner 
						and co-head of the litigation department of Russ August &amp; Kabat. As an active trial attorney, Larry 
						focuses on trademark, copyright, patent, business torts, trade regulation and advertising law and 
						complex litigation. He also works extensively on antitrust and unfair competition matters and has 
						substantial experience representing clients in the home entertainment, technology and communications 
						sectors, including video game hardware manufacturers, computer software developers, electronic toy 
						makers and wireless communications companies. Additionally, Larry consults with established and 
						emerging companies in connection with e-commerce, financing, expansion, mergers and acquisitions, 
						initial public offerings, strategic alliances and intellectual property issues. <br/><br/>

						He is also active in helping emerging companies and is an active investor and advisor to 
						Transom Capital, a firm that recently acquired Blue Microphones, Uncle Milton Toys, Ritz 
						Camera and other diverse companies. For a number of years, Larry served as an associate editor 
						of the Association of Business Trial Lawyers quarterly publication. He is an active member of 
						the Los Angeles County Bar Association, Litigation, Antitrust and Intellectual Property Law 
						Sections as well as an active member of the American Bar Association Antitrust and Intellectual 
						Property Law Sections. Larry was recognized as a Super Lawyer by the Publishers of Los Angeles 
						Magazine from 2008-2014. In 2013 and 2014, Mr. Russ was recognized as a Southern California Top 
						100 Super Lawyer.
						</div></div>
					</div>
					
					<div class="contentbox">
						<div class="contentboxtitle"><div class="mediumheader">JAI CHOI</div></div>
						<a href="http://www.linkedin.com/in/jaichoi" target="_blank">
							<div class="linkedinlogo">
							</div>
						</a>						
						<div id="logo14"></div>
						<div class="downarrow"></div>
						<div class="contentboxsubtitle">Lead Bus. Dev &amp; Partnerships Advisor</div>
						<div class="contentboxtext"><div class="alltext">
						Jai Choi serves as the Company's Business Development and Partnerships Advisor who is entrusted with 
						helping with Samesurf’s partner origination efforts. He is a founder of Tekton Ventures, a seed stage 
						venture fund focused on helping founders build and grow their early stage companies. Jai has spent 
						most of his career as a serial entrepreneur and early stage investor.  He is currently a seed and 
						early stage investor in 30+ companies including Coupang, Attune, Plae, Memebox, Cotopaxi, BitVault, 
						The Orange Chef, Chute, Sidecar, EatClub, Gem, Betable, Signifyd, HotHouse/Stitch, Bugcrowd, PriceMatch, 
						TouchofModern, HeartThis, Younity, Sensopia, UserVoice, GreenCar. He is an accelerator mentor to Mucker 
						Labs, Draper University, SparkLabs and KStartup.<br/><br/>

						Jai was a founder of PeerPong, a cloud-based semantic search company acquired by FormSpring.me in early 
						2011. He is also a venture partner with Partech Ventures, an early stage venture capital firm with offices
						in San Francisco and Paris. Jai joined Partech in late 2006 to focus on Internet, Software and Mobile.<br/><br/>
						
						Prior to Partech, he was a partner with IGNITE Ventures, a $250M venture fund and advisory group with 
						strategic limited partners from major Asia-based technology conglomerates. Jai has extensive experience 
						advising major Asia-based technology companies on new growth platforms, new business formation, joint 
						venture, and M&amp;A. He was an early employee at OnePage Software, a content personalization platform 
						acquired by Sybase in 2001. Jai previously co-founded On-Air Networks in 1997, an online radio company 
						to deliver copyright licensed music over the Internet. On-Air was acquired in late 1999 by Loudeye (Nokia). 
						He started his career in management consulting at PA Consulting Group, focused on market-related and 
						operational issues for major telecom and energy companies. Jai is an advisor to a number of other start-ups 
						including Rivet &amp; Sway and Scoop.it as well as a mentor to accelerator companies Mucker Labs and SparkLabs.
						</div></div>
					</div>
					
					<div class="contentbox">
						<div class="contentboxtitle"><div class="mediumheader">BRIAN WEITMAN</div></div>
						<a href="http://www.linkedin.com/pub/brian-weitman/9/99/585" target="_blank">
							<div class="linkedinlogo">
							</div>
						</a>						
						<div id="logo15"></div>
						<div class="downarrow"></div>
						<div class="contentboxsubtitle">Lead Apparel Industry Advisor</div>
						<div class="contentboxtext"><div class="alltext">
						Brian Weitman serves as the Company's Lead Apparel Industry Advisor who is entrusted with helping guide 
						Samesurf's initiatives within the apparel industry.<br/><br/>

						He is the CEO of STC-QST, a manufacturer and designer based in Los Angeles. STC-QST and QST Industries 
						are the leading suppliers of garment construction materials in the world. Some of the company's core 
						products are interlinings, pocketing, linings, waistbands, and embroidery backings. STC-QST supplie
						some of the leading brands in the world including Polo, Levi's, Guess, St. John Knits, VF, Quiksilver, 
						Hurley, Lucky Brand, True Religion, Hudson, Citizens for Humanity and AG.<br/><br/>

						Brian also founded Security Sourcing International. SSI Apparel is a full service apparel sourcing 
						company providing a broad range of development and production solutions to the better and contemporary 
						markets. SSI Apparel’s clients include Levi’s Vintage Collection (LVC), Chrome Hearts, Stone Cold Fox, 
						as well as many other designer brands. He was a founding partner of Field Scout, a men’s designer 
						clothing brand that sells to high end retailers around the world.  Field Scout makes a large portion 
						of its products in Los Angeles and can be found in Nordstrom, Saks, American Rag, Ron Herman and 
						many other leading retailers.<br/><br/>
						
						Brian is a third generation Apparel Industry Expert with expertise in garment construction, production, 
						global sourcing and distribution. He is currently the President of the Textile Association of Los Angeles, 
						a board member of the California Fashion Association, an advisory board member of the USC Entrepreneur 
						Program and a member of YPO International. He is also a frequent guest lecturer at the University Of 
						Southern California Marshall School Of Business.
						</div></div>
					</div>
					
					<div class="contentbox">
						<div class="contentboxtitle"><div class="mediumheader">KIA STORA</div></div>
						<a href="http://www.linkedin.com/pub/kia-stora/2/b4/3b7" target="_blank">
							<div class="linkedinlogo">
							</div>
						</a>						
						<div id="logo16"></div>
						<div class="downarrow"></div>
						<div class="contentboxsubtitle">Monetization Advisor</div>
						<div class="contentboxtext"><div class="alltext">
						Kia Stora serves as the Company's Monetization Advisor who is entrusted with helping guide Samesurf's 
						monetization efforts. She has over a decade of experience in online business development, specializing 
						in national and geo-targeted search engine optimization and marketing with companies like Chix Creative 
						and LocalCorp. She currently works with a plethora of clients to help monetize their web properties by 
						connecting traffic sources with appropriate advertisers. <br/><br/>

						Throughout her years in the relevant industries, Kia has worked closely with both publishers and advertisers 
						to craft and execute thousands of online marketing and monetization campaigns. In the last few years, she 
						also established and now oversees the day-to-day operations of Matchflow Media.
						</div></div>
					</div>
				</div>	
		</div>	
	</div>	
	