<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/browse.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/browse.js");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>
	<div id="content0">
		<div class="centredcontent">
			
			<div id=content0title><div class="mediumheader">BROWSE TOGETHER</div></div>
			<div id="content0text"><div class="alltext">Unleash crystal clear co-browsing as you shop, watch<br/>
videos and book travel together in real-time.</div></div> 				
			<a href="#" id="topdlbutton" class="enablesite">DEMO SAMESURF</a>
			<div id="browseimage"></div>
			
		</div>	
	</div>	
	
	<div id="content1">
		<div class="centredcontent">
			<div id="content1title"><div class="mediumheader">WHY USE SAMESURF TO BROWSE THE WEB TOGETHER?</div></div>
				<div id="grid">
					<div class="bulletbox">
						<div class="bulletptblue"></div>
					Synced browsing across virtually every website
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptorange"></div>
					Single click access to all of the primary features
					</div>
					
					<div class="bulletbox">
						<div class="bulletptred"></div>
					Cutting edge speed, security and functionality
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptgreen"></div>
					Integrated video chat in parallel with co-browse
					</div>
					
					<div class="bulletbox">
						<div class="bulletptgreen"></div>
					Platform for instant insights on online decisions  
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptred"></div>
					Seamless co-browsing across virtually all devices
					</div>
					
					<div class="bulletbox">
						<div class="bulletptorange"></div>
					Integrated social messaging and one-click invites
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptblue"></div>
					Co-browsing across open and authenticated sites
					</div>
				</div>
		
		</div>
	</div>
	
		
	
	<div id="content2">
		<div class="centredcontent">
			<div id="content2title"><div class="mediumheader">FEATURES</div></div>
				<div id="grid2">
				<a href="/pages/features#content1" class="iconsq1">
					<div id="icon1"></div>
				</a>

				<a href="/pages/features#content6" class="iconsq2">
					<div id="icon2"></div>
				</a>

				<a href="/pages/features#content4" class="iconsq3">
					<div id="icon3"></div>
				</a>

				<a href="/pages/features#content12" class="iconsq4">
					<div id="icon4"></div>
				</a>

				<a href="/pages/features#content8" class="iconsq5">
					<div id="icon5"></div>
				</a>
			</div>	
			
		</div>
	</div>	
	
	<div id="content3">
		<div class="centredcontent">
			
				<div id="assistedsalesvid">
					<iframe src="//player.vimeo.com/video/77007215?title=0&amp;byline=0&amp;portrait=0" 
					width="917" height="516" allowfullscreen></iframe>
				</div>
			
		</div>
	</div>	
	
	<div id="content4">
		<div class="centredcontent">
			<div id="content4image"></div>
				<div id="content4title"><div class="mediumheader">SOCIAL SHARING REIMAGINED</div></div>
						
			<div class="content4text"><div class="alltext">
			Our solutions elevate social sharing from a 
litany of messages into shared experiences 
that live directly on your favorite websites.
</div></div>
		</div>
	</div>	
	
	<div id="content5">
		<div class="centredcontent">
			<div id="content5title"><div class="mediumheader">OPEN AND AUTHENTICATED SITES</div></div>
						
			<div class="content5text"><div class="alltext">
			Samesurf supports seamless co-browsing of open and login<br/>required sites 
			through our Account Sharing functionality. </div></div>
				<div id="content5image"></div>
		</div>
	</div>	
	
		
