<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/browsertesting.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/browsertesting.js");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>
	<div id="content0">
		<div class="centredcontent">
			
			<div id=content0title><div class="mediumheader">BROWSER TESTING</div></div>
			<div id="content0text"><div class="alltext">Conduct compatibility testing to simultaneously preview</br>web projects on different browsers at the same time.</div></div>				
			<a href="#" id="topdlbutton" class="enablesite">DEMO SAMESURF</a>
			<div id="browsertestingimage"></div>
			
		</div>	
	</div>	
	
	<div id="content1">
		<div class="centredcontent">
			<div id="content1title"><div class="mediumheader">WHY USE SAMESURF FOR BROWSER TESTING?</div></div>
				<div id="grid">
					<div class="bulletbox">
						<div class="bulletptblue"></div>
					Test deployments without installing new software
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptorange"></div>
					Transform testing into a true collaborative effort
					</div>
					
					<div class="bulletbox">
						<div class="bulletptred"></div>

					
					Conduct parallel testing across all of your devices
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptgreen"></div>
					Achieve significant time and resource savings
					</div>
					
					<div class="bulletbox">
						<div class="bulletptgreen"></div>
					Perform testing without enduring learning curves
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptred"></div>
					Exhibit site compatibility for clients in real-time
					</div>
					
					<div class="bulletbox">
						<div class="bulletptorange"></div>
					Instantly view cross-browser site modifications
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptblue"></div>
					Leverage testing platform for a multitude of uses
					</div>
				</div>
		
		</div>
	</div>
	
		
	
	<div id="content2">
		<div class="centredcontent">
			<div id="content2title"><div class="mediumheader">FEATURES</div></div>
				<div id="grid2">
					<a href="/pages/features#content1" class="iconsq1">
					<div id="icon1"></div>
				</a>

				<a href="/pages/features#content6" class="iconsq2">
					<div id="icon2"></div>
				</a>

				<a href="/pages/features#content4" class="iconsq3">
					<div id="icon3"></div>
				</a>

				<a href="/pages/features#content12" class="iconsq4">
					<div id="icon4"></div>
				</a>

				<a href="/pages/features#content8" class="iconsq5">
					<div id="icon5"></div>
				</a>
				</div>		
			
		</div>
	</div>	
	
	<div id="content3">
		<div class="centredcontent">
			<div id="assistedsalesvid">
					<iframe src="//player.vimeo.com/video/77007215?title=0&amp;byline=0&amp;portrait=0" 
					width="917" height="516" allowfullscreen></iframe>
				</div>
			
		</div>
	</div>	
	
	<div id="content4">
		<div class="centredcontent">
			<div id="content4image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/simbrowsetest.png" /></div>
				<div id="content4title"><div class="mediumheader">SYNCED BROWSER TESTING</div></div>
						
			<div class="content4text"><div class="alltext">
			Use Samesurf for compatibility testing and preview development updates on multiple browsers and devices at the same time.</div></div>
		</div>
	</div>	
	
	<div id="content5">
		<div class="centredcontent">
			<div id="content5title"><div class="mediumheader">NO INSTALLS OR HARDWARE</div></div>
						
			<div class="content5text"><div class="alltext">
			Perform seamless compatibility testing on<br/> multiple projects without enduring installs,<br/>custom coding or steep learning curves. </div></div>
				<div id="content5image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/noinstalls.png" /></div>
		</div>
	</div>	
	
		
