<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/collaboration.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/collaboration.js");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>
	<div id="content0">
		<div class="centredcontent">
			
			<div id=content0title><div class="mediumheader">COLLABORATION</div></div>
			<div id="content0text"><div class="alltext">Infuse visual context into conversations via our<br/>simple and instant platform for collaboration.</div></div>
			<a href="#" id="topdlbutton" class="enablesite">DEMO SAMESURF</a>
			<div id="collaborationimage"></div>
			
		</div>
	</div>
	
	<div id="content1">
		<div class="centredcontent">
			<div id="content1title"><div class="mediumheader">WHY USE SAMESURF FOR COLLABORATION?</div></div>
				<div id="grid">
					<div class="bulletbox">
						<div class="bulletptblue"></div>
					Multi-way interactive experience for all attendees
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptorange"></div>
					Robust offering for cross-platform collaboration
					</div>
					
					<div class="bulletbox">
						<div class="bulletptred"></div>
					Simultaneous co-browsing for up to 5000 people
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptgreen"></div>
					Pristine screen clarity featuring minimal latency
					</div>
					
					<div class="bulletbox">
						<div class="bulletptgreen"></div>
					Install-free collaboration on virtually every device
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptred"></div>
					Simple requesting and passing of leader controls
					</div>
					
					<div class="bulletbox">
						<div class="bulletptorange"></div>
					Co-browsing of rich media, film and video content
					</div>
					
					<div class="bulletbox2">

						<div class="bulletptblue"></div>
					Instant toggling between online & offline content
					</div>
				</div>
		
		</div>
	</div>
	
		
	
	<div id="content2">
		<div class="centredcontent">
			<div id="content2title"><div class="mediumheader">FEATURES</div></div>
				<div id="grid2">
				<a href="/pages/features#content1" class="iconsq1">
					<div id="icon1"></div>
				</a>

				<a href="/pages/features#content6" class="iconsq2">
					<div id="icon2"></div>
				</a>

				<a href="/pages/features#content4" class="iconsq3">
					<div id="icon3"></div>
				</a>

				<a href="/pages/features#content12" class="iconsq4">
					<div id="icon4"></div>
				</a>

				<a href="/pages/features#content8" class="iconsq5">
					<div id="icon5"></div>
				</a>
			</div>	
			
		</div>
	</div>	
	
	<div id="content3">
		<div class="centredcontent">
			<div id="assistedsalesvid">
					<iframe src="//player.vimeo.com/video/77007215?title=0&amp;byline=0&amp;portrait=0" 
					width="917" height="516" allowfullscreen></iframe>
				</div>			
		</div>
	</div>	
	
	<div id="content4">
		<div class="centredcontent">
			<div id="content4image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/interactive.png" /></div>
				<div id="content4title"><div class="mediumheader">MULTI-WAY INTERACTIVITY</div></div>
						
			<div class="content4text"><div class="alltext">All users may remain active during sessions<br/>
by passing the controls and simultaneously<br/>
interacting with the same sites in real-time.</div></div>
		</div>
	</div>	
	
	<div id="content5">
		<div class="centredcontent">
			<div id="content5title"><div class="mediumheader">TRULY CROSS PLATFORM</div></div>
						
			<div class="content5text"><div class="alltext">Access the full suite of Samesurf offerings on<br/>
			virtually every browser, operating system and<br/>web-enabled device.</div></div>
				<div id="content5image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/osicons.png" /></div>
		</div>
	</div>	
