<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/contactus.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/contactus.js");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>
<div id="contact_us_container">
	<div id="contact_us">
		<div id="contact_us_header">
			<div class="mediumheader">
				CONTACT US 
			</div>
		</div>
	</div>
</div>

<div id="input_fields_container">
	<div id="input_fields">
		<form>
			<div id="first_name_input">
				<div class="input_field_text">
					FIRST NAME
					<p>
						*
					<p>
				</div>
				<div id="first_name">
					<input type="text" class="text_input" name="q" size="40" maxlength="200"> 
				</div>
			</div>
			<div id="last_name_input">
				<div class="input_field_text">
					LAST NAME
					<p>
						*
					<p>
				</div>
				<div id="last_name">
					<input type="text" class="text_input" name="q" size="40" maxlength="200"> 
				</div>
			</div>
			<div >
				<div class="input_field_text">
					EMAIL ADDRESS
					<p>
						*
					<p>
				</div>
				<input type="text" class="text_input" name="q" size="40" maxlength="200"> 
			</div>
			<div >
				<div class="input_field_text">
					COMPANY
				</div>
				<input type="text" class="text_input" name="q" size="40" maxlength="200"> 
			</div>
			<div id="message_text" class="input_field_text">
				MESSAGE
				<p>
					*
				<p>
			</div>
			<div id="message">
				<textarea id="message_text_input" name="q"></textarea>
			</div>
			<div id="all_fields_text">
				* = INDICATES REQUIRED FIELDS 
			</div>
			<button id="send_message_button" class="button_text">
				SEND MESSAGE 
			</button>
		</form>
	</div>
</div>


