<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/corptraining.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/corptraining.js");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>
	<div id="content0">
		<div class="centredcontent">
			
			<div id=content0title><div class="mediumheader">CORPORATE TRAINING</div></div>
			<div id="content0text"><div class="alltext">Empower instructors to educate hundreds of trainees at<br/>
the same time without requiring installs or coding.</div></div>				
			<a href="#" id="topdlbutton" class="enablesite">DEMO SAMESURF</a>
			<div id="corptrainingimage"></div>
			
		</div>	
	</div>	
	
	<div id="content1">
		<div class="centredcontent">
			<div id="content1title"><div class="mediumheader">WHY USE SAMESURF FOR CORPORATE TRAINING?</div></div>
				<div id="grid">
					<div class="bulletbox">
						<div class="bulletptblue"></div>
					Significant time and overall expense reductions
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptorange"></div>
					Training for up to 5000 users in a single session
					</div>
					
					<div class="bulletbox">
						<div class="bulletptred"></div>
					Highly scalable offering for corporate training
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptgreen"></div>
					Cross platform support for virtually every device  
					</div>
					
					<div class="bulletbox">
						<div class="bulletptgreen"></div>
					Multi-way interactivity featuring control passing
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptred"></div>
					Instant sharing of both online and offline content
					</div>
					
					<div class="bulletbox">
						<div class="bulletptorange"></div>
					Ability to leverage all existing training materials
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptblue"></div>
					Expansive safeguards for security and privacy
					</div>
				</div>
		
		</div>
	</div>
	
		
	
	<div id="content2">
		<div class="centredcontent">
			<div id="content2title"><div class="mediumheader">FEATURES</div></div>
				<div id="grid2">
				<a href="/pages/features#content1" class="iconsq1">
					<div id="icon1"></div>
				</a>

				<a href="/pages/features#content6" class="iconsq2">
					<div id="icon2"></div>
				</a>

				<a href="/pages/features#content4" class="iconsq3">
					<div id="icon3"></div>
				</a>

				<a href="/pages/features#content12" class="iconsq4">
					<div id="icon4"></div>
				</a>

				<a href="/pages/features#content8" class="iconsq5">
					<div id="icon5"></div>
				</a>
			</div>	
			
		</div>
	</div>	
	
	<div id="content3">
		<div class="centredcontent">
			<div id="assistedsalesvid">
					<iframe src="//player.vimeo.com/video/77007215?title=0&amp;byline=0&amp;portrait=0" 
					width="917" height="516" allowfullscreen></iframe>
			</div>
			
		</div>
	</div>	
	
	<div id="content4">
		<div class="centredcontent">
			<div id="content4image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/trainees.png" /></div>
				<div id="content4title"><div class="mediumheader">UNLIMITED TRAINEES</div></div>
						
			<div class="content4text"><div class="alltext">Our solutions support up to 5000 users in a<br/>single co-browse session without triggering<br/>connection, latency and security concerns.</div></div>
		</div>
	</div>	
	
	<div id="content5">
		<div class="centredcontent">
			<div id="content5title"><div class="mediumheader">TRAINING IN THE CLOUD</div></div>
						
			<div class="content5text"><div class="alltext">Samesurf enables instructors and trainees to<br/>instantly co-browse content together from<br/>virtually any device or browser.</div></div>
				<div id="content5image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/cloudtraining.png" /></div>
		</div>
	</div>	
