<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/customization.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/customization.js");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>
	<div id="content0">
		<div class="centredcontent">
			
			<div id=content0title><div class="mediumheader">CUSTOMIZATION</div></div>
			<div id="content0text"><div class="alltext">Configure the design and features for each experience<br/>
			to suit specific uses and brand requirements.</div></div>				
			<a href="#" id="topdlbutton" class="enablesite">DEMO SAMESURF</a>
			
		</div>	
	</div>	
	

	<div id="content1">
		<div class="centredcontent">
							
				<div id="content1title"><div class="mediumheader">PREVIEW VERSIONS</div></div>
				
				<div id="buttongrid">
						<a id="button1">SALES</a>
						<a id="button2">SUPPORT</a>
						<a id="button3">SOCIAL</a>
				</div>	
			
				<div id="content1image2"></div>
				<div id="content1image3"></div>
				<div id="content1image1"></div>
			
		</div>
	</div>
	
	<div id="content2">
		<div class="centredcontent">
			
				
			<div class="imagetable">
				<div id="content2image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/customsidebar.png" /></div>
			</div>	
			
			<div id="content2group">
			
				<div class="titletable">	
					<div id="content2title"><div class="mediumheader">CUSTOMIZE THEMES</div></div>
				</div>
			
					<div id="content2text"><div class="alltext">Construct white label experiences that<br/>match your branding requirements by<br/>modifying design elements on the fly.</div></div>
				</div>
		</div>
	</div>
	


	<div id="content3">	
		<div class="centredcontent">
			<div id="content3group">
				<div class="titletable">	
						<div id="content3title"><div class="mediumheader">SELECT YOUR FEATURES</div></div>
					</div>
				
					<div id="content3text"><div class="alltext">Select from a variety of configurable options to craft tailored<br/> 
					experiences that fit the sensibilities of your user base.</div></div>
				</div>
					<div id="content3image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/browsetogether.png" /></div>
			</div>	
				
		</div>	
					

	<div id="content4">
		<div class="centredcontent">
			<div id="content4group">
				<div class="titletable">	
						<div id="content4title"><div class="mediumheader">FEATURE SUMMARY</div></div>
				</div>
				<div class="content4view">
					<img src="/static/images/pages/hiwurl.png" alt="image" />
					<div class="box">
						<div id="grid">
							<a href="/pages/features#content1" class="iconsq01">
								<div id="icon01"></div>
							</a>

							<a href="/pages/features#content2" class="iconsq02">
								<div id="icon02"></div>
							</a>

							<a href="/pages/features#content3" class="iconsq03">
								<div id="icon03"></div>
							</a>

							<a href="/pages/features#content4" class="iconsq04">
								<div id="icon04"></div>
							</a>

							<a href="/pages/features#content5" class="iconsq05">
								<div id="icon05"></div>
							</a>

							<a href="/pages/features#content6" class="iconsq06">
								<div id="icon06"></div>
							</a>

							<a href="/pages/features#content7" class="iconsq07">
								<div id="icon07"></div>
							</a>

							<a href="/pages/features#content8" class="iconsq08">
								<div id="icon08"></div>
							</a>

							<a href="/pages/features#content12" class="iconsq09">
								<div id="icon09"></div>
							</a>

							<a href="/pages/features#content10" class="iconsq10">
								<div id="icon10"></div>
							</a>
						</div>	
					</div>
				</div>
			</div>
		</div>
	</div>			
							
