<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/different.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/different.js");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>
	<div id="content0">
		<div class="centredcontent">
			
			<div id=content0title><div class="mediumheader">WE'RE DIFFERENT</div></div>
				<a href="#" id="topdlbutton" class="enablesite">DEMO SAMESURF</a>
								
		</div>	
	</div>	
	
	<div id="content1">
		<div class="centredcontent">
			<div id="content1title"><div class="mediumheader">LIGHTNING FAST</div></div>
						
			<div class="content1text"><div class="alltext">Samesurf transcends screen sharing by<br/>delivering crystal clear experiences that<br/>travel at the speed of light. </div></div>
				<div id="content1image"></div>
		</div>
	</div>	
	
	<div id="content2">
		<div class="centredcontent">
			<div id="content2image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/everybodyclicks.png" /></div>
				<div id="content2title"><div class="mediumheader">MULTI-WAY INTERACTIVITY</div></div>
						
			<div class="content2text"><div class="alltext">All users may remain active during sessions<br/>by passing the controls and simultaneously<br/>interacting with the same sites in real-time. 
</div></div>
		</div>
	</div>	
	
	<div id="content3">
		<div class="centredcontent">
			<div id="content3title"><div class="mediumheader">SHARE ONLY WHAT YOU WANT</div></div>
						
			<div class="content3text"><div class="alltext">Samesurf supports enhanced security via<br/>sharing of a single tab, blocking of private<br/>entries and enterprise grade encryption.</div></div>
				<div id="content3image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/userprivacy.png" /></div>
		</div>
	</div>	
	
	<div id="content4">
		<div class="centredcontent">
			<div id="content4image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/noinstallsgreen.png" /></div>
				<div id="content4title"><div class="mediumheader">NO INSTALLS REQUIRED</div></div>
						
			<div class="content4text"><div class="alltext">Instant co-browsing requires no installs,<br/>coding or site modifications in terms of<br/>starting and joining active sessions.</div></div>
		</div>
	</div>	
	
	<div id="content5">
		<div class="centredcontent">
			<div id="content5title"><div class="mediumheader">THOUSANDS IN A SINGLE ROOM</div></div>
						
			<div class="content5text"><div class="alltext">Samesurf supports co-browsing for up to<br/>5000 users in one session from virtually<br/>any web-enabled device or browser.</div></div>
				<div id="content5image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/thousands.png" /></div>
		</div>
	</div>	
	
	<div id="content6">
		<div class="centredcontent">
			<div id="content6image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/videoshare.png" /></div>
				<div id="content6title"><div class="mediumheader">SEAMLESS VIDEO SHARING</div></div>
						
			<div class="content6text"><div class="alltext">Our offerings support perfectly synced<br/>video sharing without the interruptions<br/>and lag
that come with screen sharing.</div></div>
		</div>
	</div>	
	
	<div id="content7">
		<div class="centredcontent">
			<div id="content7title"><div class="mediumheader">LIGHT AS A FEATHER</div></div>
						
			<div class="content7text"><div class="alltext">Samesurf's resource efficient footprint powers <br/>co-browsing that won't slow down devices or<br/> use large amounts of bandwidth and memory.  </div></div>
				<div id="content7image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/feather.png" /></div>
		</div>
	</div>	
	

