<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/education.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/education.js");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>
	<div id="content0">
		<div class="centredcontent">
			
			<div id=content0title><div class="mediumheader">EDUCATION</div></div>
			<div id="content0text"><div class="alltext">Collaborate on activities ranging from group projects</br>to classroom simulations for distance learning.</div></div>				
			<a href="#" class="enablesite" id="topdlbutton">DEMO SAMESURF</a>
			<div id="educationimage"></div>
			
		</div>	
	</div>	
	
	<div id="content1">
		<div class="centredcontent">
			<div id="content1title"><div class="mediumheader">WHY USE SAMESURF WITHIN EDUCATION?</div></div>
				<div id="grid">
					<div class="bulletbox">
						<div class="bulletptblue"></div>
					Real-time distance learning without any installs
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptorange"></div>
					Greater interaction via multi-way control passing
					</div>
					
					<div class="bulletbox">
						<div class="bulletptred"></div>
					Simple user framework for coordinated research
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptgreen"></div>
					Effective mobile solution for web-based learning
					</div>
					
					<div class="bulletbox">
						<div class="bulletptgreen"></div>
					Broad connectivity counterbalances digital divide 
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptred"></div>
					Ideal tool for remote group projects and studies
					</div>
					
					<div class="bulletbox">
						<div class="bulletptorange"></div>
					Fun and engaging platform for online education </div>
					
					<div class="bulletbox2">
						<div class="bulletptblue"></div>
					Truly interactive presentations within classrooms
					</div>
				</div>
		
		</div>
	</div>
	
		
	
	<div id="content2">
		<div class="centredcontent">
			<div id="content2title"><div class="mediumheader">FEATURES</div></div>
				<div id="grid2">
					<a href="/pages/features#content1" class="iconsq1">
					<div id="icon1"></div>
				</a>

				<a href="/pages/features#content6" class="iconsq2">
					<div id="icon2"></div>
				</a>

				<a href="/pages/features#content4" class="iconsq3">
					<div id="icon3"></div>
				</a>

				<a href="/pages/features#content12" class="iconsq4">
					<div id="icon4"></div>
				</a>

				<a href="/pages/features#content8" class="iconsq5">
					<div id="icon5"></div>
				</a>
				</div>		
			
		</div>
	</div>	
	
	<div id="content3">
		<div class="centredcontent">
			<div id="assistedsalesvid">
					<iframe src="//player.vimeo.com/video/77007215?title=0&amp;byline=0&amp;portrait=0" 
					width="917" height="516" allowfullscreen></iframe>
			</div>
			
		</div>
	</div>	
	
	<div id="content4">
		<div class="centredcontent">
			<div id="content4image"></div>
				<div id="content4title"><div class="mediumheader">LEARNING WITHOUT BORDERS</div></div>
						
			<div class="content4text"><div class="alltext">Our offerings enable immersive distance<br/> 
			learning for thousands of simultaneous<br/>students within one unified platform.
			</div></div>
		</div>
	</div>	
	
	<div id="content5">
		<div class="centredcontent">
			<div id="content5title"><div class="mediumheader">COLLABORATIVE RESEARCH</div></div>
						
			<div class="content5text"><div class="alltext">Samesurf empowers students and faculty<br/>
			to engage in collaborative research across<br/>
			institutions that span the globe.<br/>
			</div></div>
				<div id="content5image"></div>
		</div>
	</div>	
