<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/enablesite.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/enablesite.js");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>
	<div id="content0">
		<div class="centredcontent">
			
			<div id=content0title><div class="mediumheader">ENABLE YOUR SITE</div></div>
			<div id=content0text><div class="alltext">Integrate Samesurf into any experience and instantly enable<br/>
users to interact with online content together in real-time.</div></div>
			<div class="buttons">
				<a href="#" class="taketour-btn">TAKE THE TOUR</a>
				<a href ="/signup" class="signup-btn">CLICK TO START</a>
			</div>
		</div>
	</div>
	
<div id="key_uses_box_container">
	<div id="key_uses_box">
		<div id="key_uses_text">
			<div class="mediumheader">KEY USES</div>
		</div>
		<div id="circles_div">
			<a href="">
			<div class="key_uses_circles">
				<div id="headphones_circle">
				</div>
			</div>
			</a>
			<div class="key_uses_circles">
				<div id="hand_shake">
				</div>
			</div>
			<div class="key_uses_circles">
				<div id="high_five">
				</div>
			</div>
			<div class="key_uses_circles">
				<div id="whiteboard">
				</div>
			</div>
			<div class="key_uses_circles">
				<div id="trolley">
				</div>
			</div>
			<div class="key_uses_circles">
				<div id="blackboard">
				</div>
			</div>
			<div class="key_uses_circles">
				<div id="three_heads">
				</div>
			</div>
			<div class="key_uses_circles">
				<div id="mortar_board">
				</div>
			</div>
		</div>	
	</div>
</div>

	<div id="content2">
		<div class="centredcontent">
			<div id=content2text><div class="alltext"><a href="/pages/secondaryuses">Click to view Secondary Uses.</a></div></div>
		</div>
	</div>	
	
