<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/error404.css");
	$this->addCSSFile("/static/css/pages/general.css");
?>

<div id="container">
	<div id="page">
		<div id="header_number">
			404
		</div>
		<div id="header_text">	
			PAGE NOT FOUND
		</div>
		<div id="errortext">We're unable to find the page you're looking for.<br/>
		Please try again or return to the homepage.</div>
		<a href="http://www.samesurf.com"><div id="returnbutton">RETURN TO SAMESURF.COM</div></a>
	</div>
</div>