<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/error500.css");
	$this->addCSSFile("/static/css/pages/general.css");
?>

<div id="container">
	<div id="page">
		<div id="header_number">
			500
		</div>
		<div id="header_text">	
			INTERNAL SERVER ERROR
		</div>
		<div id="errortext">An internal server error has occurred and we're working to <br/>
resolve the issue. Please try again in a few minutes.
		</div>
		<a href="http://www.samesurf.com"><div id="returnbutton">RETURN TO SAMESURF.COM</div></a>
	</div>
</div>
