<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/faqs.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/faqs.js");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>

	<div id="faqs_container">
		<div id="faqs_box_container">
			<div id="faqs_box">
				<div id="faqs_heading" class="headings">
					<div class="mediumheader">FREQUENTLY ASKED QUESTIONS</div>
				</div>
			
				<div id="faqs_search">
					<form>
						<input type="text" class="faqs_text_input" name="q" size="40" maxlength="200">
					</form>
				</div>
			</div>
		</div>
	</div>
			

	<div id="content1">		
		<div class="centredcontent">
			
			<div class="title">
				<div class="mediumheader">
					THE BASICS
				</div>
			</div>
			
				<div class="contentbox">
						<div class="contentboxtitle">
							What is samesurf?
						</div>
					
						<div class="downarrow"></div>
						<div class="contentboxtext"><div class="alltext">
						Samesurf is a fast, free and delightfully simple way to instantly experience the web together with friends, 
						family and colleagues. It's a lightning fast browser, public rooms site and website platform that transcends 
						screen sharing by giving life to a crystal clear new way to share your browsing experiences in real-time. 
						</div></div>
						
				</div>
				
				<div class="contentbox">
						<div class="contentboxtitle">
							What are Public Rooms?
						</div>
					
						<div class="downarrow"></div>
						<div class="contentboxtext"><div class="alltext">
						Samesurf is a fast, free and delightfully simple way to instantly experience the web together with friends, 
						family and colleagues. It's a lightning fast browser, public rooms site and website platform that transcends 
						screen sharing by giving life to a crystal clear new way to share your browsing experiences in real-time.
						</div></div>
						
				</div>
				
				<div class="contentbox">
						<div class="contentboxtitle">
							What is screensharenow.com?
						</div>
					
						<div class="downarrow"></div>
						<div class="contentboxtext"><div class="alltext">
						Samesurf is a fast, free and delightfully simple way to instantly experience the web together with friends, 
						family and colleagues. It's a lightning fast browser, public rooms site and website platform that transcends 
						screen sharing by giving life to a crystal clear new way to share your browsing experiences in real-time.
						</div></div>
						
				</div>
				
				<div class="contentbox">
						<div class="contentboxtitle">
							What is an Enabled Site?
						</div>
					
						<div class="downarrow"></div>
						<div class="contentboxtext"><div class="alltext">
						Samesurf is a fast, free and delightfully simple way to instantly experience the web together with friends, 
						family and colleagues. It's a lightning fast browser, public rooms site and website platform that transcends 
						screen sharing by giving life to a crystal clear new way to share your browsing experiences in real-time.
						</div></div>
						
				</div>
				
				<div class="title">
				<div class="mediumheader">
					FEATURES
				</div>
			</div>
			
				<div class="contentbox">
						<div class="contentboxtitle">
							What is samesurf?
						</div>
					
						<div class="downarrow"></div>
						<div class="contentboxtext"><div class="alltext">
						Samesurf is a fast, free and delightfully simple way to instantly experience the web together with friends, 
						family and colleagues. It's a lightning fast browser, public rooms site and website platform that transcends 
						screen sharing by giving life to a crystal clear new way to share your browsing experiences in real-time.
						</div></div>
						
				</div>
				
				<div class="contentbox">
						<div class="contentboxtitle">
							What are Public Rooms?
						</div>
					
						<div class="downarrow"></div>
						<div class="contentboxtext"><div class="alltext">
						Samesurf is a fast, free and delightfully simple way to instantly experience the web together with friends, 
						family and colleagues. It's a lightning fast browser, public rooms site and website platform that transcends 
						screen sharing by giving life to a crystal clear new way to share your browsing experiences in real-time.
						</div></div>
						
				</div>
				
				<div class="contentbox">
						<div class="contentboxtitle">
							What is screensharenow.com?
						</div>
					
						<div class="downarrow"></div>
						<div class="contentboxtext"><div class="alltext">
						Samesurf is a fast, free and delightfully simple way to instantly experience the web together with friends, 
						family and colleagues. It's a lightning fast browser, public rooms site and website platform that transcends 
						screen sharing by giving life to a crystal clear new way to share your browsing experiences in real-time.
						</div></div>
						
				</div>
				
				<div class="contentbox">
						<div class="contentboxtitle">
							What is an Enabled Site?
						</div>
					
						<div class="downarrow"></div>
						<div class="contentboxtext"><div class="alltext">
						Samesurf is a fast, free and delightfully simple way to instantly experience the web together with friends, 
						family and colleagues. It's a lightning fast browser, public rooms site and website platform that transcends 
						screen sharing by giving life to a crystal clear new way to share your browsing experiences in real-time.
						</div></div>
						
				</div>
				
				<div class="title">
				<div class="mediumheader">
					PRIVACY
				</div>
			</div>
			
				<div class="contentbox">
						<div class="contentboxtitle">
							What is samesurf?
						</div>
					
						<div class="downarrow"></div>
						<div class="contentboxtext"><div class="alltext">
						Samesurf is a fast, free and delightfully simple way to instantly experience the web together with friends, 
						family and colleagues. It's a lightning fast browser, public rooms site and website platform that transcends 
						screen sharing by giving life to a crystal clear new way to share your browsing experiences in real-time.
						</div></div>
						
				</div>
				
				<div class="contentbox">
						<div class="contentboxtitle">
							What are Public Rooms?
						</div>
					
						<div class="downarrow"></div>
						<div class="contentboxtext"><div class="alltext">Samesurf is a fast, free and delightfully simple way to instantly experience the web together with friends, 
						family and colleagues. It's a lightning fast browser, public rooms site and website platform that transcends 
						screen sharing by giving life to a crystal clear new way to share your browsing experiences in real-time.
						</div></div>
						
				</div>
				
				<div class="contentbox">
						<div class="contentboxtitle">
							What is screensharenow.com?
						</div>
					
						<div class="downarrow"></div>
						<div class="contentboxtext"><div class="alltext">
						Samesurf is a fast, free and delightfully simple way to instantly experience the web together with friends, 
						family and colleagues. It's a lightning fast browser, public rooms site and website platform that transcends 
						screen sharing by giving life to a crystal clear new way to share your browsing experiences in real-time.
						</div></div>
						
				</div>
				
				<div class="contentbox">
						<div class="contentboxtitle">
							What is an Enabled Site?
						</div>
					
						<div class="downarrow"></div>
						<div class="contentboxtext"><div class="alltext">
						Samesurf is a fast, free and delightfully simple way to instantly experience the web together with friends, 
						family and colleagues. It's a lightning fast browser, public rooms site and website platform that transcends 
						screen sharing by giving life to a crystal clear new way to share your browsing experiences in real-time.
						</div></div>
						
				</div>
					
		</div>	
	</div>	
