<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/forwebsites.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/forwebsites.js");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>
	<div id="content0">
		<div class="centredcontent">
			
			<div id=content0title><div class="mediumheader">FOR WEBSITES</div></div>
			<div id="content0text"><div class="alltext">Convert visitors seeking validation for online decisions<br/>
			into valued customers who recruit friends and family.</div></div>
			<a href="#" id="topdlbutton" class="enablesite">DEMO SAMESURF</a>
			<div id="forwebsitesimage"></div>
			
		</div>	
	</div>	
	
	<div id="content1">
		<div class="centredcontent">
			<div id="content1title"><div class="mediumheader">WHY INTEGRATE SAMESURF ONTO WEBSITES?</div></div>
				<div id="grid">
					<div class="bulletbox">
						<div class="bulletptblue"></div>
					Markedly higher conversions on e-commerce sites 
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptorange"></div>
					Elevated time on site levels for content sites
					</div>
					
					<div class="bulletbox">
						<div class="bulletptred"></div>
					Highly effective platform for viral lead origination
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptgreen"></div>
					Heightened satisfaction rates for site visitors
					</div>
					
					<div class="bulletbox">
						<div class="bulletptgreen"></div>
					Peer-to-peer site assistance reduces support costs
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptred"></div>
					Instant catalyst for socialization and interactivity
					</div>
					
					<div class="bulletbox">
						<div class="bulletptorange"></div>
					Simple UI design, text and feature customization 
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptblue"></div>
					Versatile framework that supports multiple uses
					</div>
				</div>
		
		</div>
	</div>
	
		
	
	<div id="content2">
		<div class="centredcontent">
			<div id="content2title"><div class="mediumheader">FEATURES</div></div>
				<div id="grid2">
					<a href="/pages/features#content1" class="iconsq1">
					<div id="icon1"></div>
				</a>

				<a href="/pages/features#content6" class="iconsq2">
					<div id="icon2"></div>
				</a>

				<a href="/pages/features#content4" class="iconsq3">
					<div id="icon3"></div>
				</a>

				<a href="/pages/features#content12" class="iconsq4">
					<div id="icon4"></div>
				</a>

				<a href="/pages/features#content8" class="iconsq5">
					<div id="icon5"></div>
				</a>
				</div>		
			
		</div>
	</div>	
	
	<div id="content3">
		<div class="centredcontent">
			<div id="assistedsalesvid">
					<iframe src="//player.vimeo.com/video/77007215?title=0&amp;byline=0&amp;portrait=0" 
					width="917" height="516" frameborder="0" allowfullscreen></iframe>
			</div>
			
		</div>
	</div>	
	
	<div id="content4">
		<div class="centredcontent">
			<div id="content4image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/customsidebar.png" /></div>
				<div id="content4title"><div class="mediumheader">FULL CUSTOMIZATION</div></div>
						
			<div class="content4text"><div class="alltext">Our solutions enable customization of the<br/>
features, messaging and theming for each<br/>experience to fit specific requirements.</div></div>
		</div>
	</div>	
	
	<div id="content5">
		<div class="centredcontent">
			<div id="content5title"><div class="mediumheader">NO CODING REQUIREMENTS</div></div>
						
			<div class="content5text"><div class="alltext">Samesurf’s non-reliance on code placements</br>leaves co-browsing unaffected by frequent </br>modifications to shared websites.</div></div>
				<div id="content5image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/integration.png" /></div>
		</div>
	</div>	
	