<?php $this->setTitle("samesurf"); $this->addCSSFile("/static/css/pages/HIWpresentation.css"); $this->addCSSFile("/static/css/pages/general.css"); $this->addJSFile("/static/js/pages/HIWpresentation.js"); $this->addJSFile("/static/js/pages/lazyload.js"); $this->addJSFile("/static/js/pages/animate.js");
$this->addCSSFile("/static/css/pages/lazyload.css"); $this->addCSSFile("/static/css/pages/animate.css"); ?>

<div id="titlebar">
	<div class="centredcontent">
		<div id="titlebartable">
			<div class="mediumheader">HOW PRESENTATIONS WORK</div>
		</div>

		<a href="#" class="enablesite" id="visitbutton">VISIT SAMESLIDE.COM</a>

	</div>
</div>


<div id="content1">
	<div class="centredcontent">
		<div id="content1group">
			<div class="titletable">

				<div id="circle1">1</div>
				<div id="content1title">
					<div class="mediumheader">UPLOAD CONTENT</div>
				</div>
			</div>

			<div class="content">
				<div class="alltext">Upload slides, video links and sites
					<br/>you'll be showcasing during your 
					<br/>presentation to the Samesurf Cloud.</div>
			</div>
		</div>
		<div class="imagetable">
			<div id="content1image">
				<img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/uploadcontent.png" />
			</div>
		</div>
	</div>
</div>

<div id="content2">
	<div class="centredcontent">


		<div class="imagetable">
			<div id="content2image">
				<img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/organize.png" />
			</div>
		</div>

		<div id="content2group">

			<div class="titletable">

				<div id="circle2">2</div>
				<div id="content2title">
					<div class="mediumheader">ORGANIZE</div>
				</div>
			</div>

			<div id="content2text">
				<div class="alltext">Put your slides, videos and websites
					<br/>in chronological order to create and
					<br/>preview each presentation.</div>
			</div>
		</div>
	</div>
</div>


<div id="content3">
	<div class="centredcontent">
		<div id="content3newgroup">
			<div class="titletable">

				<div id="circle3">3</div>
				<div id="content3newtitle">
					<div class="mediumheader">PRESENT</div>
				</div>
			</div>

			<div class="content">
				<div class="alltext">Start a room and send out invites once<br/>
				your presentation is ready. As leader,<br/>
				you can toggle between presentations and
				shared browsing of web content.</div>
			</div>
		</div>
		<div class="imagetable">
			<div id="content3image">
				<img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/present.png" />
			</div>
		</div>
	</div>
</div>


<div id="content4">
	<div class="centredcontent">
		<div id="content3group">
			<div class="titletable">
				<div id="circle4">4</div>
				<div id="content3title">
					<div class="mediumheader">CO-BROWSE</div>
				</div>
			</div>

			<div id="content3text">
				<div class="alltext">Browse together from page to page, pass the leader controls 
					<br/>and share the web in real-time during the presentation.</div>
			</div>
		</div>
		<div id="content4image">
			<img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/browsetogether.png" />
		</div>
	</div>
</div>

<div id="content5">
	<div class="centredcontent">
		<div id="content5group">
			<div class="titletable">	
				<div id="circle5">5</div>	
				<div id="content4title"><div class="mediumheader">EXPLORE THE FEATURES</div></div>
			</div>
			<div class="content4view">
				<img src="/static/images/pages/hiwurl.png" alt="Image" />
				<div class="box">
					<div id="grid">
						
						<a href="/pages/features#content1" class="iconsq01">
							<div id="icon01"></div>
						</a>

						<a href="/pages/features#content2" class="iconsq02">
							<div id="icon02"></div>
						</a>

						<a href="/pages/features#content3" class="iconsq03">
							<div id="icon03"></div>
						</a>

						<a href="/pages/features#content4" class="iconsq04">
							<div id="icon04"></div>
						</a>

						<a href="/pages/features#content5" class="iconsq05">
							<div id="icon05"></div>
						</a>

						<a href="/pages/features#content6" class="iconsq06">
							<div id="icon06"></div>
						</a>

						<a href="/pages/features#content7" class="iconsq07">
							<div id="icon07"></div>
						</a>

						<a href="/pages/features#content8" class="iconsq08">
							<div id="icon08"></div>
						</a>

						<a href="/pages/features#content12" class="iconsq09">
							<div id="icon09"></div>
						</a>

						<a href="/pages/features#content10" class="iconsq10">
							<div id="icon10"></div>
						</a>
					</div>	
				</div>
			</div>
		</div>
	</div>
</div>	

<div id="content6">
	<div class="centredcontent">
		<div id="content6text">
			<div class="alltext">
				<a href="http://www.samesurf.com">Preview</a> Co-browsing on the Desktop.
				<br/>
				<a href="http://www.samesurf.com">Preview</a> Co-browsing on the Mobile.
				<br/>
			</div>
		</div>
	</div>
</div>


