<?php 
	$this->setTitle("samesurf"); 
	$this->addCSSFile("/static/css/pages/homepage.css"); 
	$this->addCSSFile("/static/css/pages/general.css"); 
	$this->addJSFile("/static/js/pages/homepage.js"); 
	$this->addJSFile("/static/js/pages/lazyload.js"); 
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/animate.css");
?>
<!--[if lt IE 9]>
<script>
document.createElement('video');
</script>
<![endif]-->
<div id="sliding_banner_container">
	<video autoplay loop id="bgvid">
		<source src="/static/videos/samesurf-video-optimized.mp4" type="video/mp4">
	</video>
	<div id="slides">
		<div id="slide1" class="slide">
			<div class="headers">
				<h1>
					WEB SHARING <strong>REIMAGINED</strong>
				</h1>
				<h2>
					CRYSTAL CLEAR CO-BROWSING WITHOUT<br/> INSTALLS, HASSLES OR CODING.
				</h2>
				<div class="buttons">
					<a href="#" class="header-btn-blue">START DEMO</a>
					<a href="#" class="header-btn-blue modal" id="Homepage_video">WATCH VIDEO</a>
				</div>
			</div>
		</div>
		<div id="slide2" class="slide">
			<div class="headers">
				<h1>
					PERFECT THE ART OF<br/> <strong>SUPPORT AND SALES</strong>
				</h1>
				<div class="buttons">
					<a href="#" class="header-btn-blue">START DEMO</a>
					<a href="#" class="header-btn-blue modal" id="Homepage_video">WATCH VIDEO</a>
				</div>
			</div>
		</div>
		<div id="slide3" class="slide">
			<div class="headers">
				<h1>
					DELIVER CRYSTAL CLEAR<br/> <strong>PRESENTATIONS</strong>
				</h1>
				<div class="buttons">
					<a href="#" class="header-btn-blue">START DEMO</a>
					<a href="#" class="header-btn-blue modal" id="Homepage_video">WATCH VIDEO</a>
				</div>
			</div>
		</div>
		<div id="slide4" class="slide">
			<div class="headers">
				<h1>
					BROWSE THE WEB<br/> <strong>TOGETHER</strong>
				</h1>
				<div class="buttons">
					<a href="#" class="header-btn-blue">START DEMO</a>
					<a href="#" class="header-btn-blue modal" id="Homepage_video">WATCH VIDEO</a>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="banner_button_bar">
	<div id="banner_buttons">
		<div class="off_button">
			<div id="banner_button1"></div>
		</div>
		<div class="off_button">
			<div id="banner_button2"></div>
		</div>
		<div class="off_button">
			<div id="banner_button3"></div>
		</div>
		<div class="off_button">
			<div id="banner_button4"></div>
		</div>
	</div>
</div>
<div id="next_generation_box_container">
	<div id="next_generation_box">
		<div id="next_gen_text">
			<div class="heading">
				BROWSE THE WEB TOGETHER
			</div>
			<div class="homepagetext">
				<div class="alltext">
					Samesurf is a <a href="/pages/technology">patented</a>, install-free technology that </br>
					empowers multiple people to experience the same </br>
					content in real-time from any device or browser. 
				</div>
			</div>
			<a href="#">
				<div class="start_now_button">
					<div class="start_now_text">
						START DEMO
					</div>
				</div>
			</a>
		</div>
	</div>
</div>
<div id="key_uses_box_container">
	<div id="key_uses_box">
		<div id="key_uses_text">
			PRIMARY USES
		</div>
		<div id="circles_div">
			<a href="/pages/support">
				<div class="key_uses_circles circle_1">
					<div id="headphones_circle">
					</div>
				</div>
			</a>
			<a href="/pages/collaboration">
				<div class="key_uses_circles circle_2">
					<div id="hand_shake">
					</div>
				</div>
			</a>
			<a href="/pages/sales">
				<div class="key_uses_circles circle_3">
					<div id="high_five">
					</div>
				</div>
			</a>
			<a href="/pages/corptraining">
				<div class="key_uses_circles circle_4">
					<div id="whiteboard">
					</div>
				</div>
			</a>
			<a href="/pages/shop">
				<div class="key_uses_circles circle_5">
					<div id="trolley">
					</div>
				</div>
			</a>
			<a href="/pages/presentations">
				<div class="key_uses_circles circle_6">
					<div id="blackboard">
					</div>
				</div>
			</a>
			<a href="/pages/meetings">
				<div class="key_uses_circles circle_7">
					<div id="three_heads">
					</div>
				</div>
			</a>
			<a href="/pages/education">
				<div class="key_uses_circles circle_8">
					<div id="mortar_board">
					</div>
				</div>
			</a>
		</div>
	</div>
</div>

<div id="patent" class="block light">
	<div class="container">
		<div class="heading">
			BEST IN CLASS CO-BROWSING
		</div>
		<div class="content-wrap">
			<div class="left">
				<img class="c-right" src="/static/images/pages/nonpatentedtech.png" alt="Non-Patented Technology" />
				<div class="caption">
					<div class="title">
						ALTERNATIVES
					</div>
					Non-Patented Technology
				</div>
			</div>
			<div class="right">
				<img class="c-left" style="padding:41px 0 0;" src="/static/images/pages/patentedtech.png" alt="Patented Technology (May 2010)" />
				<div class="caption">
					<div class="title">
						<img src="/static/images/pages/bic-samesurflogo.png" alt="Image" />
					</div>
					Patented Technology
				</div>
			</div>
		</div>
	</div>
</div>

<div id="assisted-sales" class="block dark">
	<div class="container">
		<iframe src="//player.vimeo.com/video/77007215?title=0&amp;byline=0&amp;portrait=0" width="915" height="516" allowfullscreen></iframe>
	</div>
</div>

<div id="features_container">
	<div class="centredcontent">
		<div id="features_heading">
			<div class="mediumheader">FEATURES</div>
		</div>
		<div id="grid">
			<a href="/pages/features#content1" class="iconsq01">
				<div id="icon01"></div>
			</a>

			<a href="/pages/features#content2" class="iconsq02">
				<div id="icon02"></div>
			</a>

			<a href="/pages/features#content3" class="iconsq03">
				<div id="icon03"></div>
			</a>

			<a href="/pages/features#content4" class="iconsq04">
				<div id="icon04"></div>
			</a>

			<a href="/pages/features#content5" class="iconsq05">
				<div id="icon05"></div>
			</a>

			<a href="/pages/features#content6" class="iconsq06">
				<div id="icon06"></div>
			</a>

			<a href="/pages/features#content7" class="iconsq07">
				<div id="icon07"></div>
			</a>

			<a href="/pages/features#content8" class="iconsq08">
				<div id="icon08"></div>
			</a>

			<a href="/pages/features#content12" class="iconsq09">
				<div id="icon09"></div>
			</a>

			<a href="/pages/features#content10" class="iconsq10">
				<div id="icon10"></div>
			</a>
		</div>

	</div>
</div>

<div id="we_are_different_container">
	<div id="we_are_different_heading" class="heading">
		BUILT FOR THE MODERN WEB
	</div>
	<div id="text_headings">
		<div id="list_container_container">
			<div id="list_container">
				<div class="heading">
					<div id="heading1" class="we_are_different_inline">
						screen sharing
					</div>
					<div id="heading3" class="we_are_different_inline">
						vs.
					</div>
					<div id="heading2" class="we_are_different_inline">
						samesurf
					</div>
				</div>
				<div class="div_table">
					<div class="table_row">
						<div class="table_cell">
							SLOW
						</div>
						<div class="table_cell2">
							<div class="table_circles">
								<div class="circle1">
								</div>
								<div class="circle2">
								</div>
								<div class="circle3">
								</div>
							</div>
						</div>
						<div class="table_cell3">
							LIGHTNING FAST
						</div>
					</div>
					<div class="table_row">
						<div class="table_cell">
							FUZZY SCREENS
						</div>
						<div class="table_cell2">
							<div class="table_circles">
								<div class="circle1">
								</div>
								<div class="circle2">
								</div>
								<div class="circle3">
								</div>
							</div>
						</div>
						<div class="table_cell3">
							CRYSTAL CLEAR
						</div>
					</div>
					<div class="table_row">
						<div class="table_cell">
							INSTALLS
						</div>
						<div class="table_cell2">
							<div class="table_circles">
								<div class="circle1">
								</div>
								<div class="circle2">
								</div>
								<div class="circle3">
								</div>
							</div>
						</div>
						<div class="table_cell3">
							NO INSTALLS
						</div>
					</div>
					<div class="table_row">
						<div class="table_cell">
							PASSIVE VIEWING
						</div>
						<div class="table_cell2">
							<div class="table_circles">
								<div class="circle1">
								</div>
								<div class="circle2">
								</div>
								<div class="circle3">
								</div>
							</div>
						</div>
						<div class="table_cell3">
							FULLY INTERACTIVE
						</div>
					</div>
					<div class="table_row">
						<div class="table_cell">
							DESKTOP ONLY
						</div>
						<div class="table_cell2">
							<div class="table_circles">
								<div class="circle1">
								</div>
								<div class="circle2">
								</div>
								<div class="circle3">
								</div>
							</div>
						</div>
						<div class="table_cell3">
							CROSS PLATFORM
						</div>
					</div>
					<div class="table_row">
						<div class="table_cell">
							TAKE OVER COMPUTERS
						</div>
						<div class="table_cell2">
							<div class="table_circles">
								<div class="circle1">
								</div>
								<div class="circle2">
								</div>
								<div class="circle3">
								</div>
							</div>
						</div>
						<div class="table_cell3">
							NON-INVASIVE
						</div>
					</div>
					<div class="table_row">
						<div class="table_cell">
							EXPOSE PRIVATE DATA
						</div>
						<div class="table_cell2">
							<div class="table_circles">
								<div class="table_circles">
									<div class="circle1">
									</div>
									<div class="circle2">
									</div>
									<div class="circle3">
									</div>
								</div>
							</div>
						</div>
						<div class="table_cell3">
							ENTERPRISE SECURITY
						</div>
					</div>
					<div class="table_row">
						<div class="table_cell">
							RESOURCE INTENSIVE
						</div>
						<div class="table_cell2">
							<div class="table_circles">
								<div class="circle1">
								</div>
								<div class="circle2">
								</div>
								<div class="circle3">
								</div>
							</div>
						</div>
						<div class="table_cell3">
							RESOURCE EFFICIENT
						</div>
					</div>
					<div class="table_row">
						<div class="table_cell">
							CHOPPY VIDEOS
						</div>
						<div class="table_cell2">
							<div class="table_circles">
								<div class="circle1">
								</div>
								<div class="circle2">
								</div>
								<div class="circle3">
								</div>
							</div>
						</div>
						<div class="table_cell3">
							SEAMLESS VIDEOS
						</div>
					</div>
					<div class="table_row">
						<div class="table_cell">
							LIMITED USERS
						</div>
						<div class="table_cell2">
							<div class="table_circles">
								<div class="circle1">
								</div>
								<div class="circle2">
								</div>
								<div class="circle3">
								</div>
							</div>
						</div>
						<div class="table_cell3">
							UNLIMITED USERS
						</div>
					</div>
					<div class="table_row">
						<div class="table_cell">
							NON-ACCESSIBLE
						</div>
						<div class="table_cell2">
							<div class="table_circles">
								<div class="circle1">
								</div>
								<div class="circle2">
								</div>
								<div class="circle3">
								</div>
							</div>
						</div>
						<div class="table_cell3">
							FULLY ACCESSIBLE
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div id="customization_box_container">
	<div id="customization_box">
		<div id=text_box>
			<div id="customization_heading" class="heading">
				CUSTOMIZATION
			</div>
			<div id="customization_text" class="paragraph">
				<div class="alltext">
					Customize the design and features of each experience to suit 
					<br/>your specific requirements and uses. <a href="/pages/customization"> Explore Your Options</a>
				</div>
			</div>
			<div id="logos">
				<div class="wrap">
					<div class="logo selectedlogo border-right samesurf">
						<div id="samesurf_logo">
						</div>
					</div>
					<div class="logo sapient">
						<div id="sapient_logo">
						</div>
					</div>
				</div>
			</div>

			<div id="pagecontainer">
				<div id="sapientpage">
				</div>
				<div id="samesurfpage">
				</div>
			</div>
		</div>
	</div>
</div>
