<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/iewindl.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/iewindl.js");
?>
	<div id="content0">
		<div class="centredcontent">
			<div id="downloadtitle">
				<div id="logo"></div>
				<div id=content0title><div class="mediumheader">INTERNET EXPLORER DOWNLOAD INSTRUCTIONS</div></div>
			</div>			
		</div>	
	</div>	
	
	<div id="content1">
		<div class="centredcontent">
				
	
			<div class="content"><div class="alltext">After downloading, copy and paste this link into the address line within samesurf to join:<br/>
			<a href="http://i.samesurf.com/79012">http://i.samesurf.com/79012</a><br/><br/>
			Or just enter <a href="http://i.samesurf.com/79012">79012</a> after clicking the samesurf button.
			</div></div>
		</div>
	</div>

	<div id="content2">
		<div class="centredcontent">
			<div class="instructiongroup">
				<div id="circle1">1</div>
				<div id="text1"><div class="alltext">After starting the process, you'll get a prompt at the bottom of your browser. Please select 
				"Run" to continue.</div></div>
			</div>
			<div id="image1"></div>
		
			<div class="instructiongroup">
				<div id="circle2">2</div>
				<div id="text2"><div class="alltext">A wizard will pop up to guide you through the installation process. Click "Next" to continue.</div></div>
			<div id="image1a"></div>	
			</div>
			
			<div class="instructiongroup">
				<div id="circle3">3</div>
				<div id="text3"><div class="alltext">samesurf's Terms and Conditions will appear. Please read them carefully and if everything is 
				in order, select "I accept the agreement" and click "Next" to move forward.</div></div>
			<div id="image2"></div>
			</div>
			
			<div class="instructiongroup">
				<div id="circle4">4</div>
				<div id="text4"><div class="alltext">The following screens will ask you about your install location, Start Menu folder and whether 
				you want a shortcut for samesurf on your desktop. If you're happy with the defaults, click 
				"Next" to proceed through each of these prompts.</div></div>
			<div id="image3"></div>
			<div id="image3a"></div>
			<div id="image3b"></div>
			</div>
			
			<div class="instructiongroup">
				<div id="circle5">5</div>
				<div id="text5"><div class="alltext">Click "Install" to finish the process on your Windows computer.</div></div>
			<div id="image4"></div>
			</div>
			
			<div class="instructiongroup">
				<div id="circle6">6</div>
				<div id="text6"><div class="alltext">The installation will automatically begin.</div></div>
			<div id="image5"></div>
			</div>
			
			<div class="instructiongroup">
				<div id="circle7">7</div>
				<div id="text7"><div class="alltext">Click "Finish" to end the process and start samesurf. You'll only have to do this once...we promise!</div></div>
			<div id="image6"></div>	
			</div>
			
					
				
		
		</div>	
	</div>
		
	
