<?php
$this->setTitle("samesurf");
$this->addCSSFile("/static/css/pages/integration.css");
$this->addCSSFile("/static/css/pages/general.css");
$this->addJSFile("/static/js/pages/integration.js");
$this->addJSFile("/static/js/pages/lazyload.js");
$this->addJSFile("/static/js/pages/animate.js");
$this->addCSSFile("/static/css/pages/lazyload.css");
$this->addCSSFile("/static/css/pages/animate.css");
?>
<div id="content0">
	<div class="centredcontent">

		<div id=content0title><div class="mediumheader">INTEGRATION</div></div>
		<a href="#" id="topdlbutton" class="enablesite">DEMO SAMESURF</a>				
	</div>	
</div>	

<div id="content1">
	<div class="centredcontent">
		<div class="content1text"><div class="alltext">
			Integrating Samesurf on websites or apps <br/>
			requires one line of code, some checkbox <br/>
			entries and a few minutes of set-up time. <br/>
			<a href="/pages/howitworks"><div class="bluebutton">Take the Tour</div></a>
			</div>
		</div>
		<div id="content1image"></div>
	</div>
</div>

<div id="content2">
	<div class="centredcontent">
		<div id="content2title"><div class="mediumheader">WHY INTEGRATE SAMESURF?</div></div>
		<div id="grid">
			<div class="bulletbox">
				<div class="bulletptblue"></div>
				A single line of javascript completes integration
			</div>

			<div class="bulletbox2">
				<div class="bulletptgreen"></div>
				No reliance on third party software or hardware
			</div>

			<div class="bulletbox">
				<div class="bulletptred"></div>
				Ability to limit co-browsing to designated sites
			</div>

			<div class="bulletbox2">
				<div class="bulletptred"></div>
				Simple set-up process through self-service portal
			</div>

			<div class="bulletbox">
				<div class="bulletptgreen"></div>
				Seamless integration into existing software tools
			</div>

			<div class="bulletbox2">
				<div class="bulletptblue"></div>
				No coding supports continual site modifications
			</div>
		</div>

	</div>
</div>


<div id="content3">
	<div class="centredcontent">
		<div id="content3image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/nocoding.png" /></div>
		<div id="content3title"><div class="mediumheader">NO CODING REQUIRED</div></div>

		<div class="content3text"><div class="alltext">Samesurf integrates seamlessly onto any<br/>
			application or website without requiring complex
			coding or site modifications.</div></div>
	</div>
</div>	

<div id="content4">
	<div class="centredcontent">
		<div id="content4title"><div class="mediumheader">THIRD PARTY INTEGRATION</div></div>

		<div class="content4text"><div class="alltext">Our offerings integrate seamlessly within other applications<br/>
			and existing solutions for Phone Support and Live Chat.</div></div>
		<div id="content4image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/systeminteg.png" /></div>

		<div class="content4text2"><div class="alltext">Learn more about <a href="/pages/phonesupport">Phone Support</a> and <a href="/pages/livechat">Live Chat</a>.</div></div>	
	</div>
</div>	

<div id="content5">
	<div class="centredcontent">
		<div id="content5image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/standalone.png" /></div>
		<div id="content5title"><div class="mediumheader">STAND ALONE INTEGRATION</div></div>

		<div class="content5text"><div class="alltext">Samesurf complements existing products like<br/>Live Chat 
while doubling as an independent<br/>platform with no 
reliance on other software.</div></div>
	</div>
</div>