<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/jobs.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/jobs.js");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>
	<div id="titlebar">
		<div class="centredcontent">
			<div id="titlebartable">
				<div id="logo"></div>
					<div id="titlebartitle"><div class="mediumheader">JOBS</div></div>
			</div>
		</div>	
	</div>		
				
	<div id="content1">
		<div class="centredcontent2">
			
			<div class="title">
				<div class="mediumheader">
					OPEN POSITIONS
				</div>
			</div>
			
				<div class="contentbox">
						<div class="contentboxtitle">
							Senior VP of Business Development
						</div>
					
						<div class="downarrow"></div>
						<div class="contentboxtext"><div class="alltext">
						Samesurf/Actual Worlds, Inc. ("Company") is seeking a VP of Business Development to identify, 
						evaluate, structure and help implement business growth opportunities for the Company. This role 
						will be responsible for identifying new opportunities and partnerships as a means to grow revenue 
						on the Company's core businesses across e-commerce, web, mobile, apps, gaming, social media and 
						connected devices through licensing, revenue share deals, advertising, subscription, micropayments 
						or alternative methods of monetization.<br/><br/>

						The VP should be exceptionally personable and should have the mindset of a digital entrepreneur - 
						a person with experience growing digital businesses as well as someone who thrives on seeking ways 
						to monetize existing activities, expand revenue streams and forge new models that embody samesurf's 
						core vision.<br/><br/>

						As a senior team member, this role will help make the strategic plan on how to grow the business as 
						well as be out in the marketplace identifying and making deals for potential product, partner and 
						licensing opportunities leading to and including, in some cases, implementation.<br/><br/>

						The ideal candidate is a collaborator who is both strategic and detail-oriented, with business 
						development experience and a proven track record of growing a start up company in the online space. 
						The person should be comfortable working with executives at other companies and with internal management 
						teams. The ideal candidate should also be very familiar with the latest innovations and upcoming trends 
						in the e-commerce, content and ancillary arenas. They should have strong analytic and presentation skills.<br/><br/> 

						<div class="contentboxsubt">RESPONSIBILITIES:</div>
						Be at the forefront of industry knowledge in terms of the latest products and innovations and how 
						they can integrate samesurf into those experiences. Work with the Company's management on the digital 
						strategy growth plan and roadmap across all platforms. Identify, conceive, execute and model revenue 
						producing business opportunities, including new products, partnerships and licensing. Manage the 
						relationship with outside partners from identification to final deal to implementation when needed, 
						working with legal and the digital management team, including business analysis and metrics for success 
						and monetization models. Reports to the Company's Chief Executive Officer. <br/><br/>

						<div class="contentboxsubt">QUALIFICATIONS:</div>
						Bachelor degree, MBA preferred
						Strong track record in strategy and business development
						Integrated Web Technologies background preferred
						Strong network of e-commerce, content and digital media contacts
						Ability to make presentation and manage various tasks in parallel.

						<div class="contentboxsubt">COMPENSATION:</div>
						Competitive salary and participation in the company's stock option plan.
						
						
						<div class="submitbutton">SEND RESUME</div>
						
						</div></div>
						
				</div>
				
				<div class="contentbox">
						<div class="contentboxtitle">
							Front End Web Developer
						</div>
					
						<div class="downarrow"></div>
						<div class="contentboxtext"><div class="alltext">
						Samesurf is a fast, free and delightfully simple way to instantly experience the web together with friends, 
						family and colleagues. It's a lightning fast browser, public rooms site and website platform that transcends 
						screen sharing by giving life to a crystal clear new way to share your browsing experiences in real-time.
							
							<div class="submitbutton">SEND RESUME</div>
							
							
						</div></div>
						
				</div>
				
				<div class="contentbox">
						<div class="contentboxtitle">
							Account Executive
						</div>
					
						<div class="downarrow"></div>
						<div class="contentboxtext"><div class="alltext">
						Samesurf is a fast, free and delightfully simple way to instantly experience the web together with friends, 
						family and colleagues. It's a lightning fast browser, public rooms site and website platform that transcends 
						screen sharing by giving life to a crystal clear new way to share your browsing experiences in real-time.
							
							<div class="submitbutton">SEND RESUME</div>
							
						</div></div>
						
				</div>
				
				<div class="contentbox">
						<div class="contentboxtitle">
							Video Editor
						</div>
					
						<div class="downarrow"></div>
						<div class="contentboxtext"><div class="alltext">
						Samesurf is a fast, free and delightfully simple way to instantly experience the web together with friends, 
						family and colleagues. It's a lightning fast browser, public rooms site and website platform that transcends 
						screen sharing by giving life to a crystal clear new way to share your browsing experiences in real-time. 
							
							<div class="submitbutton">SEND RESUME</div>
							
						</div></div>
						
				</div>
				
				<div class="contentbox">
						<div class="contentboxtitle">
							Account Executive
						</div>
					
						<div class="downarrow"></div>
						<div class="contentboxtext"><div class="alltext">
						Samesurf is a fast, free and delightfully simple way to instantly experience the web together with friends, 
						family and colleagues. It's a lightning fast browser, public rooms site and website platform that transcends 
						screen sharing by giving life to a crystal clear new way to share your browsing experiences in real-time.
							
							<div class="submitbutton">SEND RESUME</div>
							
						</div></div>
						
				</div>
				
				<div class="contentbox">
						<div class="contentboxtitle">
							Video Editor
						</div>
					
						<div class="downarrow"></div>
						<div class="contentboxtext"><div class="alltext">
						Samesurf is a fast, free and delightfully simple way to instantly experience the web together with friends, 
						family and colleagues. It's a lightning fast browser, public rooms site and website platform that transcends 
						screen sharing by giving life to a crystal clear new way to share your browsing experiences in real-time.
							
							<div class="submitbutton">SEND RESUME</div>
							
						</div></div>
						
				</div>
				
				
		
			
		
		</div>	
		
	</div>	
