<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/landing.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/landing.js");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>
<div class="landing">
	<div class="container">
		<img class="logo" src="/static/images/pages/logo.png" alt="Samesurf, Browse The Web Together" />
		<div class="logo-2-container">
			<img class="logo-2" src="/static/images/pages/samesurf-landing-2.png" alt="Samesurf, Browse The Web Together" />
		</div>
		<form id="samesurf-start">
			<div class="info">
				Enter any Web Address to Start
			</div>
			<div class="input-area">
				<input type="text" name="samesurf-start-url" placeholder="http://" />
				<input type="submit" value="" />
			</div>
		</form>
	</div>
	<div class="bottom-nav">
		<div class="wrap">
			<p>
				No Installs, Hassles or Coding.
			</p>
			<ul>
				<li><a href="/pages/features#content1" class="cobrowse"><span>Co-Browsing</span></a></li>
				<li><a href="/pages/features#content4" class="videochat"><span>Video Chat</span></a></li>
				<li><a href="/pages/features#content6" class="screensharing"><span>Screen Sharing</span></a></li>
				<li><a href="/pages/features#content11" class="livechat"><span>Live Chat</span></a></li>
				<li><a href="/pages/watchvideos" class="watchtogether"><span>Co-Watching</span></a></li>
			</ul>
			<br />
			<ul>
				<li><a href="#"  class="header-btn-blue modal watchvideo" id="Homepage_video">Watch Video</a></li>
				<li><a href="/">Learn More</a></li>
			</ul>
			<div class="pre-load">
				<img src="/static/images/pages/cobrowse-icon-hover.png" alt="Preload" />
				<img src="/static/images/pages/video-chat-icon-hover.png" alt="Preload" />
				<img src="/static/images/pages/ss-icon-hover.png" alt="Preload" />
				<img src="/static/images/pages/live-chat-icon-hover.png" alt="Preload" />
				<img src="/static/images/pages/watch-together-icon-hover.png" alt="Preload" />
			</div>
		</div>
	</div>
</div>