<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/legal.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/legal.js");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>
	<div id="titlebar">
		<div class="centredcontent">
			<div id="titleinfobox">
				<div id="titletext"><div class="mediumheader">POLICIES</div></div>
					<div class="infobox">
						<div class="infoboxtext"><a href="#1">1. ACCEPTANCE OF THE TERMS</a><br>
												 <a href="#2">2. PRIVACY INFORMATION</a><br>
												 <a href="#3">3. SAMESURF UPDATES AND UPGRADES</a><br>
												 <a href="#4">4. LICENSE AND RESTRICTIONS</a><br>
												 <a href="#5">5. UPDATES AND MAINTENANCE</a><br>
												 <a href="#6">6. CONTENT DISCLOSURE</a><br>
												 <a href="#7">7. QUALITY</a>
						</div>
					</div>
					<div class="infobox">
						<div class="infoboxtext"><a href="#8">8. GOVERNMENT END USERS</a><br>
												 <a href="#9">9. TERMINATION</a><br>
												 <a href="#10">10. DISCLAIMERS OF WARRANTY & LIABILITY</a><br>
												 <a href="#11">11. YOUR RESPONSIBILITY</a><br>
												 <a href="#12">12. PROPRIETARY INTERESTS</a><br>
												 <a href="#13">13. PRICING AND CHARGES</a><br>
												 <a href="#14">14. 3RD PARTY PRODUCTS AND SERVICES</a>
						</div>
					</div>
					<div class="infobox">
						<div class="infoboxtext"><a href="#15">15. TERMINATION</a><br>
												 <a href="#16">16. HOW TO CONTACT SAMESURF</a><br>
												 <a href="#17">17.MISCELLANEOUS</a><br>
												 <a href="#18">18. DISPUTES</a><br>
												 <a href="#19">19. CHANGE OF TERMS</a><br>
												 <a href="#20">20. DATA RETENTION POLICY</a>
						</div>
					</div>
			</div>	
				
		</div>	
	</div>	
	
	<div id="content1">	
		<div class="centredcontent">
			<div class="content1text">
				Please read these Terms & Conditions and the samesurf Privacy Policy (collectively, the &ldquo;Agreement&rdquo;) before using the samesurf 
				software and related services (&ldquo;samesurf&rdquo;).  By installing, using or accessing samesurf (1) as a desktop or mobile browser 
				application; (2) as an embedded technology on a partnered website; (3) on samesurf.com, screensharenow.com or other company 
				owned websites; or (4) via other formats, whether made available to you for free or for a fee (&ldquo;the Software&rdquo;), you accept and 
				agree to be bound by this Agreement.  If you don't want to be bound by the Agreement, please terminate your use of the samesurf 
				Software and do not install, use or access samesurf.  For purposes of this Agreement, the term &ldquo;samesurf&rdquo; also refers to its parent 
				corporation: Actual Worlds, Inc., a Delaware corporation (&ldquo;AW&rdquo;).<br><br>
				

				samesurf's products and services, associated documents (whether in printed or electronic form) and any improvements, 
				modifications, enhancements, fixes, updates, upgrades and future versions thereto (&ldquo;Updates&rdquo;) are being licensed (not sold) to you 
				by samesurf/Acutal Worlds, Inc.   For purposes of the Agreement, &ldquo;samesurf&rdquo; and AW includes its subsidiary companies and 
				affiliated legal entities and all their directors, officers, agents, licensors and employees.<br><br>
					
			<div class="content1title"><a id="1"><div class="mediumheader">
			
				1. ACCEPTANCE OF THE TERMS
			 
			</div></a></div>
			
				In order to download and/or use the Software, products and/or samesurf websites, you must first accept these terms. These terms 
				are accepted by you (a) when you click to accept or agree the terms; or (b) when you download and/or use the Software and/or 
				samesurf websites. We advise you to print a copy of these terms for your records. These terms remain effective from the date of 
				acceptance until terminated by you or samesurf.   You cannot accept these terms if: (a) you are not lawfully entitled to use the 
				Software, products and/or samesurf websites in the country in which you are located or resident or (b) if you are not of legal age 
				to form a binding agreement with samesurf.<br><br>
						
			<div class="content1title"><a id="2"><div class="mediumheader">
				2. PRIVACY INFORMATION
			</div></a></div>
			
				Please note that personally identifiable information collected through samesurf is subject to the samesurf Privacy Notice (set forth 
				below), which is incorporated and made as part of this Agreement.   It is important to also note that you do not need to register or 
				provide any personally identifying information in order to download and/or use samesurf.  When you download, use or access 
				samesurf by contacting our servers, samesurf receives only standard log information including your machine's IP address and one 
				or more cookies.  Sites that you visit using samesurf will automatically receive standard log information similar to that received by 
				samesurf.com. These sites may also set their own cookies or use web storage on your machine.  Please keep in mind that we do not 
				have control over the websites or the privacy practices of the sites you're visiting. Please carefully consider any website's privacy 
				practices before visiting that site.  You are solely responsible for the online content you visit and/or follow others on with samesurf.<br><br>
				
				samesurf enables multiple users to browse (and/or screen share) websites and other content together in real-time.  It also 
				incorporates complementary components that further enhance these shared experiences.  These components include, but are not 
				limited to, tracking cursor movements, sharing screen drawings, text chat, audio & video chat, social chat via integration with other 
				social networking and chat services such as Facebook and Google Talk, single link invites, screen sharing and the transmission of 
				&ldquo;tweets,&rdquo; &ldquo;wall posts,&rdquo; and other messages through a bevy of social networking services. In order to effectuate these shared 
				experiences, samesurf's servers act as a pass through mechanism that coordinates most activities that take place within samesurf 
				sessions; these servers receive and transmit information such as URLs, cookies and form data (&ldquo;Coordination Information&rdquo;) in order 
				to enable multiple users to browse content together.  Therefore, like most browsers, applications and similar services that enable 
				you to access the Web, the Coordination Information regarding the pages you visit using samesurf pass through our servers.<br><br>
				
				With certain exceptions that exist for samesurf partnered educational institutions where we generally retain personally identifiable 
				data for a shorter period of time (see section marked &ldquo;Data Retention Policy&rdquo;), samesurf generally logs web addresses -- known as 
				uniform resource locators (&ldquo;URLs&rdquo;) -- for the web pages and online content that our users access via samesurf and certain 
				identifiers, such as IP or MAC addresses.  These forms of data are retained for the purpose of troubleshooting and diagnosing 
				technical issues and for transmitting personalized and relevant advertisements or opportunities to our users.<br><br>
				
				In coming versions of the samesurf downloadable applications for desktop and mobile devices (&ldquo;the Downloadable Applications&rdquo;), 
				all text you enter in samesurf's address bar will be sent to a default search engine. The initial default search engine is selected by 
				samesurf, and we may change the default search engine in the future without notice to you. The privacy policy of the selected 
				default search engine applies to information sent to it. As an opt-in option, samesurf also enables you to import 
				apps/browser/extension information such as your bookmark data from other services like Google.<br><br>
				
				If you enable samesurf's Account Sharing feature that allows you to share websites that require logins, it is important to note that 
				you should only share content using these mechanisms with followers you trust and know well.  Accordingly, you hereby 
				acknowledge that in utilizing the Account Sharing feature, you are giving others who are following you in the same room access to 
				your sensitive account information and you are hereby accepting all responsibility and liability for your decision to share 
				authenticated sites or sites that require logins. You are also fully aware that in utilizing the Account Sharing feature and in not 
				taking adequate precautions in this regard, you may enable your followers to perform tasks that may lead to embarrassment, 
				pecuniary loss or other harmful consequences. These consequences include, but are certainly not limited to, the following: (1) 
				Having followers buy items in your account; (2) Having followers post in your account; (3) Having followers view sensitive data 
				such as your credit card or password information in your account; (4) Having followers download documents from within your 
				accounts; and (5) other similar consequences. By using this product, you hereby acknowledge that Samesurf is not responsible for 
				any loss, harm or other negative consequence that you or others may suffer while using the Account Sharing to share sites that 
				require logins (authenticated sites). Furthermore, you hereby acknowledge that you will utilize the Account Sharing feature in full 
				compliance with all applicable laws and that you will not violate the terms of service and/or privacy policies of the sites you are 
				sharing via the Account Sharing function.<br><br>
				
				In utilizing samesurf for either co-browsing (&ldquo;samesurfing&rdquo;) or screen sharing, you hereby acknowledge that you may be 
				transmitting, distributing or broadcasting either visual or written information to your followers who may be joining you in a 
				samesurf or screen sharing session as well as any other individual or entity who is, or may become aware, of said session, and is 
				able to observe, either physically, or through electronic means, said sessions. Accordingly, it's important that you invite only 
				followers you know well to a screen sharing session or to a samesurf session where Account Sharing is enabled.<br><br>
				
				<div class="content1title"><div class="mediumheader">
						TRANSMITTED AND RECEIVED MATERIAL
				</div></div>				
				
				You hereby agree that the transmissions, distributions, broadcasts, transfers or other exchange of material in violation of any local, 
				State, or Federal law or regulation using samesurf is strictly prohibited. The foregoing includes, without limitation, material 
				protected by copyright, trademark, trade secret, patent or other intellectual property right used without proper authorization and 
				material that is obscene, vulgar, defamatory, immoral, pornographic, pedophilic, or otherwise objectionable, constitutes an illegal 
				threat, or a threat to national security or violates any export control laws. Your further hereby agree to be solely responsible for all 
				content, either visual, written, or audible, that is transmitted, distributed, broadcasted or otherwise transferred through samesurf. 
				You agree that you will not utilize samesurf to harass, libel, threaten, offend, or violate the intellectual property rights of any party 
				or to otherwise criminally or civilly offend another under any applicable local, State, or Federal law.<br><br>
				
				You hereby agree that you will not utilize samesurf to send unsolicited e-mail messages or postings, including, without limitation, 
				bulk commercial advertising or informational announcements (otherwise known as &ldquo;spam&rdquo;). As such, you further agree that you 
				shall not use samesurf to (i) disguise your true Internet Protocol address or any other user; (ii) send e-mail messages or postings 
				which are excessive and/or intended to harass or annoy others; or (iii) continue to send e-mail messages or postings to a recipient 
				who has indicate that he or she does not wish to receive same. 
				
				<div class="content1title"><div class="mediumheader">
						INFORMATION STORED ON YOUR COMPUTER AND SITES YOU VISIT
				</div></div>
				
				samesurf records useful information about your browsing history on your own computer. This includes (1) Cookies or web storage data 
				deposited on your machine by websites you visit; and (2) a record of downloads you have made from websites.  On the browser application, 
				you can delete all or portions of this history at any time by either clearing your cache via the “Tools” button or clearing your downloads 
				via selection of the “Downloads” option under the “Tools” button.<br/><br/> 
				
				On certain instances and when you are in a samesurf session, samesurf may serve you and/or your followers (1) targeted and/or other forms of 
				advertising or (2) may utilize online monetization techniques that generate revenue for samesurf in formats that include, but are certainly 
				not limited to, the following: (a) banner ads; (b) text ads; (c) UI sponsorships; (d) URL redirects (with affiliate insertions); (e) integrated 
				search (CPC); (f) CPA ads; (g) video ads; (h) surveys; (i) affiliate marketing programs; and (j) other forms of monetization. In using samesurf, 
				you hereby agree that your only remedy in not participating, viewing or interacting with such advertising products is to simply cease your use of 
				our products. 
				
				<div class="content1title"><div class="mediumheader">
						INFORMATION RELATING TO USING APPLICATIONS, EXTENSIONS AND PLUGINS ON SAMESURF
				</div></div>

				If you install a plug-in on samesurf, any data processed by the plug-in will be handled in accordance with the policies of the developer of that plug-in.

				<div class="content1title"><a id="3"><div class="mediumheader">
						3. SAMESURF UPDATES AND UPGRADES
				</div></a></div>

				samesurf is offered by Actual Worlds, Inc., a Delaware corporation ("AW"). The terms of the Agreement govern the samesurf software in its various formats and 
				any updates or upgrades to the samesurf software that AW may provide that replace and/or supplement the original software, unless such update or upgrade is 
				accompanied by a separate license, in which case the terms of that license will govern. This Agreement also covers services related to the Software.

				<div class="content1title"><a id="4"><div class="mediumheader">
						4. LICENSE AND RESTRICTIONS
				</div></a></div>

				Subject to your compliance with the terms of the Agreement, AW grants you a non-exclusive, non-transferable, non-sublicensable, limited license to install and/or 
				use the Software in its various formats on your computer or device in accordance with the Agreement and any applicable law or regulation in the relevant jurisdictions 
				(including any laws regarding the export of data or software to and from the United States or other relevant countries). You may not make copies of or distribute the 
				Software or electronically transfer the Software from one device to another or over a network. Except and only to the extent expressly permitted under applicable law, 
				you may not, and may not encourage, assist, or authorize any other person to, modify, reverse engineer, decompile, or disassemble the Software, in whole or in part; 
				create any derivative work from or of the Software; or bypass, modify, defeat or tamper with or circumvent any of the functions or protections of the Software. Unless 
				AW has given you specific written permission to do so, you may not sublicense, assign, or otherwise transfer the Software or your rights to use the Software. All rights 
				not expressly granted in the Agreement are reserved by AW.  You may not and you agree not to remove, obscure or alter any copyright notices or other proprietary notices 
				included in the Software.  You may not and you agree also note to use the Software or cause the Software (or any part of it) to be used within or to provide commercial 
				products or services to third parties. One or more open source software licenses apply or may in the future apply to certain components of the Software and will govern 
				in the event of a conflict with this Agreement.<br/><br/> 

				The Software may use the processing capabilities, memory and bandwidth of the computer (or other applicable device) you are using for the limited purpose of facilitating 
				the communication and establishing the connection between samesurf users. If your use of the Software is dependent upon the use of a processor and bandwidth owned or 
				controlled by a third party, you acknowledge and agree that your license to use the Software is subject to you obtaining consent from the relevant third party for such use. 
				You represent and warrant that by accepting these Terms, you have obtained such consent.
				
				<div class="content1title"><a id="5"><div class="mediumheader">
						5. UPDATES AND MAINTENANCE
				</div></a></div>

				In order to keep samesurf up-to-date, AW may automatically update or upgrade the Software at any time and without notice to you. Further, AW may change, suspend, or 
				discontinue samesurf, or any part of samesurf without notice or liability. If AW elects to provide customer support of any kind, it may terminate that support at any 
				time without notice to you.<br/><br/> 

				From time to time, samesurf may need to perform maintenance on or upgrade the Software, products or samesurf websites or the underlying infrastructure that enables you 
				to use the Software, products or samesurf websites. This may require samesurf to temporarily suspend or limit your use of some or all of the Software, products or samesurf 
				websites until such time as this maintenance and/or upgrade can be completed. You will not be entitled to claim damages for such suspension or limitation of the use of any 
				Software, product or samesurf website.<br/><br/> 

				<div class="mediumheader2">Changes to Products</div> samesurf is constantly improving the Software and Products and may also need to change technical features from time to time in order to comply with 
				applicable regulations. Accordingly, you acknowledge and agree that the products and functionality of the Software may vary from time to time. If you do not agree with any 
				changes to the Software and the other products you may terminate your relationship with samesurf. You may need to upgrade to a new version in order to enjoy the benefit of 
				certain Products. In addition, you acknowledge and agree that certain products may be subject to usage limits or geographical restrictions, which may vary from time to time.
				
				<div class="content1title"><a id="6"><div class="mediumheader">
						6. CONTENT DISCLOSURE				
				</div></a></div>

				<div class="mediumheader2">Content of Communications</div> samesurf is not the source of, does not have any control over, does not monitor and takes no responsibility for the content of communications made 
				using the Software. By using the Software, you agree that any content that you submit may be transmitted to the recipient of your communication or others in the same "room." 
				The content of communications is entirely the responsibility of the person from whom such content originated.  You also agree and acknowledge that if you choose to log others 
				into any of your online accounts via the Account Sharing or Screen Sharing features of the Software, you may be giving those users access to your accounts with the corresponding 
				power to make changes, purchases, posts and other inputs on your account.  Accordingly, you should only use the Account Sharing or Screen Sharing features with users who you know 
				and trust to the highest degree.  In addition, you may also be exposed to content that is offensive, unlawful, harmful to minors, obscene, indecent or otherwise objectionable. 
				The content of your communications may be protected by intellectual property rights, which are owned by third parties. You are responsible for the content you choose to communicate, 
				share, share access to and visit using the Software. In particular, you are responsible for ensuring that you do not submit material or unlawfullly share content or access to accounts 
				(subscription based or otherwise) that are (i) copyrighted, protected by trade secret or otherwise subject to third party proprietary rights, including privacy and publicity rights, 
				unless you are the owner of such rights or have permission from their rightful owner (ii) a falsehood or misrepresentation (iii) offensive, unlawful, harmful to minors, obscene, 
				defamatory, libellous, threatening, pornographic, harassing, hateful, racially or ethnically offensive, or that encourages conduct that would be considered a criminal offense, gives 
				rise to civil liability, violates any law, or is otherwise objectionable; (iv) an advertisement or solicitation of business; or (v) impersonating another person. samesurf reserves 
				the right (but shall have no obligation) to decide whether any content that you use or practices that you perform comply with these Terms. samesurf may in its sole discretion remove 
				such content and/or terminate these Terms and your user account if you use any content that is in breach of these Terms.<br/><br/> 

				<div class="mediumheader2">Notice and Take-Down</div> If samesurf receives any notification that any material that you post, upload, edit, host, share and/or publish on the samesurf websites or through 
				the Software (excluding your private communications) ("User Submission") is inappropriate, infringes any rights of any third party, or if samesurf wishes to remove your User Submission 
				for any reason whatsoever, samesurf reserves the right to automatically remove such User Submission for any reason immediately or within such other timescales as may be decided from time 
				to time by samesurf in its sole discretion. The User Submission shall be taken down without any admission as to liability and without prejudice to any rights, remedies or defenses, all of 
				which are expressly reserved. You acknowledge and agree that samesurf is under no obligation to put back such User Submission at any time. Any false, misleading or inaccurate information 
				provided by you may result in civil and criminal liability.<br/><br/> 

				<div class="mediumheader2">Unsolicited Ideas</div> samesurf does not consider or accept unsolicited proposals or ideas, including without limitation ideas for new products, technologies, promotions, 
				product names, product feedback and product improvements ("Unsolicited Feedback"). If you send any Unsolicited Feedback to samesurf through the samesurf Website or otherwise, you 
				acknowledge and agree that samesurf shall not be under any obligation of confidentiality with respect to the Unsolicited Feedback.<br/><br/> 

				<div class="mediumheader2">Reports</div> Certain parts of the samesurf websites or the Software may ask for written suggestions or problem reports such as using our feedback form ("Reports"). The 
				Reports shall be deemed the property of samesurf. samesurf shall exclusively own all now known or hereafter existing rights to the Reports throughout the universe in perpetuity and 
				shall be entitled to use the Reports for any purpose whatsoever, commercial or otherwise, without compensation to the provider of the Reports. Any Reports you send to samesurf will 
				not be treated as confidential and samesurf shall not be liable for any disclosure of the Reports.<br/><br/> 

				<div class="mediumheader2">Linking</div> You may link to the samesurf websites from another website owned by you, provided you do so in a way that is fair and legal and does not damage our 
				reputation or take advantage of it. You must not establish a link in such a way as to suggest any form of association, approval or endorsement by samesurf where none exists. 
				samesurf may revoke the permission to link to the samesurf websites at any time at its sole discretion.<br/><br/> 

				To the extent that you use or connect to any third party instant messaging services, social networks (such as Facebook or Twitter) or other third-party applications through 
				samesurf, you agree to comply with all terms and conditions of use for those services.<br/><br/> 

				<div class="mediumheader2">User Content and Abuse</div>  samesurf allows users to communicate and share information with each other. samesurf does not verify the qualifications 
				or identity of users and does not evaluate or control exchanges between users. Any content transmitted or actions taken by a user are the sole responsibility of the user and are 
				not to be attributed to samesurf. samesurf cannot and does not assume responsibility for the accuracy, completeness, safety, reliability, or legality of anything posted to or sent 
				through samesurf by any user.<br/><br/> 

				<div class="mediumheader2">Third Party Services</div>  samesurf allows you to access third-party IM services, social networks and applications from the samesurf "Chat with Friends" 
				module. It also contains links to third-party websites and includes advertising for third-party products and services. samesurf is not responsible for, nor does it guarantee the 
				accuracy or integrity of, the content or services of any third-party website, service, product or application accessible through samesurf.<br/><br/> 

				Any interactions you have with these third parties are solely between you and such third party. samesurf is not responsible or liable for any loss or damage of any kind incurred as 
				the result of any dealings with third parties or as the result of the presence of links to such third party websites or services on samesurf.<br/><br/> 

				<div class="mediumheader2">Provisions Relating to Third Party Messaging Services</div>  samesurf users can use samesurf to log into and use their accounts with different third party 
				instant messaging services via the "Chat with Friends" module. Your use of any third party instant messaging service through samesurf is subject to the terms and conditions of 
				those services.<br/><br/> 

				<div class="mediumheader2">Interstate and International use</div>  Except for samesurf partnered educational institutions where data is generally captured for a shorter period of time, 
				you consent to the collection and processing of personal information in the United States. All users understand the potential cross-border nature of communications made using samesurf 
				and acknowledge that using the samesurf services may result in interstate and international transmission of data.<br/><br/> 

				<div class="mediumheader2">Special Provisions Relating to the Embedded Version of samesurf</div>  The samesurf embed version is an embeddable technology that is displayed as a button, 
				footer and/or sidebar on your browser window ("the Embed Version"). The UI (including the chat modules) for the embed version may cover a portion of the web page that you're viewing.  
				The Embed Version UI may conflict with other browser extensions or toolbars that are designed to occupy the same space in your browser window. By using the Embed Version, you consent 
				to these conflicts. It is important to note that you can always minimize the sidebar by clicking on the "Minimize Sidebar" button on the samesurf footer.

				<div class="content1title"><div class="mediumheader">
						NOTICE TO USERS OF SAMESURF PUBLIC ROOMS				
				</div></div>

				samesurf allows you to embed or link to samesurf Pubic Rooms in other sites by including links to the samesurf Public Room on that site. You understand that linking to or otherwise embedding 
				a samesurf Public Room in another site is subject to the policies of the receiving site and to the technical capabilities of your browser. samesurf reserves the right to restrict your access 
				to samesurf Public Rooms or terminate any embedded samesurf Public Room under any circumstances.<br/><br/> 

				samesurf reserves the right to terminate a samesurf Public Room, remove users from a samesurf Public Room and/or limit the number of embedded copies of a samesurf room in its sole discretion. 
				Users of samesurf Public Rooms may not create a link to a samesurf Public Room or otherwise embed or cause to display any instance of any samesurf Public Room on any website that contains, 
				propagates, or otherwise displays any adult, illegal or patently offensive content.<br/><br/> 

				You understand that no content appearing in any samesurf Public Room, except for "in-room chat" is hosted or served on the samesurf servers, and that, as a result, samesurf has no control over 
				the accessibility of content from third party servers, nor does it guarantee the accuracy, quality or integrity of content posted or displayed in any samesurf Public Room. It is hereby understood 
				that any brands, trademarks, or other intellectual property of any third party that is referenced in the name, content or other component of a public room is not the property of samesurf and that 
				the inclusion of such intellectual property implies nor is intended to imply an endorsement, involvement or other relationship by and between samesurf, the public room originator and/or the owner 
				of the subject intellectual property.

				<div class="content1title"><a id="7"><div class="mediumheader">
						7. QUALITY				
				</div></a></div>

				samesurf cannot guarantee that the Software, products or samesurf websites will always function without disruptions, delay or errors. A number of factors may impact the quality of your communications 
				and use of the Software, products or samesurf Websites, and may result in the failure of your communications.  These include, but are not limited to: your local network, firewall, internet service 
				provider, your browser and the public internet. samesurf takes no responsibility for any disruption, interruption or delay caused by any failure of or inadequacy in any of these items or any other 
				items over which we have no control.

				<div class="content1title"><a id="8"><div class="mediumheader">
						8. GOVERNMENT END USERS				
				</div></a></div>

				The Software is provided to the U.S. Government as a "commercial item," "commercial computer software," "commercial computer software documentation," and "technical data," as defined in the U.S. 
				Federal Acquisition Regulation and the U.S. Defense Federal Acquisition Regulation Supplement, with the same rights and restrictions customarily provided to end users.

				<div class="content1title"><a id="9"><div class="mediumheader">
						9. TERMINATION				
				</div></a></div>
				
				You may terminate the Agreement at any time by uninstalling the Software or ceasing your use of samesurf. In addition, your rights under the Agreement will automatically terminate without notice 
				from AW if you fail to comply with any term of the Agreement or if AW discontinues samesurf.  In case of any termination, you must cease all use of samesurf in its various formats, including the 
				Software. AW may also terminate your right to use samesurf at any time, and in such event may modify it to make it inoperable.

				<div class="content1title"><a id="10"><div class="mediumheader">
						10. DISCLAIMER OF WARRANTIES AND LIABILITY				
				</div></a></div>

				YOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT INSTALLATION, USE OF, OR ANY OTHER ACCESS TO SAMESURF IS AT YOUR SOLE RISK. SAMESURF IS DELIVERED TO YOU "AS IS" WITH ALL FAULTS AND WITHOUT WARRANTY OF 
				ANY KIND, AND AW AND ITS PARTNERS, AFFILIATES, LICENSORS, AND/OR LICENSEES DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION THE IMPLIED WARRANTIES OF MERCHANTABILITY, 
				FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, QUIET ENJOYMENT, AND NON-INFRINGEMENT.  IN PARTICULAR, AW AND ITS PARTNERS, AFFILIATES, LICENSORS, AND/OR LICENSEES DO NOT REPRESENT OR WARRANT TO YOU 
				THAT: (A) YOUR USE OF THE SERVICES WILL MEET YOUR REQUIREMENTS, (B) YOUR USE OF THE SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE, OR FREE FROM ERROR, (C) ANY INFORMATION OBTAINED BY YOU AS A 
				RESULT OF YOUR USE OF THE SERVICES WILL BE ACCURATE OR RELIABLE, AND (D) THAT DEFECTS IN THE OPERATION OR FUNCTIONALITY OF ANY SOFTWARE PROVIDED TO YOU AS PART OF THE SERVICES WILL BE CORRECTED.  
				ANY MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SERVICES IS DONE AT YOUR OWN DISCRETION AND RISK AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR 
				OTHER DEVICE OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH MATERIAL.<br/><br/> 

				<div class="mediumheader2">No Liability</div> YOU ACKNOWLEDGE AND AGREE THAT SAMESURF WILL HAVE NO LIABILITY WHATSOEVER, WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE) OR ANY OTHER THEORY OF 
				LIABILITY, AND WHETHER OR NOT THE POSSIBILITY OF SUCH DAMAGES OR LOSSES HAS BEEN NOTIFIED TO SAMESURF, IN CONNECTION WITH OR ARISING FROM YOUR USE OF SAMESURF WEBSITES, OR THE SOFTWARE. YOUR ONLY 
				RIGHT OR REMEDY WITH RESPECT TO ANY PROBLEMS OR DISSATISFACTION WITH SUCH SOFTWARE AND/OR SAMESURF WEBSITES IS TO IMMEDIATELY DEINSTALL SUCH SOFTWARE AND CEASE USE OF SUCH SOFTWARE AND/OR SAMESURF 
				WEBSITES.<br/><br/> 

				<div class="mediumheader2">Limitation of Liability</div>  TO THE EXTENT NOT PROHIBITED BY LAW, NEITHER AW NOR ITS PARTNERS, AFFILIATES, LICENSORS, AND/OR LICENSEES WILL BE LIABLE TO YOU FOR ANY 
				INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR BREACH OF ANY EXPRESS OR IMPLIED WARRANTY, BREACH OF CONTRACT, NEGLIGENCE, STRICT LIABILITY, OR ANY OTHER LEGAL THEORY RELATED TO SAMESURF, INCLUDING WITHOUT 
				LIMITATION ANY DAMAGES ARISING OUT OF LOSS OF PROFITS, REVENUE, DATA, OR USE OF SAMESURF, EVEN IF AW HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. IN ANY CASE, AW'S AGGREGATE LIABILITY UNDER 
				AGREEMENT WILL BE LIMITED TO THE AGGREGATE FEES YOU PAID AW FOR THE PRECEDING THREE MONTHS PRIOR TO THE ALLEGED AND ACTUAL PROVEN DAMAGES.

				<div class="content1title"><a id="11"><div class="mediumheader">
					11.  YOUR RESPONSIBILITY
				</div></a></div>	

				<div class="mediumheader2">User Account</div> Prior to your first use of the samesurf Software, you may be asked to create a User Account and choose a user ID and password. If you do choose to 
				register with samesurf, we recommend that you choose a password that is hard to guess and consists of letters, numbers and symbols. You are solely responsible and liable for all activities conducted 
				through your User Account, the Software, the samesurf websites or whether you use the software without registering for samesurf. To prevent unauthorized use, you shall keep your password confidential 
				and shall not share it with any third party or use it to access third party websites or services. If you suspect that someone else knows your password, then you shall immediately change it in order to 
				protect the security of your User Account. It is your responsibility to ensure that you do not respond to any unsolicited requests for credit card details, passwords or other data. samesurf takes no 
				responsibility for your failure to comply with the obligations in this paragraph 11.<br/><br/> 

				<div class="mediumheader2">Lawful Use</div> You must use the Software, products and samesurf websites in accordance with the laws of the jurisdiction in which you are located. In some countries, there 
				are restrictions on the download and use of the Software, products and/or samesurf websites. It is your responsibility to ensure that you are legally allowed to use the Software, products and/or samesurf 
				websites in the jurisdiction in which you are located.<br/><br/> 

				<div class="mediumheader2">Prohibited Use</div> You may not:<br/><br/> 

				(a) intercept or monitor, damage or modify any communication which is not intended for you;<br/><br/>  

				(b) use any type of spider, virus, worm, trojan-horse, time bomb or any other codes or instructions that are designed to distort, delete, damage, emulate or disassemble the Software, communication or 
				protocols;<br/><br/>  

				(c) send unsolicited communications (also referred to as 'SPAM' or 'SPIT') or any communication not permitted by applicable law or use the Software for the purposes of phishing or pharming or impersonating or 
				misrepresenting affiliation with another person or entity;<br/><br/>  

				(d) expose any third party to material which is offensive, harmful to minors, indecent or otherwise objectionable in any way;<br/><br/>  

				(e) use the Software or samesurf websites to cause or intend to cause embarrassment or distress to, or to threaten, harass or invade the privacy of, any third party;<br/><br/>  

				(f) use (including as part of your User ID and/or profile picture) any material or content that is subject to any third party proprietary rights, unless you have a license or permission from the owner of 
				such rights;<br/><br/>  

				(g) collect or harvest any personally identifiable information, including account names, from the samesurf Website;<br/><br/>  

				(h) impact or attempt to impact the availability of the Software for example, with a denial of service (DOS) or distributed denial of service (DDoS) attack;<br/><br/>  

				(i) use or launch any automated system, including without limitation, robots, spiders or offline readers that access the samesurf Website; or<br/><br/>  

				(j) use or misuse any user's account before, during or after a sharing session.<br/><br/>  

				<div class="mediumheader2">User Submissions</div> Please exercise respect when participating in any features of the samesurf websites or Software such as forums, samesurf Public Rooms, email functions, 
				video hosting, online sharing and/or publishing or any other function on the samesurf websites or of the samesurf Software which allows you to post, upload, edit, host, share and/or publish content. You 
				acknowledge and agree that: (i) by using the samesurf websites and/or Software you may be exposed to content that you may find offensive or indecent and you do so at your own risk; (ii) you are solely 
				responsible for, and samesurf has no responsibility to you or any third party for any User Submissions that you create, submit, post or publish on the samesurf websites or through the Software; (iii) samesurf 
				does not guarantee any confidentiality with respect to User Submissions, whether or not they are published (iv) samesurf is not responsible for any User Submissions that you may have access to through your use 
				of the samesurf Websites or Software and all User Submissions are the responsibility of the person from whom such User Submissions originated. samesurf does not endorse any User Submissions or any opinion, 
				recommendation, or advice expressed therein, and expressly disclaims any and all liability in connection with User Submissions.<br/><br/> 

				In connection with your User Submissions, you represent and warrant that you (i) own or have the necessary licenses, rights, consents, and permissions to use and authorize samesurf to use all copyrights, 
				trade marks, trade secrets, patents and other intellectual property or proprietary rights in and to any and all User Submissions in accordance with these Terms; and (ii) you have the written consent, release 
				and /or permission of each and every identifiable individual person in the User Submission to use the name and/or likeness of each and every such individual in the User Submission, to enable inclusion and use 
				thereof in the manner contemplated by these Terms. You shall not copy, post or use text, photos, pictures, music, sounds, images or any other content from any third party or source ("Third Party Content") 
				without specific permission from the owner. Such Third Party Content may be protected by intellectual property laws and the owners of the intellectual property rights in such content may object to its use. 
				You must not use any Third Party Content without first obtaining the permission of the owner of the intellectual property rights in such content.<br/><br/> 

				If, at any time you choose to upload or post User Submissions to the samesurf websites or through the Software, you automatically grant samesurf a non-exclusive, worldwide, irrevocable, royalty-free, 
				perpetual, sub-licensable and transferable license of all rights to use, edit, modify, include, incorporate, adapt, record, publicly perform, display, transmit and reproduce the User Submissions including, 
				without limitation, all trade marks associated therewith, in connection with the samesurf websites and samesurf's Software and products including for the purpose of promoting or redistributing part or all 
				of the samesurf websites and/or the Software or products, in any and all media now known or hereafter devised. You also hereby grant each user of the samesurf website and/or samesurf's Software or products 
				a non-exclusive license to access your User Submission through the samesurf website and/or Software or products and to use, copy, distribute, prepare derivative works of, display, perform and transmit such 
				User Submissions solely as permitted through the functionality of the samesurf websites and/or Software or products and pursuant to these Terms of Use. In addition, you waive any so-called "moral rights" 
				in and to the User Submissions, to the extent permitted by applicable law.<br/><br/> 

				You may not submit or publish through the samesurf website or Software any User Submissions that are libelous, defamatory, pornographic, harassing, hateful, an invasion of privacy, obscene, abusive, illegal, 
				racist, offensive, harmful to a minor or an infringement of any intellectual property rights or a trade secret of a third party, or would otherwise violate the rights of any third party or give rise to civil 
				or criminal liability. Furthermore, you may not submit or publish User Submissions that contain falsehoods or mispresentations, solicit funds or services, contain advertising, promotional materials, junk mail, 
				spam, chain letters or any form of solicitation, impersonate others or include programs that contain viruses or any other programs designed to impair the functionality of any computer. You agree not to solicit, 
				for commercial purposes, any users of the samesurf website or Software with respect to their User Submissions. You agree not to circumvent, disable or otherwise interfere with the security related features of 
				the samesurf Website or Software or features that prevent or restrict the use of any content thereof.<br/><br/> 

				<div class="mediumheader2">No Reselling</div> The Software and products are for your individual use. You shall not resell or commercialize the Software and/or products to any third party.<br/><br/> 

				<div class="mediumheader2">Export Restrictions</div> The Software may be subject to international rules that govern the export of software. You shall comply with all applicable international and national 
				laws that apply to the Software as well as end-user, end-use, destination restrictions issued by national governments or similar bodies, and restrictions on embargoed nations. In the US, the Software may 
				not be exported or re exported from the US to or downloaded by any person in any countries controlled for anti terrorism reasons, which include Iran, North Korea, Cuba, Syria and Sudan. Moreover, the 
				Software may not be exported or re exported from the US to or downloaded by any person or entity subject to US sanctions regardless of location. samesurf is making the Software available to you for 
				download only on the condition that you certify that you are not such a person or entity and that the download is not otherwise in violation of US export control and sanctions regulations.<br/><br/>

				<div class="content1title"><a id="12"><div class="mediumheader">
						12.  PROPRIETARY INTERESTS
				</div></a></div>		

				The Software, products and samesurf websites contain proprietary and confidential information that is protected by intellectual property laws and treaties.  The content and compilation of content included 
				on the samesurf Websites (excluding User Submissions) such as text, graphics, logos, icons, images, audio clips, digital downloads and software, are the property of AW, its affiliates or licensors and are 
				protected by United States and international copyright laws. Such copyright protected content cannot be reproduced without samesurf's express permission. samesurf reserves all rights not expressly granted 
				in the samesurf websites.<br/><br/> 

				samesurf retains exclusive ownership of the Software, products and samesurf websites and all intellectual property therein (whether or not registered and anywhere in the world). You will not take any action 
				to jeopardize, limit or interfere with samesurf’s intellectual property rights in the Software, products and/or samesurf websites.<br/><br/> 

				<div class="mediumheader2">Business Marks</div>  samesurf&trade; is a trademark of Actual Worlds, Inc. AW has registered and filed applications to register its trademarks in many countries worldwide, and will 
				continue to register its trademarks in many others. AW's trademarks and trade dress may not be used in connection with any product or service that is not AW's, in any manner that is likely to cause 
				confusion among customers, or in any manner that disparages or discredits samesurf or AW. All other trademarks not owned by AW or any of its related companies that appear on this site are the property 
				of their respective owners. You are not permitted to and shall not register any trade name, trademark, logo, domain name or any other name or sign that incorporates any of AW's or samesurf's intellectual 
				property (in whole or part) or that is confusingly similar thereto.  All other trademarks, trade names, service marks, service names are the property of their respective holders, including but not limited 
				to, the following:<br/><br/>
				
				<ul>
					<li>"Google Talk" is a registered trademark of Google Inc.</li>
					<li>"Windows Live" MSN and the Windows Live Messenger icon are registered trademarks of Microsoft Corporation.</li>
					<li>"Facebook" is the registered trademark of Facebook, Inc.</li>
					<li>"Twitter" is the registered trademark of Twitter, Inc.</li>
				</ul><br/>
					
				It is hereby understood and agreed by the parties that samesurf is not affiliated with or endorsed by Google Inc., Microsoft Corporation, Facebook, Inc., Twitter, Inc. or any other company whose services 
				are integrated into samesurf.

				<div class="content1title"><a id="13"><div class="mediumheader">
						13.  PRICING AND CHARGES
					</div></a></div>

				<div class="mediumheader2">Charges for Paid For Products</div> Where applicable, the charges for paid for products will be confirmed to you before you complete a purchase from samesurf. samesurf may change 
				the applicable charges payable for the purchase of such products at any time without any notice to you. You can choose whether or not to accept the new charges prior to completing your next purchase of the 
				applicable product. The new charges will apply to your next purchase after the new charges have been published.<br/><br/> 

				<div class="mediumheader2">Third Party Charges:</div> Using the Software on mobile applications will use some of the data allowance available on the data package to which you have subscribed with your 
				mobile network operator. Out-of-country usage may lead to significantly higher costs than regular usage, and you are solely responsible for keeping yourself informed and paying for possible roaming and 
				other applicable charges levied by your mobile network operator.

				<div class="content1title"><a id="14"><div class="mediumheader">
						14. THIRD PARTY WEBSITES PRODUCTS AND SERVICES
				</div></a></div>

				Third parties may offer products or services via the Software and/or samesurf websites, including games, applications, images, ring tones, digital goods, digital services or avatars. The third party 
				products or services may be subject to the third party provider's own terms and privacy policy that you may have to accept upon download or installation. You should review such terms before making any 
				purchases or using any third party product or service and samesurf shall not be responsible for your failure to do so.<br/><br/> 

				<div class="mediumheader2">Merchants</div>  You acknowledge and agree that any third party product information and pricing that is shown on the samesurf Websites regarding third party products and 
				services is given to samesurf by the applicable third party merchant ("Merchant"). The Merchant has the ability to change their pricing or terminate their product availability at anytime. samesurf 
				is not involved in any transactions between you and any Merchant whose products and/or services are listed on the samesurf Websites. samesurf does not control, is not responsible for and does not 
				guarantee: (i) the pricing, quality, performance, availability or terms and conditions of purchase of products or services provided by the Merchant; (ii) any payment transactions, delivery, returns 
				or after sales activities related to the products or services purchased on the Merchants' websites; (iii) the availability of the Merchant's websites; (iv) the completeness, truth or accuracy of any 
				advertising or other materials on, or available from, the Merchants' websites, nor any listing or other content about such products and services displayed on the samesurf Websites; (v) links to the 
				Merchants' websites that are featured on the samesurf Websites. Any questions, complaints, or claims related to any product or service provided by a Merchant should be directed to the applicable 
				Merchant.<br/><br/> 

				<div class="mediumheader2">Hyperlinks</div> The Software and samesurf websites may include references or hyperlinks to other third party websites. samesurf is not responsible for such third party 
				websites or the availability of such websites and does not endorse any content or material on such third party websites. Your use of each of these third party websites is subject to the terms and 
				conditions posted on the applicable website. It is hereby agreed and understood that samesurf is not affiliated with, endorsed by or related to in any other respect with such entities.

				<div class="content1title"><a id="15"><div class="mediumheader">
						15.  TERMINATION
				</div></a></div>

				You may terminate your relationship with samesurf at any time by requesting closure of your User Account, ceasing to use the Software, products and/or samesurf websites.  samesurf may terminate 
				its relationship with you, or may terminate or suspend your use of the Software, User Account(s), products or samesurf websites at any time:<br/><br/> 

				(a) if you are in breach of these Terms;<br/><br/> 

				(b) if samesurf reasonably suspects that you are using the Software, the products and/or samesurf websites to break the law or infringe third party rights;<br/><br/> 

				(c) if samesurf reasonably suspects that you are trying to unfairly exploit or misuse any of our policies.<br/><br/> 

				(d) if samesurf reasonably suspects that you are using our products, Software and/or samesurf websites fraudulently or that your User Account is being used by a third party fraudulently; and<br/><br/> 

				(e) immediately, if required due to a change in laws/regulation by a regulator or authority with a lawful mandate, or by any of samesurf's partners;<br/><br/> 

				<div class="mediumheader2">Access</div> samesurf shall effect such termination by preventing your access to your User Account, the Software, products and/or samesurf Websites (as applicable). We reserve 
				the right to cancel User Accounts that have been inactive for more than one (1) year.<br/><br/> 

				<div class="mediumheader2">Consequences of Termination</div> Upon termination of your relationship with samesurf: (a) all licenses and rights to use the Software, products and/or samesurf websites shall 
				immediately terminate; (b) you will immediately cease any and all use of the Software, products and/or samesurf websites; and (c) you will immediately remove the Software from all hard drives, networks 
				and other storage media and destroy all copies of the Software in your possession or under your control.

				<div class="content1title"><a id="16"><div class="mediumheader">
						16. HOW TO CONTACT SAMESURF
				</div></a></div>

				To contact samesurf in relation to the samesurf Software or "samesurf" branded Products, please submit a support request to info@samesurf.com.<br/><br/>

				<div class="content1title"><a id="17"><div class="mediumheader">
						17. MISCELLANEOUS
				</div></a></div>

				<div class="mediumheader2">Electronic Communications</div> You agree to the use of electronic communication in order to enter into contracts, place orders, and create other records and to the electronic 
				delivery of notices, policies and changes thereto and records of transactions with samesurf or AW.<br/><br/> 

				<div class="mediumheader2">Entire Agreement</div> These Terms constitute the entire agreement between you and samesurf with respect to your use of the Software, products and/or samesurf websites and replace 
				any prior agreements between you and samesurf with respect to the Software, products and/or samesurf websites.   If you sign up or register for additional samesurf services that use third-party content or 
				third-party software, you may also be subject to additional terms and conditions that apply to such third-party content or third-party software.<br/> 

				<div class="mediumheader2">Validity</div> If any provision of these Terms (or part of it), is found by any court or administrative body of competent jurisdiction to be illegal, invalid or unenforceable, 
				then such provision (or part of it) shall be removed from the Terms without affecting the legality, validity or enforceability of the remainder of the Terms.<br/><br/> 

				<div class="mediumheader2">Not a Waiver</div> The failure by samesurf to exercise, or delay in exercising, a legal right or remedy provided by these Terms or by law shall not constitute a waiver of samesurf’s 
				right or remedy. If samesurf waives a breach of these Terms, this shall not operate as a waiver of a subsequent breach of the Terms.<br/><br/> 

				<div class="mediumheader2">Assignment of Terms</div>  You may not assign these Terms or any rights or obligations contained in them. samesurf may, without prior notice, assign these Terms or any rights or 
				obligations contained in them to any third party.<br/><br/> 

				<div class="mediumheader2">Survivability of Terms past Termination</div>  This paragraph shall survive termination of the Terms.<br/><br/> 

				<div class="mediumheader2">Force Majeure</div>  You acknowledge and agree that if samesurf is unable to provide the Software, Products and/or samesurf Websites as a result of a force majeure event, samesurf 
				will not be in breach of any of its obligations towards you under these Terms. A force majeure event means any event beyond the control of samesurf.<br/><br/>

				<div class="content1title"><a id="18"><div class="mediumheader">
						18. DISPUTES
				</div></a></div>

				By accessing samesurf you agree that the statutes and laws of the United States and the State of California, without regard to any principles of conflicts of law, will apply to all matters relating to the use 
				of the Services, and you further agree that any litigation shall be subject to the exclusive jurisdiction of the state and federal courts in the City and County of Los Angeles in the State of California, USA 
				and you consent to the personal jurisdiction of those courts. The failure of samesurf to exercise or enforce any right or provision of the Terms of Use does not constitute a waiver of such right or provision. 
				Regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to use of the Services, the Terms of Use or the Privacy Policy must be filed within one (1) year after 
				the event giving rise to such claim or cause of action or be forever barred. All headings in the Terms of Use are for convenience only and have no legal or contractual effect.

				<div class="content1title"><a id="19"><div class="mediumheader">
						19. CHANGE OF TERMS
				</div></a></div>

				AW reserves the right to modify, suspend, or discontinue the Software, or any part of samesurf, at any time and without notice to you. AW will not be liable to you should it exercise such right. AW reserves the 
				right to make changes to the Agreement at any time by posting the revised terms on the samesurf.com website. Your continued use of the Software following any such changes will constitute your acceptance of those 
				changes.

				<div class="content1title"><a id="20"><div class="mediumheader">
						20. DATA RETENTION POLICY
				</div></a></div>
				
				With the exception of company partnered educational institutions relating to the use of the samesurf downloadable (from the standpoint of the end user) applications for desktop and mobile devices, samesurf generally 
				logs web addresses -- known as uniform resource locators ("URLs") -- for the web pages and online content that our users access via samesurf for 365 days; samesurf also retains certain identifiers, such as IP or MAC 
				addresses. Even so, samesurf may elect to delete this or any other information for any reason and at any time in its sole and absolute discretion. These forms of data are retained for the purpose of troubleshooting 
				and diagnosing technical issues and for the purpose of transmitting personalized and relevant advertisements or opportunities to our users.<br/><br/>
				
					<div id="privpolbox">
						<div class="infobox2">
							<div class="infoboxtext"><a href="#cover">What this Privacy Policy Covers</a><br>
													 <a href="#collect">Information that samesurf Collects</a><br>
													 <a href="#private">What is public and what is private?</a><br>
													 <a href="#commplatforms">samesurf's communication platforms</a><br>
													 <a href="#cookies">samesurf's use of cookies</a><br>
							</div>
						</div>
						<div class="infobox2">
							<div class="infoboxtext"><a href="#platform">samesurf Platform</a><br>
													 <a href="#info">Information usage and sharing</a><br>
													 <a href="#emails">Emails and other notifications</a><br>
													 <a href="#security">Information Security</a><br>
													 <a href="#thirdparty">Third-Party Advertisers and Links to Other Websites</a><br>
							</div>
						</div>
						<div class="infobox2">
							<div class="infoboxtext"><a href="#nonus">Non-U.S. users; EU Safe Harbor</a><br>
													 <a href="#changes">Changes to this Privacy Policy</a><br>
													 <a href="#editing">Editing and deleting your account information</a><br>
													 <a href="#children">Children</a><br>
													 <a href="#comments">Comments and Questions</a>
							</div>
						</div>
					</div>	
					
					<br/><br/>
					
					<a id="cover"><div class="mediumheader2">What this Privacy Policy Covers</div></a><br/><br/>

					This Privacy Policy applies to all of the websites, software and services offered by samesurf/Actual Worlds, Inc.<br/><br/>

					By visiting, accessing or using samesurf, you agree to this Privacy Policy.<br/><br/>

					This Privacy Policy does not apply to any websites, products or services that are not owned or operated by samesurf or to actions taken by samesurf users. For example, this Privacy Policy does not apply to 
					third-party websites where the samesurf functionality appears, to third-party applications that may become available through samesurf, or to any social networks or IM service providers that you associate 
					with your samesurf account, all of which are governed by their own privacy policies.<br/><br/>

					<a id="collect"><div class="mediumheader2">Information that samesurf Collects</div></a><br/><br/>

					<em>Personally identifiable information</em><br/><br/>

					Personally identifiable information is information that can be used to determine your personal identity, such as your name or email address. When you create an account, we ask for your name and email address. 
					If you link your third-party instant messaging (IM) accounts to your samesurf account, we may also collect your user name for that account, which is also considered personally identifiable information.<br/><br/>
					
					With the exception of company partnered educational institutions relating to the use of the samesurf downloadable (from the standpoint of the end user) applications for dekstop and mobile devices, samesurf 
					generally logs web addresses -- known as uniform resource locators ("URLs") -- for the web pages and online content that our users access via samesurf for 365 days; samesurf also retains certain identifiers, 
					such as IP or MAC addresses.  Even so, samesurf may elect to delete this or any other information for any reason and at any time in its sole and absolute discretion. These forms of data are retained for 
					the purpose of troubleshooting and diagnosing technical issues and for the purpose of transmitting personalized and relevant advertisements or opportunities to our users.<br/><br/>

					<em>Optional profile data</em><br/><br/>

					samesurf gives you the opportunity to update your public profile with information about yourself such as your photo, place of residence, and links to your other social networking accounts.<br/><br/>

					<em>Information from the accounts you link to samesurf</em><br/><br/>

					If you connect your samesurf account to your third-party IM accounts or your social network accounts (e.g., Facebook and Twitter), they may send us information about you, including your name, username 
					at those services, Unique User ID ("UUID") for those services, friends list, status, profile information, age and gender.<br/><br/>

					<em>Demographic data</em><br/><br/>

					samesurf may ask for your age and gender at registration and may collect additional demographic information about you, such as your location and interests. samesurf may receive this information from you 
					or from outside sources, such as websites where the samesurf functionality is present, ad networks and other providers, or we may make assumptions based on the other information that we collect.<br/><br/>

					<em>Log data</em><br/><br/>

					When you use samesurf via a browser, mobile application or other application, like most other websites we automatically collect information about you and your activity (known as "log data"), including your 
					Internet Protocol (IP) address, your browser or device type, your mobile device ID, your interactions with samesurf, your interactions with third party IM and social networks through samesurf, your geographic 
					region and samesurf cookies associated with your browser. If you visit a site that has the embedded samesurf functionality, we also collect information about the website or web page that you view and your 
					interactions with that site.<br/>

					<em>Email address of friends you invite</em><br/><br/>

					If you use the samesurf feature that allows you to "Add Friends" to use samesurf or to "Chat with Friends," we will ask for your friend's email address but we will only use it to send them the invitation.<br/><br/>

					<a id="private"><div class="mediumheader2">What is public and what is private?</div></a><br/><br/>

					<em>Public information</em><br/><br/> 

					Many features of samesurf, such as samesurf profiles and Public Rooms, are designed to be a public experience in order to allow people with similar interests to find each other and share the online content that 
					they are visiting. This section describes which information is public. Public information is available to everyone on the Internet and can be viewed, copied, indexed, transferred and searched.<br/>

					<ul>
						<li>Your profile: Your samesurf public profile and all of the information on it are all public.</li>
						<li>Your username: Your username will also be part of your public profile URL (your samesurf profile web address) and will also be displayed to users who have access to samesurf. Because of the way the 
						Internet works, when you or other users click on a link from your public profile page, the website that you go to or the advertisements that you click on will also receive the URL that you are coming from, 
						which includes your user name (known as the "referrer URL").</li>
						<li>Your activity in samesurf Public Rooms. Your communications in samesurf Public Rooms are logged and can be seen by anyone the user who created the samesurf Public Room has allowed to access the samesurf 
						Public Rooms, which may be everyone. Your postings on samesurf message boards or forums are also public.</li>
						<li>Components not labeled Private. Any components that are not otherwise labeled as private in this Privacy Policy are hereby deemed to be public.</li>
					</ul>	
						
					<em>Private Information</em><br/><br/> 

					The following information is not made available as part of your public profile or otherwise made public by samesurf: (1) your age and gender; (2) your email address; (3) your third-party IM account buddies or 
					third-party (e.g., Facebook) social network friends; (4) your IM communications; and (5) your log data.<br/><br/>

					<a id="commplatforms"><div class="mediumheader2">samesurf's Communication Platforms</div></a><br/><br/>

					samesurf offers users the ability to communicate with each other through IM, in-room chat, samesurf Public Rooms, audio & video chat and other mechanisms. Please note that you should never disclose personal 
					information about yourself in a public area like samesurf Public Rooms. You should never share personal information in a private IM or in any other manner with samesurf unless it's with someone you know 
					well and trust.<br/><br/> 

					When you create a samesurf account, your preferences are set to enable all samesurf users to send you an IM.  By using samesurf, you consent to the storage of your IM history on samesurf as the default 
					option and to the storing of your IM history by other users with whom you are chatting or by the Third Party IM Service that you or your friend is using. samesurf may customize the advertising shown to users 
					based on software analysis of IM chat, samesurf Room conversations or other data.<br/><br/>

					<a id="cookies"><div class="mediumheader2">samesurf's Use of Cookies</div></a><br/><br/>

					Like most websites and web applications, samesurf uses cookies. A cookie is a small amount of data, which often includes an anonymous unique identifier that is sent to your browser from a website's computers 
					and stored on your computer's hard drive. samesurf does not store personally identifiable information or passwords in its cookies.<br/><br/> 

					We use these cookies to provide you with a better samesurf experience, such as by recognizing you when you come to samesurf.  We also use cookies to generate aggregate and anonymous data so that we can better 
					understand and analyze how our users utilize samesurf.<br/><br/> 

					samesurf also allows third parties to place cookies on your browser in order to help us with our analytics, to deliver and report on advertising that runs on samesurf and to measure whether you've seen or 
					interacted with an ad on samesurf or other sites. samesurf does not allow these third parties to collect any personally identifiable information about you through their cookies on samesurf.  Please note that 
					the cookies that we and our third-party advertising partners set are often used to provide customized advertising to you on samesurf and on the other websites that you visit.<br/><br/>

					<a id="platform"><div class="mediumheader2">samesurf Platform</div></a><br/><br/>

					samesurf may allow third parties who have entered into an agreement with us to make their applications available through samesurf.  samesurf may provide these third-parties with information that is part of 
					your public profile, as described under the "What is public and what is private" section.  samesurf requires that these third parties only use this information to provide their applications to you and that 
					they not disclose it to any third party without your consent.<br/><br/> 

					In addition, some of the applications may collect personally identifiable information from you directly. In that case, any information that you provide through the application will be governed by the 
					application owner's privacy policy, which you should review. Each application owner will be solely responsible for complying with its privacy policy.<br/><br/>

					<a id="info"><div class="mediumheader2">Information Usage and Sharing</div></a><br/><br/>

					<em>Usage of information</em><br/><br/> 

					samesurf uses the information it collects (1) to provide you with access to your account; (2) to provide you with the samesurf services; (3) to enhance and improve the samesurf services; (4) to recommend 
					to you or other samesurf users potential friends or websites that may be of interest; (5) to provide customized advertising to you; (6) to conduct research; (7) to determine your geographic location or 
					other demographic information about you; (8) to create reports and to analyze usage patterns; and (9) to contact you via email.<br/><br/> 

					<em>Sharing of information</em><br/><br/> 

					samesurf may share your non-public personally identifiable information with third parties only in the following cases:  (1) we may need to share your log-in information with the third-party IM services 
					and networks where you have an account that you have chosen to access through samesurf in order to permit you to log onto and use that service; (2) with trusted third-party service providers who help us 
					in the operation of samesurf and who have agreed to maintain the confidentiality of the data; (3) to the third-party applications available through samesurf, as described under “samesurf Platform;” (4) 
					when we have your consent; (5) in cases of abusive behavior or suspected violations of the terms of use of samesurf or of any third-party service accessed through or in association with samesurf, we may 
					share personal information, including IP address, with that third party in order to investigate the violation and to take appropriate action; (6) where we have a good faith belief that it is required in 
					order to respond to subpoenas, court orders, or other legal process, to prevent fraud or imminent harm, or to establish or exercise our legal rights or defend against legal claims; or (7) in the event 
					that samesurf is acquired by or merged with another company or transfers substantially all of its assets to another company, samesurf will transfer all of its user information and data, including information 
					about you, to that other company.  samesurf may share your public information or any anonymous information for any of the purposes described under "Usage of information."<br/><br/>

					<a id="emails"><div class="mediumheader2">Emails and Other Notifications</div></a><br/><br/>

					samesurf reserves the right to send you communications relating to your account and the samesurf services. You consent to receiving all legally-required notifications from samesurf through display on 
					samesurf, through the email associated with your samesurf account or the email associated with any of your third-party IM services or social networks through which you connect to samesurf (such as Facebook).<br/><br/>

					<a id="security"><div class="mediumheader2">Information Security</div></a><br/><br/>

					We work to protect the security of your information during transmission by using Secure Sockets Layer (SSL) software, which encrypts information you input.  Nevertheless, it is important for you to protect 
					against unauthorized access to your password and to your computer. Be sure to sign off when finished using a shared computer or when sharing online content of any kind.<br/><br/>

					<a id="thirdparty"><div class="mediumheader2">Third-Party Advertisers and Links to Other Websites</div></a><br/><br/>

					Our site includes third-party advertising and links to other Web sites. We do not provide any personally identifiable customer information to these advertisers or third-party Web sites.<br/><br/> 

					These third-party web sites and advertisers, or Internet advertising companies working on their behalf, sometimes use technology to send (or "serve") the advertisements directly to your browser or the 
					samesurf applications in the various formats. They automatically receive your IP address when this happens. They may also use cookies, JavaScript, web beacons (also known as action tags or single-pixel gifs) 
					and other technologies to measure the effectiveness of their ads and to personalize advertising content. We do not have access to or control over cookies or other features that they may use and the information 
					practices of these advertisers and third-party Web sites are not covered by this Privacy Notice.<br/><br/> 

					samesurf also displays personalized third-party advertising based on personal information about customers, such as purchasing history and visits to certain sites.  Although samesurf does not provide any 
					personal information to advertisers, advertisers (including ad-serving companies) may assume that users who interact with or click on a personalized advertisement meet their criteria to personalize the ad.<br/><br/>

					<a id="nonus"><div class="mediumheader2">Non-U.S. users; EU Safe Harbor</div></a><br/><br/>

					samesurf is hosted and operated entirely in the United States and is subject to United States law. Any personal information that you provide to samesurf is being provided to samesurf solely in the United States 
					and will be hosted on United States servers. You consent to the transfer of your personal information to the United States. If you are accessing samesurf from outside the United States, please be advised that 
					United States law may not offer the same privacy protections as the law of your jurisdiction.<br/><br/>

					<a id="changes"><div class="mediumheader2">Changes to this Privacy Policy</div></a><br/><br/>

					Any changes to this policy will be posted in the policies link in the footer of the following URL: http://www.samesurf.com. We will not use data we collect in a manner that is materially different from promises 
					made in this Privacy Policy without your consent.<br/><br/>

					<a id="editing"><div class="mediumheader2">Editing and deleting your account information</div></a><br/><br/>

					You can edit certain personal information that you have provided or request that your account be deleted by logging into your samesurf account and accessing your account settings. Information that was already 
					publicly shared and messages that you previously sent will still be visible in the various places that information is displayed.<br/><br/>

					<a id="children"><div class="mediumheader2">Children</div></a><br/><br/>

					samesurf does not knowingly permit children under 13 to create a samesurf account, access samesurf or to use samesurf Public Rooms. In addition, samesurf does not store the personal information of users who access 
					their third-party IM accounts and indicate to us that they are under 13. In the event that we learn that we have collected personal information from a child under age 13, we will delete that information. If you 
					are a parent of a child under 13 and you believe that your child has created a samesurf account in violation of our policy, please contact us immediately at <a href=mailto:info@samesurf.com>info@samesurf.com</a>.<br/><br/>

					<a id="comments"><div class="mediumheader2">Comments and Questions</div></a><br/><br/>

					samesurf periodically reviews its privacy practices and this privacy policy. We encourage interested persons to raise any concerns by emailing us at <a href=mailto:info@samesurf.com>info@samesurf.com</a> and we will 
					investigate and attempt to resolve any concerns or complaints.<br/><br/>
			</div>
		
		</div>
	</div>		