<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/livechat.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/livechat.js");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>
	<div id="content0">
		<div class="centredcontent">
			
			<div id=content0title><div class="mediumheader">LIVE CHAT</div></div>
							
			<a href="#" id="topdlbutton" class="enablesite">DEMO SAMESURF</a>
			
		</div>	
	</div>	
	
		<div id="content1">
		<div class="centredcontent">
						
			<div class="content1text"><div class="alltext">Samesurf adds a visual element to interactions<br/>  
with customers by enabling agents to offer<br/> 
co-browsing as a helpful complement to chat.   
			<a href="/pages/howitworks"><div class="bluebutton">How It Works</div></a>
			</div></div>
				<div id="content1circle">	
					<div id="content1image"></div>
				</div>	
		</div>
	</div>	
	
	<div id="content2">
		<div class="centredcontent">
			<div id="content2title"><div class="mediumheader">KEY POINTS</div></div>
				<div id="grid">
					<div class="bulletbox">
						<div class="bulletptblue"></div>
					Elevated conversion, upsell and cross-sell rates
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptorange"></div>
					Support for both open and authenticated sites
					</div>
					
					<div class="bulletbox">
						<div class="bulletptred"></div>
					Full interactivity for both agents and customers
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptgreen"></div>
					Built-in security features like TLS/SSL encryption
					</div>
					
					<div class="bulletbox">
						<div class="bulletptgreen"></div>
					Privacy safeguards that feature field blocking
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptred"></div>
					Complementary tools such as PDF co-browsing
					</div>
					
					<div class="bulletbox">
						<div class="bulletptorange"></div>
					Cross platform for all devices and browsers 
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptblue"></div>
					Highly scalable and cost-effective support tool
					</div>
				</div>
		
		</div>
	</div>
	
	
	<div id="content3">
		<div class="centredcontent">
			<div id="content3title"><div class="mediumheader">INSTANT CO-BROWSING</div></div>
						
			<div class="content3text"><div class="alltext">Agents and customers are able to enhance<br/>
			standard Live Chat interactions by toggling <br/>
			into co-browse sessions with a single click. </div></div>
				<div id="content3image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/LC2CB.png" /></div>
		</div>
	</div>	
	
	<div id="content4">
		<div class="centredcontent">
			<div id="content4image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/noinstalls.png" /></div>
				<div id="content4title"><div class="mediumheader">NO INSTALLS OF ANY KIND</div></div>
						
			<div class="content4text"><div class="alltext">Samesurf differentiates itself from alternative<br/> 
offerings by eliminating coding requirements,<br/>  
installs and exorbitant up-front expenditures. 
			</div></div>
		</div>
	</div>	