<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/marketresearch.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/marketresearch.js");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>
	<div id="content0">
		<div class="centredcontent">
			
			<div id=content0title><div class="mediumheader">MARKET RESEARCH</div></div>
			<div id="content0text"><div class="alltext">Achieve cost efficiencies and deeper insights by leveraging <br/>
diverse sample sets to conduct market research online.</div></div>				
			<a href="#" id="topdlbutton" class="enablesite">DEMO SAMESURF</a>
			<div id="marketresearchimage"></div>
			
		</div>	
	</div>	
	
	<div id="content1">
		<div class="centredcontent">
			<div id="content1title"><div class="mediumheader">WHY USE SAMESURF WITHIN MARKET RESEARCH?</div></div>
				<div id="grid">
					<div class="bulletbox">
						<div class="bulletptblue"></div>
					Larger and more diverse user response groups 
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptorange"></div>
					Interaction with multiple panelists at one time
					</div>
					
					<div class="bulletbox">
						<div class="bulletptred"></div>
					Significant time, resource and expense reductions
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptgreen"></div>
					Highly effective framework for mobile research
					</div>
					
					<div class="bulletbox">
						<div class="bulletptgreen"></div>
					Instant reaction monitoring using HD video chat
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptred"></div>
					Reductions in user error from install-free platform
					</div>
					
					<div class="bulletbox">
						<div class="bulletptorange"></div>
					Real-time client participation during live sessions
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptblue"></div>
					Ability to instantly modify study methodologies   
					</div>
				</div>
		
		</div>
	</div>
	
		
	
	<div id="content2">
		<div class="centredcontent">
			<div id="content2title"><div class="mediumheader">FEATURES</div></div>
				<div id="grid2">
				<a href="/pages/features#content1" class="iconsq1">
					<div id="icon1"></div>
				</a>

				<a href="/pages/features#content6" class="iconsq2">
					<div id="icon2"></div>
				</a>

				<a href="/pages/features#content4" class="iconsq3">
					<div id="icon3"></div>
				</a>

				<a href="/pages/features#content12" class="iconsq4">
					<div id="icon4"></div>
				</a>

				<a href="/pages/features#content8" class="iconsq5">
					<div id="icon5"></div>
				</a>
			</div>	
			
		</div>
	</div>	
	
	<div id="content3">
		<div class="centredcontent">
			<div id="assistedsalesvid">
					<iframe src="//player.vimeo.com/video/77007215?title=0&amp;byline=0&amp;portrait=0" 
					width="917" height="516" allowfullscreen></iframe>
			</div>
			
		</div>
	</div>	
	
	<div id="content4">
		<div class="centredcontent">
			<div id="content4image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/focusgps.png" /></div>
				<div id="content4title"><div class="mediumheader">ONLINE FOCUS GROUPS</div></div>
						
			<div class="content4text"><div class="alltext">Samesurf enables moderators to interact,  
poll and record multiple panelists from  
all portions of the world at the same time.</div></div>
		</div>
	</div>	
	
	<div id="content5">
		<div class="centredcontent">
			<div id="content5title"><div class="mediumheader">INSIGHTS FROM THE CLOUD</div></div>
						
			<div class="content5text"><div class="alltext">Our solutions complement existing research <br/>
tools that measure respondent reactions to <br/>
stimuli such as products and ad campaigns.</div></div>
				<div id="content5image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/mktrschcloud.png" /></div>
		</div>
	</div>	