<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/meetings.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/meetings.js");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>
	<div id="content0">
		<div class="centredcontent">
			
			<div id=content0title><div class="mediumheader">MEETINGS</div></div>
			<div id="content0text"><div class="alltext">Simplify your online meetings and demos with an</br>install-free platform for inspired collaboration.</div></div>
			<a href="#" id="topdlbutton" class="enablesite">DEMO SAMESURF</a>
			<div id="meetingsimage"></div>
			
		</div>	
	</div>	
	
	<div id="content1">
		<div class="centredcontent">
			<div id="content1title"><div class="mediumheader">WHY USE SAMESURF FOR MEETINGS?</div></div>
				<div id="grid">
					<div class="bulletbox">
						<div class="bulletptblue"></div>
					Ultra-visual platform for seamless web meetings
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptorange"></div>
					Ability to toggle between online & offline content
					</div>
					
					<div class="bulletbox">
						<div class="bulletptred"></div>
					Crystal clear and lag-free co-browsing of the web 
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptgreen"></div>
					Co-browsing support for 5000 simultaneous users
					</div>
					
					<div class="bulletbox">
						<div class="bulletptgreen"></div>
					Multi-way interactivity for all session participants
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptred"></div>
					Functions on virtually every device and browser  
					</div>
					
					<div class="bulletbox">
						<div class="bulletptorange"></div>
					Carries extensive privacy and security safeguards
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptblue"></div>
					Install-free framework for instant web meetings
					</div>
				</div>
		
		</div>
	</div>
	
		
	
	<div id="content2">
		<div class="centredcontent">
			<div id="content2title"><div class="mediumheader">FEATURES</div></div>
				<div id="grid2">
				<a href="/pages/features#content1" class="iconsq1">
					<div id="icon1"></div>
				</a>

				<a href="/pages/features#content6" class="iconsq2">
					<div id="icon2"></div>
				</a>

				<a href="/pages/features#content4" class="iconsq3">
					<div id="icon3"></div>
				</a>

				<a href="/pages/features#content12" class="iconsq4">
					<div id="icon4"></div>
				</a>

				<a href="/pages/features#content8" class="iconsq5">
					<div id="icon5"></div>
				</a>
			</div>	
			
		</div>
	</div>	
	
	<div id="content3">
		<div class="centredcontent">
			<div id="assistedsalesvid">
					<iframe src="//player.vimeo.com/video/77007215?title=0&amp;byline=0&amp;portrait=0" 
					width="917" height="516" allowfullscreen></iframe>
			</div>
			
		</div>
	</div>	
	
	<div id="content4">
		<div class="centredcontent">
			<div id="content4image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/nohassles.png" /></div>
				<div id="content4title"><div class="mediumheader">NO INSTALLS OF ANY KIND</div></div>
						
			<div class="content4text"><div class="alltext">Samesurf transcends screen sharing by<br/>
eliminating the installs that delay entry<br/>
into collaborative web experiences.</div></div>
		</div>
	</div>	
	
	<div id="content5">
		<div class="centredcontent">
			<div id="content5title"><div class="mediumheader">PRISTINE SCREEN CLARITY</div></div>
						
			<div class="content5text"><div class="alltext">Our solutions empower multiple people<br/>
			to co-browse content together without<br/>
			compromising pristine screen clarity.</div></div>
				<div id="content5image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/crystalclr.png" /></div>
		</div>
	</div>	
	
		
