<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/partners.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/partners.js");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>
	<div id="content0">
		<div class="centredcontent">
			
			<div id=content0title>
				<div class="mediumheader">PARTNERSHIPS</div>
			</div>
			
			<a href="#" class="enablesite becomeapartner" id="topdlbutton">BECOME A PARTNER</a>	
								
		</div>	
	</div>	
	
	<div id="content1">
		<div class="centredcontent">
			<div class="content1text"><div class="alltext">Add multi-user support to your suite of<br/>
offerings by incorporating Samesurf for <br/>
online support, sales and collaboration.<br/><a href="#">Become a Partner</a></div></div>
				<div id="content1image"></div>
		</div>
	</div>
	
	<div id="content2">
		<div class="centredcontent">
			<div id="content2title"><div class="mediumheader">WHY PARTNER WITH SAMESURF?</div></div>
				<div id="grid">
					<div class="bulletbox">
						<div class="bulletptblue"></div>
					Expand the breadth of your suite of offerings
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptgreen"></div>
					Convert your products into multi-user experiences 
					</div>
					
					<div class="bulletbox">
						<div class="bulletptred"></div>
					Leverage our patents on co-browsing technology
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptred"></div>
					Introduce cutting edge solutions to your clients
					</div>
					
					<div class="bulletbox">
						<div class="bulletptgreen"></div>
					Gain an effective partner for sales opportunities 
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptblue"></div>
					Originate highly complementary revenue streams
					</div>
					
				</div>
		
		</div>
	</div>
	
		
	<div id="content3">
		<div class="centredcontent">
			<div id="content3image"></div>
				<div id="content3title"><div class="mediumheader">PATENTED TECHNOLOGY</div></div>
						
			<div class="content3text"><div class="alltext">Our broad and growing patent portfolio<br/>
for collaborative browsing continues to<br/>
protect our unique brand of offerings.</div></div>
		</div>
	</div>	
	
	<div id="content4">
		<div class="centredcontent">
			<div id="content4title"><div class="mediumheader">BEST IN CLASS CO-BROWSING</div></div>
						
			<div class="content4text"><div class="alltext">Samesurf trumps alternatives by eliminating installs, incorporating<br/>
unique features and delivering a truly seamless experience.</div></div>
				<div id="content4image"></div>
		</div>
	</div>	
	
	<div id="content5">
		<div class="centredcontent">
			<div id="content5title"><div class="mediumheader">SYSTEM LEVEL INTEGRATION</div></div>
						
			<div class="content5text"><div class="alltext">Our offerings integrate flawlessly within complementary<br/>
solutions like Live Chat, Phone Support and Kiosks.</div></div>
			
			<div id="content5image"></div>
			
			<div class="content5text2"><div class="alltext">Learn more about <a href="/pages/phonesupport">Phone Support</a> and 
			<a href="/pages/livechat">Live Chat</a>.</div></div>
			
		</div>
	</div>	
	
	<div id="content6">
		<div class="centredcontent">
						
			<div class="content6text"><div class="mediumheader">CONTACT US</div></div>
				<div class="smalltext"><div class="alltext">Contact us to become a partner or to get more information:</div></div>
				
				<form method="post">	
					<div id="nameinput">
						<input type="text" id="nametext" value="Name" name="name"/>
					</div>
					
					<div id="emailinput">
						<input type="text" id="emailtext" value="Email Address" name="email"/>
					</div>
					
					<div id="titleinput">
						<input type="text" id="titletext" value="Title" name="title"/>
					</div>
					
					<div id="phoneinput">
						<input type="text" id="phonetext" value="Phone" name="phone"/>
					</div>
					
					<div id="companyinput">
						<input type="text" id="companytext" value="Company" name="company"/>
					</div>
					
					<div id="forminput">
						<textarea id="formtextarea" name="info">Enter Message...</textarea>
					</div>
				</form>	
				<div id="formsubmit">SUBMIT</div>
			
		</div>
	</div>	
		
