<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/phonesupport.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/phonesupport.js");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>
	<div id="content0">
		<div class="centredcontent">
			
			<div id=content0title><div class="mediumheader">PHONE SUPPORT</div></div>
							
			<a href="#" id="topdlbutton" class="enablesite">DEMO SAMESURF</a>
			
		</div>	
	</div>	
	
		<div id="content1">
		<div class="centredcontent">
						
			<div class="content1text"><div class="alltext">Samesurf enhances traditional phone support by
enabling agents to offer interactive expertise via<br/>  
instant co-browsing for virtually every platform.<br/>
			<a href="/pages/howitworks"><div class="bluebutton">How It Works</div></a>
			</div></div>
			<div id="content1image"></div>
		</div>
	</div>	
	
	<div id="content2">
		<div class="centredcontent">
			<div id="content2title"><div class="mediumheader">KEY POINTS</div></div>
				<div id="grid">
					<div class="bulletbox">
						<div class="bulletptblue"></div>
					Instant session entry via the Join a Room feature
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptorange"></div>
					Higher conversion, upsell and cross-sell rates
					</div>
					
					<div class="bulletbox">
						<div class="bulletptred"></div>
					Support for both open and authenticated sites 
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptgreen"></div>
					Cross platform across all devices and browsers
					</div>
					
					<div class="bulletbox">
						<div class="bulletptgreen"></div>
					Highly scalable and cost-effective support tool
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptred"></div>
					Collaboration features such as joint form filling
					</div>
					
					<div class="bulletbox">
						<div class="bulletptorange"></div>
					Privacy safeguards featuring single tab sharing
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptblue"></div>
					Seamless install-free support and sales solution
					</div>
				</div>
		
		</div>
	</div>
	
	
	<div id="content3">
		<div class="centredcontent">
			<div id="content3title"><div class="mediumheader">INSTANT CO-BROWSING</div></div>
						
			<div class="content3text"><div class="alltext">
Samesurf empowers agents to immerse<br/>
customers into co-browse sessions via<br/>
gateways like email and mobile invites.<br/>
			</div></div>
			<div id="content3image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/PS2CB.png" /></div>
		</div>
	</div>	
	
	<div id="content4">
		<div class="centredcontent">
			<div id="content4image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/joinroom.png" /></div>
			<div id="content4title"><div class="mediumheader">THE JOIN A ROOM BOX</div></div>
						
			<div class="content4text"><div class="alltext"> The Join a Room box grants users instant<br/> 
entry into sessions by having agents read<br/>  
out the room number for customer entry.
			</div></div>
		</div>
	</div>	
