<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/presentations.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/presentations.js");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>
	<div id="content0">
		<div class="centredcontent">
			
			<div id=content0title><div class="mediumheader">PRESENTATIONS</div></div>
			<div id="content0text"><div class="alltext">Deliver install-free presentations without the</br>hassles and latency of screen sharing.</div></div>	
			<a href="http://sameslide.com" class="visitsameslide" id="topdlbutton">VISIT SAMESLIDE.COM</a>
			<div id="presentationsimage"></div>
		</div>
	</div>
	
	<div id="content1">
		<div class="centredcontent">
			<div id="content1title"><div class="mediumheader">WHY USE SAMESURF FOR PRESENTATIONS?</div></div>
				<div id="grid">
					<div class="bulletbox">
						<div class="bulletptblue"></div>
					Highly effective tool for install-free presentations
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptorange"></div>
					Instant ability to co-browse virtually any website
					</div>
					
					<div class="bulletbox">
						<div class="bulletptred"></div>
					Crystal clear presentations residing in the cloud
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptgreen"></div>
					Simultaneous co-browsing for up to 5000 users
					</div>
					
					<div class="bulletbox">
						<div class="bulletptgreen"></div>
					Multi-way interactivity for every session attendee
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptred"></div>
					Broad-based browser and device compatibility
					</div>
					
					<div class="bulletbox">
						<div class="bulletptorange"></div>
					Fully integrated privacy and security safeguards
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptblue"></div>
					Ideal for sharing perfectly synced video content
					</div>
				</div>
		
		</div>
	</div>
	
		
	
	<div id="content2">
		<div class="centredcontent">
			<div id="content2title"><div class="mediumheader">FEATURES</div></div>
			<div id="grid2">
				<a href="/pages/features#content1" class="iconsq1">
					<div id="icon1"></div>
				</a>

				<a href="/pages/features#content6" class="iconsq2">
					<div id="icon2"></div>
				</a>

				<a href="/pages/features#content4" class="iconsq3">
					<div id="icon3"></div>
				</a>

				<a href="/pages/features#content12" class="iconsq4">
					<div id="icon4"></div>
				</a>

				<a href="/pages/features#content8" class="iconsq5">
					<div id="icon5"></div>
				</a>
			</div>		
			
		</div>
	</div>	
	
	<div id="content3">
		<div class="centredcontent">
			<div id="assistedsalesvid">
					<iframe src="//player.vimeo.com/video/77007215?title=0&amp;byline=0&amp;portrait=0" 
					width="917" height="516" allowfullscreen></iframe>
			</div>
			
		</div>
	</div>	
	
	<div id="content4">
		<div class="centredcontent">
			<div id="content4image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/share.png" /></div>
				<div id="content4title"><div class="mediumheader">PERSUADE AND CLOSE </div></div>
						
			<div class="content4text"><div class="alltext">
				Guide your viewers through an array of <br/>
				slides and videos with the instant ability <br/>
				to toggle into co-browsing for websites. <br/>
				</div></div>
		</div>
	</div>	
	
	<div id="content5">
		<div class="centredcontent">
			<div id="content5title"><div class="mediumheader">PRESENT ANYTIME, ANYWHERE</div></div>
						
			<div class="content5text"><div class="alltext">Eliminate the exorbitant costs that come with<br/>in-person presentations while gaining instant<br/>access to a global audience.</div></div>
				<div id="content5image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/presentanywhere.png" /></div>
		</div>
	</div>	
		