<?php $this->setTitle("samesurf"); $this->addCSSFile("/static/css/pages/press.css"); $this->addCSSFile("/static/css/pages/general.css"); $this->addJSFile("/static/js/pages/press.js"); $this->addJSFile("/static/js/pages/lazyload.js"); $this->addJSFile("/static/js/pages/animate.js");
$this->addCSSFile("/static/css/pages/lazyload.css"); $this->addCSSFile("/static/css/pages/animate.css"); ?>
<div id="press_container">
	<div id="press">
		<div id="press_title" class="press_header">
			PRESS
		</div>
	</div>

	<div id="assets_container">
		<div class="assets_boxes">
			<a href="">
				<div id="facebook_box" class="contact_facebook_twitter_boxes">
					<div id="facebook_text" class="three_boxes_text">
						FACEBOOK
					</div>
				</div>
			</a>
			<a href="">
				<div id="twitter_box" class="contact_facebook_twitter_boxes">
					<div id="twitter_text" class="three_boxes_text">
						TWITTER
					</div>
				</div>
			</a>
			<a href="">
				<div id="google_box" class="contact_facebook_twitter_boxes">
					<div id="google_text" class="three_boxes_text">
						GOOGLE+
					</div>
				</div>
			</a>
		</div>
	</div>
</div>


<div id="content2">
	<div class="centredcontent">
		<div id="content2title">
			<div class="mediumheader">
				ASSETS
			</div>
		</div>
		<div id="grid">
			<div class="assetimgplustext1">
				<div class="asset1">
				</div>
				<div class="assettext">
					HQ LOGO
				</div>
			</div>

			<div class="assetimgplustext2">
				<div class="asset2">
				</div>
				<div class="assettext">
					300X250 S ADVERTS
				</div>
			</div>

			<div class="assetimgplustext3">
				<div class="asset3">
				</div>
				<div class="assettext">
					160X600 V ADVERTS
				</div>
			</div>

			<div class="assetimgplustext4">
				<div class="asset4">
				</div>
				<div class="assettext">
					730X90 H ADVERTS
				</div>
			</div>

			<div class="assetimgplustext5">
				<div class="asset5">
				</div>
				<div class="assettext">
					SAMESURF VIDEOS
				</div>
			</div>
		</div>

	</div>
</div>

<div id="content3">
	<div class="centredcontent">
		<div id="content3title">
			<div class="mediumheader">
				ARTICLES
			</div>
		</div>

		<div class="grey_text press2_text">
			<div class="alltext">
				July 24th 2012 -
			</div>
		</div>
		<div class="blue_text press2_text">
			Social Shopping Leader Kaboodle Partners with Samesurf
		</div>
		<div class="presstext">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ultrices ligula, nec sollicitudin eros sagittis ac. Nunc sed ante a justo pulvinar consectetur non elementum purus. Vestibulum congue enim ac orci varius, a mollis mauris tristique.
			Vivamus magna turpis.</div>

		<div class="grey_text press2_text">
			<div class="alltext">
				July 24th 2012 -
			</div>
		</div>
		<div class="blue_text press2_text">
			Social Shopping Leader Kaboodle Partners with Samesurf
		</div>
		<div class="presstext">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ultrices ligula, nec sollicitudin eros sagittis ac. Nunc sed ante a justo pulvinar consectetur non elementum purus. Vestibulum congue enim ac orci varius, a mollis mauris tristique.
			Vivamus magna turpis.</div>

		<div class="grey_text press2_text">
			<div class="alltext">
				July 24th 2012 -
			</div>
		</div>
		<div class="blue_text press2_text">
			Social Shopping Leader Kaboodle Partners with Samesurf
		</div>
		<div class="presstext">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ultrices ligula, nec sollicitudin eros sagittis ac. Nunc sed ante a justo pulvinar consectetur non elementum purus. Vestibulum congue enim ac orci varius, a mollis mauris tristique.
			Vivamus magna turpis.</div>
	</div>
</div>

<div id="content4">
	<div class="centredcontent">
		<div id="leftcontent">
			<div id="leftcontenttitle">
				AS SEEN ON
			</div>
			<div class="blue_text">
				Phasellus fringilla
			</div>
			<div class="grey_text2">
				<div class="presstext">
					Cras ac ligula convallis, semper neque a, cursus turpis. Phasellus vitae porta purus. Nam gravida hendrerit elit.
				</div>
			</div>
			<div class="blue_text">
				Phasellus fringilla
			</div>
			<div class="grey_text2">
				<div class="presstext">
					Cras ac ligula convallis, semper neque a, cursus turpis. Phasellus vitae porta purus. Nam gravida hendrerit elit.
				</div>
			</div>
			<div class="blue_text">
				Phasellus fringilla
			</div>
			<div class="grey_text2">
				<div class="presstext">
					Cras ac ligula convallis, semper neque a, cursus turpis. Phasellus vitae porta purus. Nam gravida hendrerit elit.
				</div>
			</div>

		</div>
		<div id="rightcontent">
			<div id="rightcontenttitle">
				REQUEST INTERVIEW
			</div>

			<form method="post">
				<div class="contactbox">
					<input type="text" id="nametext" value="Name" name="name"/>
				</div>

				<div class="contactbox">
					<input type="text" id="emailtext" value="Email Address" name="email"/>
				</div>

				<div class="contactbox">
					<input type="text" id="companytext" value="Company" name="company"/>
				</div>

				<div class="contactbox2">
					<textarea id="formtextarea" name="info">Your Message...</textarea>
				</div>

				<div class="contactbox3">
					<button id="interview-submit-btn">
						SUBMIT
					</button>
				</div>
			</form>
		</div>
	</div>
</div>


