<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addCSSFile("/static/css/pages/pricingweb.css");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>

<div class="web_light">
	<div class="web_centered_content web_section_1">
		<p id="web_uses_head">SAMESURF FOR WEBSITES</p>
		<a href="#"  class="enablesite" id="topdlbutton">HOW IT WORKS</a>
	</div>
</div>

<div class="web_dark">
	<div class="web_centered_content web_section_2">
		<div id="monthly_pricing_table">
			<div id="web_session_pricing_basic" class="web_session_pricing">
				<p class="web_session_pricing_head">BASIC</p>
				<div class="web_session_pricing_table">
					<div class="web_session_pricing_table_head">
						<span class="web_session_pricing_table_entry">MONTHLY SESSIONS</span>
						<span class="web_session_pricing_table_entry">PRICING</span>
					</div>
					<div class="web_session_pricing_table_row">
						<span class="web_session_pricing_table_entry web_session_pricing_table_left">1-1000</span>
						<span class="web_session_pricing_table_entry web_session_pricing_bold"><span class="dollar_super">$</span>99</span>
					</div>
					<div class="web_session_pricing_table_row">
						<span class="web_session_pricing_table_entry web_session_pricing_table_left">1001-2100</span>
						<span class="web_session_pricing_table_entry web_session_pricing_bold"><span class="dollar_super">$</span>199</span>
					</div>
					<div class="web_session_pricing_table_row">
						<span class="web_session_pricing_table_entry web_session_pricing_table_left">2101-3200</span>
						<span class="web_session_pricing_table_entry web_session_pricing_bold"><span class="dollar_super">$</span>299</span>
					</div>
					<div class="web_session_pricing_table_row">
						<span class="web_session_pricing_table_entry web_session_pricing_table_left">3201-4300</span>
						<span class="web_session_pricing_table_entry web_session_pricing_bold"><span class="dollar_super">$</span>399</span>
					</div>
					<div class="web_session_pricing_table_row">
						<span class="web_session_pricing_table_entry web_session_pricing_table_left">4301-5400</span>
						<span class="web_session_pricing_table_entry web_session_pricing_bold"><span class="dollar_super">$</span>499</span>
					</div>
					<div class="web_session_pricing_table_row session_pricing_bottom">
						<span class="web_session_pricing_table_entry web_session_pricing_table_left">5401+</span>
						<span class="web_session_pricing_table_entry"><a href="/pages/contactus" class="pricing_blue_link">Contact Us</a></span>
					</div>
				</div>
			</div>
			<div class="web_session_pricing">
				<p class="web_session_pricing_head">PREMIUM</p>
				<div class="web_session_pricing_table">
					<div class="web_session_pricing_table_head">
						<span class="web_session_pricing_table_entry">MONTHLY SESSIONS</span>
						<span class="web_session_pricing_table_entry">PRICING</span>
					</div>
					<div class="web_session_pricing_table_row">
						<span class="web_session_pricing_table_entry web_session_pricing_table_left">1-1000</span>
						<span class="web_session_pricing_table_entry web_session_pricing_bold"><span class="dollar_super">$</span>149</span>
					</div>
					<div class="web_session_pricing_table_row">
						<span class="web_session_pricing_table_entry web_session_pricing_table_left">1001-2100</span>
						<span class="web_session_pricing_table_entry web_session_pricing_bold"><span class="dollar_super">$</span>249</span>
					</div>
					<div class="web_session_pricing_table_row">
						<span class="web_session_pricing_table_entry web_session_pricing_table_left">2101-3200</span>
						<span class="web_session_pricing_table_entry web_session_pricing_bold"><span class="dollar_super">$</span>349</span>
					</div>
					<div class="web_session_pricing_table_row">
						<span class="web_session_pricing_table_entry web_session_pricing_table_left">3201-4300</span>
						<span class="web_session_pricing_table_entry web_session_pricing_bold"><span class="dollar_super">$</span>449</span>
					</div>
					<div class="web_session_pricing_table_row">
						<span class="web_session_pricing_table_entry web_session_pricing_table_left">4301-5400</span>
						<span class="web_session_pricing_table_entry web_session_pricing_bold"><span class="dollar_super">$</span>549</span>
					</div>
					<div class="web_session_pricing_table_row session_pricing_bottom">
						<span class="web_session_pricing_table_entry web_session_pricing_table_left">5401+</span>
						<span class="web_session_pricing_table_entry"><a href="/pages/contactus" class="pricing_blue_link">Contact Us</a></span>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="web_dark">
	<div class="web_centered_content web_section_3">
		<table id="table_support_options">
			<tbody>
				<tr>
					<td id="table_head_monthly_pricing">
						<p class="table_head_text">
							FEATURES
						</p>
					</td>
					<td id="table_head_basic" class="table_support_head">
						<p class="table_head_text">BASIC</p>
						<p><span class="support_price_bold">Starting at $99/</span>Month</p>
					</td>
					<td id="table_head_premium" class="table_support_head">
						<p class="table_head_text">PREMIUM</p>
						<p><span class="support_price_bold">Starting at $149/</span>Month</p>
					</td>
					<td id="table_head_enterprise" class="table_support_head">
						<p class="table_head_text">ENTERPRISE</p>
						<p><a href="/pages/contactus" class="table_link_white">Contact Us</a></p>
					</td>
				</tr>
				<tr>
					<td class="table_options">PATENTED CO-BROWSING</td>
					<td class="table_inclusive">Included</td>
					<td class="table_inclusive">Included</td>
					<td class="table_inclusive">Included</td>
				</tr>
				<tr>
					<td class="table_options">SAMESURF START BUTTON</td>
					<td class="table_inclusive">Publisher*</td>
					<td class="table_inclusive">Publisher*</td>
					<td class="table_inclusive">Publisher*</td>
				</tr>
				<tr>
					<td class="table_options">SIMULTANEOUS SESSIONS</td>
					<td class="table_inclusive">Included</td>
					<td class="table_inclusive">Included</td>
					<td class="table_inclusive">Included</td>
				</tr>
				<tr>
					<td class="table_options">AUDIO &amp; VIDEO CHAT</td>
					<td class="table_inclusive">P2P WebRTC**</td>
					<td class="table_inclusive">P2P WebRTC**</td>
					<td class="table_inclusive">Premium WebRTC***</td>
				</tr>
				<tr>
					<td class="table_options">SUPPPORTED DOMAINS</td>
					<td class="table_inclusive">Single</td>
					<td class="table_inclusive">Multiple</td>
					<td class="table_inclusive">Multiple</td>
				</tr>
				<tr>
					<td class="table_options">PRODUCT SUPPORT</td>
					<td class="table_inclusive">Help Center</td>
					<td class="table_inclusive">Email Access</td>
					<td class="table_inclusive">Email + Phone****</td>
				</tr>
				<tr>
					<td class="table_options">ANALYTICS</td>
					<td class="table_inclusive">Simple</td>
					<td class="table_inclusive">Simple</td>
					<td class="table_inclusive">Advanced</td>
				</tr>
				<tr>
					<td class="table_options">SMS INVITES</td>
					<td class="table_inclusive"><span class="notincluded">Not Included</span></td>
					<td class="table_inclusive"><span class="notincluded">Not Included</span></td>
					<td class="table_inclusive">Included</td>
				</tr>
				<tr>
					<td class="table_options">CUSTOM BRANDING</td>
					<td class="table_inclusive"><span class="notincluded">Not Included</span></td>
					<td class="table_inclusive"><span class="notincluded">Not Included</span></td>
					<td class="table_inclusive">Included</td>
				</tr>
				<tr>
					<td class="table_options">FEATURE CUSTOMIZATION</td>
					<td class="table_inclusive"><span class="notincluded">Not Included</span></td>
					<td class="table_inclusive"><span class="notincluded">Not Included</span></td>
					<td class="table_inclusive">Included</td>
				</tr>
				<tr>
					<td class="table_options">DESIGNATED SERVER</td>
					<td class="table_inclusive"><span class="notincluded">Not Included</span></td>
					<td class="table_inclusive"><span class="notincluded">Not Included</span></td>
					<td class="table_inclusive">Included</td>
				</tr>
				<tr>
					<td class="table_options">ENHANCED  <a href="pages/forsupportandsales" class="table_blue_link">SLA</a></td>
					<td class="table_inclusive"><span class="notincluded">Not Included</span></td>
					<td class="table_inclusive"><span class="notincluded">Not Included</span></td>
					<td class="table_inclusive">Included</td>
				</tr>
			</tbody>
		</table>
		<div id="support_btn_wrap">
			<button id="support_basic_btn" class="support_buy_btn">BUY NOW</button>
			<button id="support_premium_btn" class="support_buy_btn">BUY NOW</button>
			<button id="support_enterprise_btn" class="support_buy_btn">CONTACT US</button>
		</div>
		<div id="web_table_astrix_text">
			<p><span class="text_astrix_bold">*</span> Publisher to include Visible Start Button on its Website using the Samesurf <a href="#" class="table_blue_link">API</a></p>
			<p><span class="text_astrix_bold">**</span> Peer-To-Peer WebRTC for Supported Browsers and Flash for Non-Supported Browsers</p>
			<p><span class="text_astrix_bold">***</span> Enterprise Grade WebRTC for Supported Browsers and Flash for Non-Supported Browsers</p>
			<p><span class="text_astrix_bold">****</span> Product Support Escalation to Live Help Requires $1000 Minimum Monthly Expenditure</p>
		</div>
		<div id="for_you">
			<p id="for_you_header">IS IT FOR YOU?</p>
			<div class="row">
				<div class="col-md-6">
					<a href="#"><img src="/static/images/browser_together_for_you.png" alt="Browse Together" /></a>
				</div>
				<div class="col-md-6">
					<ul id="for_you_bullets">
						<li><span class="color_bar bar_blue"></span><span class="color_text">Support Agents</span></li>
						<li><span class="color_bar bar_yellow"></span><span class="color_text">Connectors</span></li>
						<li><span class="color_bar bar_red"></span><span class="color_text">Sales Experts</span></li>
						<li><span class="color_bar bar_green"></span><span class="color_text">Video Viewers</span></li>
						<li><span class="color_bar bar_green"></span><span class="color_text">Web Shoppers</span></li>
						<li><span class="color_bar bar_red"></span><span class="color_text">Co-Travelers</span></li>
						<li><span class="color_bar bar_yellow"></span><span class="color_text">Tastemakers</span></li>
						<li><span class="color_bar bar_blue"></span><span class="color_text">Social Surfers</span></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>