<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addCSSFile("/static/css/pages/pricingindividual.css");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>

<div class="individual_light">
	<div class="individual_centered_content individual_section_1">
		<p id="individual_intro_head">SAMESURF FOR INDIVIDUALS</p>
	<a href="#"  class="enablesite" id="topdlbutton">HOW IT WORKS</a>
	</div>
</div>

<div class="individual_dark">
	<div class="support_centered_content">
		<table id="table_support_options">
			<tbody>
				<tr>
					<td id="table_head_monthly_pricing">
						<p class="table_head_text">
							FEATURES
						</p>
					</td>
					<td id="table_head_basic" class="table_support_head">
						<p class="table_head_text">DEMO</p>
						<p><span class="support_price_bold">Free</p>
					</td>
					<td id="table_head_premium" class="table_support_head">
						<p class="table_head_text">PREMIUM</p>
						<p><span class="support_price_bold">$10/</span>User/Month</p>
					</td>
					<td id="table_head_enterprise" class="table_support_head">
						<p class="table_head_text">ENTERPRISE</p>
						<p><a href="/pages/contactus" class="table_link_white">Contact Us</a></p>
					</td>
				</tr>
				<tr>
					<td class="table_options">PATENTED CO-BROWSING</td>
					<td class="table_inclusive">Included</td>
					<td class="table_inclusive">Included</td>
					<td class="table_inclusive">Included</td>
				</tr>
				<tr>
					<td class="table_options">SESSION DURATION</td>
					<td class="table_inclusive">5 minutes</td>
					<td class="table_inclusive">Unlimited</td>
					<td class="table_inclusive">Unlimited</td>
				</tr>
				<tr>
					<td class="table_options">AUDIO &amp; VIDEO CHAT</td>
					<td class="table_inclusive">P2P WebRTC*</td>
					<td class="table_inclusive">P2P WebRTC*</td>
					<td class="table_inclusive">Premium WebRTC**</td>
				</tr>
				<tr>
					<td class="table_options">PRODUCT SUPPORT</td>
					<td class="table_inclusive">Help Center</td>
					<td class="table_inclusive">Email Access</td>
					<td class="table_inclusive">Email + Phone***</td>
				</tr>
				<tr>
					<td class="table_options">SAMESLIDE PRESENTATIONS</td>
					<td class="table_inclusive">Demo</td>
					<td class="table_inclusive">Full Version</td>
					<td class="table_inclusive">Full Version</td>
				</tr>
				<tr>
					<td class="table_options">CLOUD STORAGE</td>
					<td class="table_inclusive"><span class="notincluded">Not Included</span></td>
					<td class="table_inclusive">1GB</td>
					<td class="table_inclusive">10GB</td>
				</tr>
				<tr>
					<td class="table_options">NO DISPLAY ADS</td>
					<td class="table_inclusive"><span class="notincluded">Not Included</span></td>
					<td class="table_inclusive">Included</td>
					<td class="table_inclusive">Included</td>
				</tr>
				<tr>
					<td class="table_options">SCREEN SHARING</td>
					<td class="table_inclusive"><span class="notincluded">Not Included</span></td>
					<td class="table_inclusive">Included****</td>
					<td class="table_inclusive">Included****</td>
				</tr>
				<tr>
					<td class="table_options">CUSTOM BRANDING</td>
					<td class="table_inclusive"><span class="notincluded">Not Included</span></td>
					<td class="table_inclusive"><span class="notincluded">Not Included</span></td>
					<td class="table_inclusive">Included</td>
				</tr>
				<tr>
					<td class="table_options">FEATURE CUSTOMIZATION</td>
					<td class="table_inclusive"><span class="notincluded">Not Included</span></td>
					<td class="table_inclusive"><span class="notincluded">Not Included</span></td>
					<td class="table_inclusive">Included</td>
				</tr>
				<tr>
					<td class="table_options">ANALYTICS</td>
					<td class="table_inclusive"><span class="notincluded">Not Included</span></td>
					<td class="table_inclusive"><span class="notincluded">Not Included</span></td>
					<td class="table_inclusive">Included</td>
				</tr>
				<tr>
					<td class="table_options">DESIGNATED SERVER</td>
					<td class="table_inclusive"><span class="notincluded">Not Included</span></td>
					<td class="table_inclusive"><span class="notincluded">Not Included</span></td>
					<td class="table_inclusive">Included</td>
				</tr>
				<tr>
					<td class="table_options">SMS INVITES</td>
					<td class="table_inclusive"><span class="notincluded">Not Included</span></td>
					<td class="table_inclusive"><span class="notincluded">Not Included</span></td>
					<td class="table_inclusive">Included</td>
				</tr>
				<tr>
					<td class="table_options">ENHANCED  <a href="pages/forsupportandsales" class="table_blue_link">SLA</a></td>
					<td class="table_inclusive"><span class="notincluded">Not Included</span></td>
					<td class="table_inclusive"><span class="notincluded">Not Included</span></td>
					<td class="table_inclusive">Included</td>
				</tr>
				<tr>
					<td class="table_options">SIMULTANEOUS SESSIONS</td>
					<td class="table_inclusive"><span class="notincluded">Not Included*****</span></td>
					<td class="table_inclusive"><span class="notincluded">Not Included*****</span></td>
					<td class="table_inclusive"><span class="notincluded">Not Included*****</span></td>
				</tr>
			</tbody>
		</table>
		<div id="support_btn_wrap">
			<button id="support_basic_btn" class="support_buy_btn">START DEMO</button>
			<button id="support_premium_btn" class="support_buy_btn">BUY NOW</button>
			<button id="support_enterprise_btn" class="support_buy_btn">CONTACT US</button>
		</div>
		<div id="table_astrix_text">
			<p><span class="astrix_bold">*</span> Peer-To-Peer WebRTC for Supported Browsers and Flash for Non-Supported Browsers</p>
			<p><span class="astrix_bold">**</span> Enterprise Grade WebRTC for Supported Browsers and Flash for Non-Supported Browsers</p>
			<p><span class="astrix_bold">***</span> Phone Support Escalation Requires a Minimum of 10 Monthly Users per Account</p>
			<p><span class="astrix_bold">****</span> Screen Sharing Only Functions on Certain Supported Browsers</p>
			<p><span class="astrix_bold">*****</span> Option Only Available on the <a href="/pages/forsupportandsales" class="table_blue_link">For Business</a> Category</p>
		</div>
		<div id="for_you">
			<p id="for_you_header">IS IT FOR YOU?</p>
			<div class="row">
				<div class="col-md-6">
					<div class="circle_icon">
						<a href="#"><img src="/static/images/circle_collab.png" alt="Collab" /></a>
					</div>
					<div class="circle_icon">
						<a href="#"><img src="/static/images/circle_meet.png" alt="Meet" /></a>
					</div>
					<div class="circle_icon">
						<a href="#"><img src="/static/images/circle_present.png" alt="Present" /></a>
					</div>
					<div class="circle_icon">
						<a href="#"><img src="/static/images/circle_learn.png" alt="Learn" /></a>
					</div>
					<div class="circle_icon">
						<a href="#"><img src="/static/images/circle_shop.png" alt="Shop" /></a>
					</div>
					<div class="circle_icon">
						<a href="#"><img src="/static/images/circle_book.png" alt="Book" /></a>
					</div>
				</div>
				<div class="col-md-6">
					<ul id="for_you_bullets">
						<li><span class="color_bar bar_blue"></span><span class="color_text">Web Shoppers</span></li>
						<li><span class="color_bar bar_yellow"></span><span class="color_text">Educators</span></li>
						<li><span class="color_bar bar_red"></span><span class="color_text">Professionals</span></li>
						<li><span class="color_bar bar_green"></span><span class="color_text">Schoolmates</span></li>
						<li><span class="color_bar bar_green"></span><span class="color_text">Consultants</span></li>
						<li><span class="color_bar bar_red"></span><span class="color_text">Online Friends</span></li>
						<li><span class="color_bar bar_yellow"></span><span class="color_text">Sales People</span></li>
						<li><span class="color_bar bar_blue"></span><span class="color_text">Creative Types</span></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
