<?php
$this->setTitle("samesurf");
$this->addCSSFile("/static/css/pages/privaterooms.css");
$this->addCSSFile("/static/css/pages/general.css");
$this->addJSFile("/static/js/pages/privaterooms.js");
$this->addJSFile("/static/js/pages/lazyload.js");
$this->addJSFile("/static/js/pages/animate.js");
$this->addCSSFile("/static/css/pages/lazyload.css");
$this->addCSSFile("/static/css/pages/animate.css");
?>
<div id="room_options">
	<div class="center_content">
		<div id="video_head">
			<div id="video_head_text">WATCH VIDEOS TOGETHER</div>
			<div id="start_room" class="blue_button">START OR JOIN A ROOM</div>
		</div>
	</div>
</div>
<div id="manual_search">
	<div class="center_content">
		<form id="publicrooms-start">
			<div class="info">
				SEARCH YOUTUBE OR ENTER VIMEO ADDRESSES
			</div>
			<div class="input-area">
				<input type="text" name="publicrooms-web-url" placeholder="http://" />
				<input type="submit" value="" />
			</div>
			<div id="search_youtube"></div>
			<div id="search_vimeo"></div>
		</form>
	</div>
</div>
<div class="video_list">
	<div class="or_container">
		<div class="or">
			OR
		</div>
	</div>
	<div class="center_content">
		<div class="section_header">
			JOIN AN ACTIVE ROOM
		</div>
		<div class="row clearfix">
			<div class="col-md-4">
				<div class="website_section">
					<div class="website_groups">
						<span class="website_group_header">SoCal Garage Rock <span>- 128 Followers</span></span>
						<span class="website_group_subheader">Host: <a href="#">JohnSmith</a></span>
					</div>
					<div class="website_row">
						<a href="http://www.amazon.com" id="amazon" class="website">
							<img src="/static/images/amazon.jpg" alt="Amazon" />
							<div class="generic_website_description">
								<span class="type url">URL</span>
								<span class="link">The Growlers - Full Album</span>
								<span class="timestamp">22:58</span>
							</div>
						</a>
					</div>
				</div>
			</div>

			<div class="col-md-4">
				<div class="website_section">
					<div class="website_groups">
						<span class="website_group_header">24/7 Beatles Playlist <span>- 41 Followers</span></span>
						<span class="website_group_subheader">Leader: <a href="#">Ringo</a></span>
					</div>
					<div class="website_row">
						<a href="http://www.priceline.com" id="priceline" class="website">
							<img src="/static/images/priceline.jpg" alt="Amazon" />
							<div class="generic_website_description">
								<span class="type url">URL</span>
								<span class="link">The Beatles - Blackbird</span>
								<span class="timestamp">22:58</span>
							</div>
						</a>
					</div>
				</div>
			</div>

			<div class="col-md-4">
				<div class="website_section">
					<div class="website_groups">
						<span class="website_group_header">CollegeHumor <span>- 41 Followers</span></span>
						<span class="website_group_subheader">Leader: <a href="#">Ringo</a></span>
					</div>
					<div class="website_row">
						<a href="http://espn.com" id="espn" class="website">
							<img src="/static/images/espn.jpg" alt="Amazon" />
							<div class="generic_website_description">
								<span class="type url">URL</span>
								<span class="link">What does human ...</span>
								<span class="timestamp">22:58</span>
							</div>
						</a>
					</div>
				</div>
			</div>
			<div class="col-md-4">
				<div class="website_section">
					<div class="website_groups">
						<span class="website_group_header">SoCal Garage Rock <span>- 128 Followers</span></span>
						<span class="website_group_subheader">Host: <a href="#">JohnSmith</a></span>
					</div>
					<div class="website_row">
						<a href="http://www.amazon.com" id="amazon" class="website">
							<img src="/static/images/amazon.jpg" alt="Amazon" />
							<div class="generic_website_description">
								<span class="type url">URL</span>
								<span class="link">The Growlers - Full Album</span>
								<span class="timestamp">22:58</span>
							</div>
						</a>
					</div>
				</div>
			</div>

			<div class="col-md-4">
				<div class="website_section">
					<div class="website_groups">
						<span class="website_group_header">24/7 Beatles Playlist <span>- 41 Followers</span></span>
						<span class="website_group_subheader">Leader: <a href="#">Ringo</a></span>
					</div>
					<div class="website_row">
						<a href="http://www.priceline.com" id="priceline" class="website">
							<img src="/static/images/priceline.jpg" alt="Amazon" />
							<div class="generic_website_description">
								<span class="type url">URL</span>
								<span class="link">The Beatles - Blackbird</span>
								<span class="timestamp">22:58</span>
							</div>
						</a>
					</div>
				</div>
			</div>

			<div class="col-md-4">
				<div class="website_section">
					<div class="website_groups">
						<span class="website_group_header">CollegeHumor <span>- 41 Followers</span></span>
						<span class="website_group_subheader">Leader: <a href="#">Ringo</a></span>
					</div>
					<div class="website_row">
						<a href="http://espn.com" id="espn" class="website">
							<img src="/static/images/espn.jpg" alt="Amazon" />
							<div class="generic_website_description">
								<span class="type url">URL</span>
								<span class="link">What does human ...</span>
								<span class="timestamp">22:58</span>
							</div>
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="video_list">
	<div class="or_container">
		<div class="or">
			OR
		</div>
	</div>
	<div class="center_content">
		<div class="section_header">
			VIEW POPULAR VIDEOS
		</div>
		<div class="row clearfix">
			<div class="col-md-4">
				<div class="website_section">
					<div class="website_row">
						<a href="http://www.amazon.com" id="amazon" class="website">
							<img src="/static/images/amazon.jpg" alt="Amazon" />
							<div class="generic_website_description">
								<span class="type url">URL</span>
								<span class="link">The Growlers - Full Album</span>
								<span class="timestamp">22:58</span>
							</div>
						</a>
					</div>
				</div>
			</div>

			<div class="col-md-4">
				<div class="website_section">
					<div class="website_row">
						<a href="http://www.priceline.com" id="priceline" class="website">
							<img src="/static/images/priceline.jpg" alt="Amazon" />
							<div class="generic_website_description">
								<span class="type url">URL</span>
								<span class="link">The Beatles - Blackbird</span>
								<span class="timestamp">22:58</span>
							</div>
						</a>
					</div>
				</div>
			</div>

			<div class="col-md-4">
				<div class="website_section">
					<div class="website_row">
						<a href="http://espn.com" id="espn" class="website">
							<img src="/static/images/espn.jpg" alt="Amazon" />
							<div class="generic_website_description">
								<span class="type url">URL</span>
								<span class="link">What does human ...</span>
								<span class="timestamp">22:58</span>
							</div>
						</a>
					</div>
				</div>
			</div>
			<div class="col-md-4">
				<div class="website_section">
					<div class="website_row">
						<a href="http://www.amazon.com" id="amazon" class="website">
							<img src="/static/images/amazon.jpg" alt="Amazon" />
							<div class="generic_website_description">
								<span class="type url">URL</span>
								<span class="link">The Growlers - Full Album</span>
								<span class="timestamp">22:58</span>
							</div>
						</a>
					</div>
				</div>
			</div>

			<div class="col-md-4">
				<div class="website_section">
					<div class="website_row">
						<a href="http://www.priceline.com" id="priceline" class="website">
							<img src="/static/images/priceline.jpg" alt="Amazon" />
							<div class="generic_website_description">
								<span class="type url">URL</span>
								<span class="link">The Beatles - Blackbird</span>
								<span class="timestamp">22:58</span>
							</div>
						</a>
					</div>
				</div>
			</div>

			<div class="col-md-4">
				<div class="website_section">
					<div class="website_row">
						<a href="http://espn.com" id="espn" class="website">
							<img src="/static/images/espn.jpg" alt="Amazon" />
							<div class="generic_website_description">
								<span class="type url">URL</span>
								<span class="link">What does human ...</span>
								<span class="timestamp">22:58</span>
							</div>
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>