<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/publicroomsinfo.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/publicroomsinfo.js");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>
	<div id="content0">
		<div class="centredcontent">
			
			<div id=content0title><div class="mediumheader">HOW VIDEO SHARING WORKS</div></div>
			<a href="#" class="enablesite" id="topdlbutton">VISIT PUBLICROOMS.COM</a>
						
		</div>	
	</div>	
	
	<div id="content1">
		<div class="centredcontent">
			<div id="content1title"><div class="mediumheader">NO INSTALLS REQUIRED</div></div>
						
			<div class="content1text"><div class="alltext">Integer posuere erat a ante venenatis dapibus <br/>
			posuere velit aliquet. Cras justo odio, dapibus ac <br/>
			facilisis in, egestas eget quam. Donec ullamcorper <br/>
			nulla non metus auctor fringilla. Aenean eu leo <br/>
			quam. Pellentesque ornare sem lacinia quam.</div></div>
				<div id="content1image"></div>
		</div>
	</div>	
	
		
	
	<div id="content2">
		<div class="centredcontent">
			<div id="content2title"><div class="mediumheader">FEATURES</div></div>
				<div id="grid2">
					<div class="iconsq1">
						<div id="icon1"></div>
					</div>
					
					<div class="iconsq2">
						<div id="icon2"></div>
					</div>
					
					<div class="iconsq3">
						<div id="icon3"></div>
					</div>
					
					<div class="iconsq4">
						<div id="icon4"></div>
					</div>
					
					<div class="iconsq5">
						<div id="icon5"></div>
					</div>
				</div>		
			
		</div>
	</div>	
	
	<div id="content3">
		<div class="centredcontent">
			<div id="content3title"><div class="mediumheader">PLAY. PAUSE. SKIP. TOGETHER</div></div>
						
			<div class="content3text"><div class="alltext">Integer posuere erat a ante venenatis dapibus <br/>
			posuere velit aliquet. Cras justo odio, dapibus ac <br/>
			facilisis in, egestas eget quam. Donec ullamcorper <br/>
			nulla non metus auctor fringilla. Aenean eu leo <br/>
			quam. Pellentesque ornare sem lacinia quam.</div></div>
				<div id="content3image"></div></div>
		</div>
	</div>
	
	<div id="content4">
		<div class="centredcontent">
			<div id="content4image"></div>
				<div id="content4title"><div class="mediumheader">ANY BROWSER. ANY DEVICE.</div></div>
						
			<div class="content4text"><div class="alltext">Samesurf is a cross platform experience that <br/>
			enables real-time sharing across virtually every <br/>
			computer, smartphone or tablet. If you’re <br/>
			sharing	videos from a mobile device, you can <br/>
			even lead others through the process of picking <br/>
			starting and auto-synching videos.</div></div>
		</div>
	</div>	
	
	<div id="content5">
		<div class="centredcontent">
			<div id="content5title"><div class="mediumheader">YOUTUBE & VIMEO INTEGRATION</div></div>
						
			<div class="content5text"><div class="alltext">For Youtube videos, simply search for a term <br/>
			like the name, subject or artist via our <br/>
			integrated search box. For Vimeo videos, simply <br/>
			copy & paste the web address from Vimeo.com <br/>
			into the input box and click Enter.</div></div>
				<div id="content5image"></div>
		</div>
	</div>	s
		