<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/remotecontrol.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/remotecontrol.js");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>
	<div id="content0">
		<div class="centredcontent">
			
			<div id=content0title><div class="mediumheader">REMOTE CONTROL</div></div>
			<div id="content0text">Remotely control screens across the globe from any</br>device without additional hardware or coding.</div>
			<a href="#" class="enablesite" id="topdlbutton">DEMO SAMESURF</a>
			<div id="remotecontrolimage"></div>
			
		</div>	
	</div>	
	
	<div id="content1">
		<div class="centredcontent">
			<div id="content1title"><div class="mediumheader">WHY USE SAMESURF FOR REMOTE CONTROL?</div></div>
				<div id="grid">
					<div class="bulletbox">
						<div class="bulletptblue"></div>
					Beam mobile content from small to large screens
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptorange"></div>
					Eliminate hardware and installation requirements
					</div>
					
					<div class="bulletbox">
						<div class="bulletptred"></div>
					Interact with remote devices from any location
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptgreen"></div>
					Play online content for users that span the globe 
					</div>
					
					<div class="bulletbox">
						<div class="bulletptgreen"></div>
					Eliminate the need to toggle into HDMI mode
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptred"></div>
					Achieve synced video viewing across platforms 
					</div>
					
					<div class="bulletbox">
						<div class="bulletptorange"></div>
					Connect enabled appliances to a single device
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptblue"></div>
					Control any web-enabled device from your mobile
					</div>
				</div>
		
		</div>
	</div>
	
		
	
	<div id="content2">
		<div class="centredcontent">
			<div id="content2title"><div class="mediumheader">FEATURES</div></div>
				<div id="grid2">
				<a href="/pages/features#content1" class="iconsq1">
					<div id="icon1"></div>
				</a>

				<a href="/pages/features#content6" class="iconsq2">
					<div id="icon2"></div>
				</a>

				<a href="/pages/features#content4" class="iconsq3">
					<div id="icon3"></div>
				</a>

				<a href="/pages/features#content12" class="iconsq4">
					<div id="icon4"></div>
				</a>

				<a href="/pages/features#content8" class="iconsq5">
					<div id="icon5"></div>
				</a>
			</div>		
			
		</div>
	</div>	
	
	<div id="content3">
		<div class="centredcontent">
			<div id="assistedsalesvid">
					<iframe src="//player.vimeo.com/video/77007215?title=0&amp;byline=0&amp;portrait=0" 
					width="917" height="516" allowfullscreen></iframe>
			</div>
			
		</div>
	</div>	
	
	<div id="content4">
		<div class="centredcontent">
			<div id="content4image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/connectedrooms.png" /></div>
				<div id="content4title"><div class="mediumheader">CONNECT ROOMS WITHOUT HARDWARE</div></div>
						
			<div class="content4text"><div class="alltext">Utilize desktop and mobile devices to control smart appliances<br/>
throughout the home or office from anywhere in the world.</div></div>
		</div>
	</div>	
	
	<div id="content5">
		<div class="centredcontent">
			<div id="content5title"><div class="mediumheader">CREATE INSTANT NETWORKS</div></div>
						
			<div class="content5text"><div class="alltext">Leverage computers, phones or tablets to create<br/>
web sharing networks without the expense and <br/>
effort of setting up traditional networks.</div></div>
				<div id="content5image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/screens.png" /></div>
		</div>
	</div>


