<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/safariosxdl.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/safariosxdl.js");
?>
	<div id="content0">
		<div class="centredcontent">
			<div id="downloadtitle">
				<div id="logo"></div>
				<div id=content0title><div class="mediumheader">SAFARI DOWNLOAD INSTRUCTIONS</div></div>
			</div>			
		</div>	
	</div>	
	
	<div id="content1">
		<div class="centredcontent">
				
	
			<div class="content"><div class="alltext">After downloading, copy and paste this link into the address line within samesurf to join:<br/>
			<a href="http://i.samesurf.com/79012">http://i.samesurf.com/79012</a><br/><br/>
			Or just enter <a href="http://i.samesurf.com/79012">79012</a> after clicking the samesurf button.
			</div></div>
		</div>
	</div>

	<div id="content2">
		<div class="centredcontent">
			<div class="instructiongroup">
				<div id="circle1">1</div>
				<div id="text1"><div class="alltext">Once you click the download button, the process will automatically begin in the top portion of 
				your browser and the indicator will let you know how you're doing.</div></div>
			</div>
			<div id="image1"></div>
		
			<div class="instructiongroup">
				<div id="circle2">2</div>
				<div id="text2"><div class="alltext">After the download is complete, please click on "Downloads" in the upper right hand part of 
				your screen and double click on the samesurf.dmg file you downloaded.</div></div>
			</div>
			<div id="image1a"></div>
			
			<div class="instructiongroup">
				<div id="circle3">3</div>
				<div id="text3"><div class="alltext">Once you've reviewed the samesurf Terms of Service and everything is in order please click "Agree" to continue.</div></div>
			<div id="image2"></div>
			</div>
			
			<div class="instructiongroup">
				<div id="circle4">4</div>
				<div id="text4"><div class="alltext">Once you've selected "Agree," you will see a .dmg window open up on your desktop.  Within that 
				window, please drag the samesurf icon into your Applications folder.</div></div>
			<div id="image3"></div>
			</div>
			
			<div class="instructiongroup">
				<div id="circle5">5</div>
				<div id="text5"><div class="alltext">Once you've dragged samesurf into your Applications folder, please open up your Applications 
				folder and double click on the application entitled "samesurf."</div></div>
			<div id="image4"></div>
			</div>
			
			<div class="instructiongroup">
				<div id="circle6">6</div>
				<div id="text6"><div class="alltext">After double clicking on "samesurf," a window will pop up that will ask you whether you're sure 
				that you want to open samesurf.  If everything is in order, please press "Open."</div></div>
			<div id="image5"></div>
			</div>
			
			<div class="instructiongroup">
				<div id="circle7">7</div>
				<div id="text7"><div class="alltext">After you click "Open," samesurf will automatically launch on your desktop.</div></div>
			</div>
			
			<div class="instructiongroup">
				<div id="circle8">8</div>
				<div id="text8"><div class="alltext">After downloading, cut and paste <a href="http://i.samesurf.com/i/79012">http://i.samesurf.com/i/79012</a>
				 into the address line within samesurf to rejoin or just reenter room <a href="http://i.samesurf.com/i/79012">79012</a>
				  after clicking the start samesurf button.</div></div>
				<div id="image6"></div>
				<div id="image7"></div>
				<div id="image8"></div>
				<div id="image9"></div>
			</div>
		
			
				
		
		</div>	
	</div>
		
	
