<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/sales.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/sales.js");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>
	<div id="content0">
		<div class="centredcontent">
			
			<div id=content0title><div class="mediumheader">ASSISTED SALES</div></div>
			<div id="content0text"><div class="alltext">Simulate the in-store experience within the virtual realm<br/>
			by putting customers and agents on the same page.</div></div>				
			<a href="#" id="topdlbutton" class="enablesite">DEMO SAMESURF</a>
			<div id="salesimage"></div>
			
		</div>	
	</div>	
	
	<div id="content1">
		<div class="centredcontent">
			<div id="content1title"><div class="mediumheader">WHY USE SAMESURF FOR ASSISTED SALES?</div></div>
				<div id="grid">
					<div class="bulletbox">
						<div class="bulletptblue"></div>
					Enhanced conversion, upsell and cross-sell rates 
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptorange"></div>
					Flexible assisted selling platform for all industries
					</div>
					
					<div class="bulletbox">
						<div class="bulletptred"></div>
					Instant elevation of customer satisfaction levels
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptgreen"></div>
					Sizable reduction in shopping cart abandonment 
					</div>
					
					<div class="bulletbox">
						<div class="bulletptgreen"></div>
					Support for buyer decisions at point of purchase
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptred"></div>
					Elevated visitor return and customer referral rates
					</div>
					
					<div class="bulletbox">
						<div class="bulletptorange"></div>
					Cross platform functionality without any installs
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptblue"></div>
					Simple integration into existing software systems
					</div>
				</div>
		
		</div>
	</div>
	
		
	
	<div id="content2">
		<div class="centredcontent">
			<div id="content2title"><div class="mediumheader">FEATURES</div></div>
				<div id="grid2">
				<a href="/pages/features#content1" class="iconsq1">
					<div id="icon1"></div>
				</a>

				<a href="/pages/features#content6" class="iconsq2">
					<div id="icon2"></div>
				</a>

				<a href="/pages/features#content4" class="iconsq3">
					<div id="icon3"></div>
				</a>

				<a href="/pages/features#content12" class="iconsq4">
					<div id="icon4"></div>
				</a>

				<a href="/pages/features#content8" class="iconsq5">
					<div id="icon5"></div>
					</a>
			</div>		
			
		</div>
	</div>	
	
	<div id="content3">
		<div class="centredcontent">
					<div id="assistedsalesvid">
					<iframe src="//player.vimeo.com/video/77007215?title=0&amp;byline=0&amp;portrait=0" 
					width="917" height="516" allowfullscreen></iframe>
			</div>
			
		</div>
	</div>	
	
<div id="content4">
	<div class="centredcontent">
		<div id="content4image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/converting.png" /></div>
		<div id="content4title"><div class="mediumheader">INCREASED CONVERSIONS</div></div>

		<div class="content4text"><div class="alltext">
			Samesurf increases conversion and user<br/>
			satisfaction rates by immersing agents<br/> 
			directly into the customer experience.<br/></div></div>
	</div>
</div>	
	
	<div id="content5">
		<div class="centredcontent">
			<div id="content5title"><div class="mediumheader">FULL CUSTOMIZATION</div></div>
						
			<div class="content5text"><div class="alltext">Our solutions enable customization of the<br/>
features, messaging and themes for each<br/>
experience to fit individual requirements.<br/>
    </div></div>
				<div id="content5image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/customsidebar.png" /></div>
		</div>
	</div>	