<?php
$this->setTitle("samesurf");
$this->addCSSFile("/static/css/pages/search.css");
$this->addCSSFile("/static/css/pages/general.css");
$this->addJSFile("/static/js/pages/search.js");
$this->addJSFile("/static/js/pages/lazyload.js");
$this->addJSFile("/static/js/pages/animate.js");
$this->addCSSFile("/static/css/pages/lazyload.css");
$this->addCSSFile("/static/css/pages/animate.css");
?>
<div id="content0">
	<div class="centredcontent">

		<div id=content0title><div class="mediumheader">SEARCH TOGETHER</div></div>
		<div id="content0text"><div class="alltext">Make web searching collaborative by co-browsing<br/> 
			multiple engines from a single experience.</div></div>				
		<a href="#" id="topdlbutton" class="enablesite">DEMO SAMESURF</a>
		<div id="searchimage"></div>

	</div>	
</div>	

<div id="content1">
	<div class="centredcontent">
		<div id="content1title"><div class="mediumheader">WHY USE SAMESURF TO SEARCH TOGETHER?</div></div>
		<div id="grid">
			<div class="bulletbox">
				<div class="bulletptblue"></div>
				Collaborative searches for products and services  
			</div>

			<div class="bulletbox2">
				<div class="bulletptorange"></div>
				Simultaneous shopping supports multiple users  
			</div>

			<div class="bulletbox">
				<div class="bulletptred"></div>
				Diminished necessity to share multiple page links
			</div>

			<div class="bulletbox2">
				<div class="bulletptgreen"></div>
				Viewing online media together on every website 
			</div>

			<div class="bulletbox">
				<div class="bulletptgreen"></div>
				Instant input from collaborators during searches 
			</div>

			<div class="bulletbox2">
				<div class="bulletptred"></div>
				Ability to experience all forms of content together
			</div>

			<div class="bulletbox">
				<div class="bulletptorange"></div>
				Seamless shared booking for travel arrangements
			</div>

			<div class="bulletbox2">
				<div class="bulletptblue"></div>
				Tandem search on virtually any device or browser
			</div>
		</div>

	</div>
</div>



<div id="content2">
	<div class="centredcontent">
		<div id="content2title"><div class="mediumheader">FEATURES</div></div>
		<div id="grid2">
			<a href="/pages/features#content1" class="iconsq1">
					<div id="icon1"></div>
				</a>

				<a href="/pages/features#content6" class="iconsq2">
					<div id="icon2"></div>
				</a>

				<a href="/pages/features#content4" class="iconsq3">
					<div id="icon3"></div>
				</a>

				<a href="/pages/features#content12" class="iconsq4">
					<div id="icon4"></div>
				</a>

				<a href="/pages/features#content8" class="iconsq5">
					<div id="icon5"></div>
				</a>
		</div>		

	</div>
</div>	

<div id="content3">
	<div class="centredcontent">
		<div id="assistedsalesvid">
			<iframe src="//player.vimeo.com/video/77007215?title=0&amp;byline=0&amp;portrait=0" 
					width="917" height="516" allowfullscreen></iframe>
		</div>

	</div>
</div>	

<div id="content4">
	<div class="centredcontent">
		<div id="content4image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/syncedsearch.png" /></div>
		<div id="content4title"><div class="mediumheader">CO-SEARCH ACROSS SITES</div></div>

		<div class="content4text"><div class="alltext">Experience co-browse ready searches<br/> 
across services like Google and Bing<br/>
within a simple and instant platform.</div></div>
	</div>
</div>	

<div id="content5">
	<div class="centredcontent">
		<div id="content5title"><div class="mediumheader">SEAMLESS COLLABORATION</div></div>

		<div class="content5text"><div class="alltext">Transform web searching into a true collaboration<br/> 
			by unleashing lightning fast co-browsing.</div></div>
		<div id="content5image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/collab.png" /></div>
	</div>
</div>	

