<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/secondaryuses.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/secondaryuses.js");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>
	<div id="content0">
		<div class="centredcontent">
			
			<div id=content0title><div class="mediumheader">SECONDARY USES</div></div>
				<a href="#" id="topdlbutton" class="enablesite">DEMO SAMESURF</a>
								
		</div>	
	</div>	
	
	<div id="content1">
		<div class="centredcontent">
			<div id="content1title"><div class="mediumheader">EDUCATION</div></div>
						
			<div class="content1text"><div class="alltext">Share collaborative activities ranging from<br>joint research to classroom simulations for<br>enhanced distance learning.<br></div>
			<a href="/pages/education">Learn More</a></div>
				<div class="bluecircle">
					<div id="icon01"></div>
				</div>
		</div>
	</div>	
	
	<div id="content2">
		<div class="centredcontent">
			<div class="greencircle">
				<div id="icon02"></div>
			</div>
			
			<div id="content2title"><div class="mediumheader">HEALTH CARE</div></div>
			<div class="content2text"><div class="alltext">Enhance patient care through privacy<br>conscious tools
for collaboration with<br>medical and insurance information. <br></div>
			<a href="/pages/medical">Learn More</a></div>
				
		</div>
	</div>
	
		<div id="content5">
		<div class="centredcontent">
			<div id="content5title"><div class="mediumheader">SEARCH TOGETHER</div></div>
						
			<div class="content5text"><div class="alltext">Transform search into a true collaboration<br>by co-browsing
		all of the search engines<br>together from a single source.<br></div>
			<a href="/pages/search">Learn More</a></div>
				<div class="yellowcircle">
					<div id="icon05"></div>
				</div>
		</div>
	</div>	
	
		<div id="content6">
		<div class="centredcontent">
			<div class="purplecircle">
				<div id="icon06"></div>
			</div>
			
			<div id="content6title"><div class="mediumheader">MARKET RESEARCH</div></div>
			<div class="content6text"><div class="alltext">Achieve major cost efficiencies and deeper<br>insights by leveraging
more diverse sample<br>sets to conduct market research online.<br></div>
			<a href="/pages/marketresearch">Learn More</a></div>
				
		</div>
	</div>
	
	<div id="content7">
		<div class="centredcontent">
			<div id="content7title"><div class="mediumheader">BROWSER TESTING</div></div>
						
			<div class="content7text"><div class="alltext">Conduct install-free compatibility testing<br>to preview projects on multiple browsers<br>and devices at the same time.<br></div>
			<a href="/pages/browsertesting">Learn More</a></div>
				<div class="redcircle">
					<div id="icon07"></div>
				</div>
		</div>
	</div>
	
	<div id="content8">
		<div class="centredcontent">
			<div class="pinkcircle">
				<div id="icon08"></div>
			</div>
			
			<div id="content8title"><div class="mediumheader">USABILITY TESTING</div></div>
			<div class="content8text"><div class="alltext">Conduct effective usability testing by using<br>diverse response pools to garner enhanced<br>resource efficiencies and deeper insights.<br></div>
			<a href="/pages/usabilitytesting">Learn More</a></div>
				
		</div>
	</div>	
	

