<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/security.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/security.js");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>
	<div id="content0">
		<div class="centredcontent">
			
			<div id=content0title><div class="mediumheader">SECURITY</div></div>
			<a href="/pages/workflow" id="topdlbutton" class="enablesite">PREVIEW OUR PATENTED TECHNOLOGY</a>
			
		</div>
	</div>
	
	<div id="content1">
		<div class="centredcontent">
			<div class="content1text"><div class="alltext">
				Samesurf promotes security via built-in features <br/>
				such as TLS/SSL encryption, single tab browser <br/>
				sharing and field blocking for sensitive entries.  <br/>
				<a class="bluebutton" href="/pages/workflow">Preview our Patented Technology</a>
				</div></div>
				<div id="content1image"></div>
		</div>
	</div>
	
	<div id="content2">
		<div class="centredcontent">
			<div id="content2title"><div class="mediumheader">KEY FEATURES</div></div>
				<div id="grid">
					<div class="bulletbox">
						<div class="bulletptblue"></div>
					No code placement requirements of any kind
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptorange"></div>
					Restriction of view access to a single browser tab
					</div>
					
					<div class="bulletbox">
						<div class="bulletptred"></div>
					Blocking of sensitive input entries like passwords
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptgreen"></div>
					Shared browsing without exposing the desktop
					</div>
					
					<div class="bulletbox">
						<div class="bulletptgreen"></div>
					Secure co-browsing for authenticated websites
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptred"></div>
					Ability to limit co-browsing to subset of domains
					</div>
					
					<div class="bulletbox">
						<div class="bulletptorange"></div>
					Co-browsing without data storage or processing</div>
					
					<div class="bulletbox2">
						<div class="bulletptblue"></div>
					Integration that doesn't affect existing processes 
					</div>
				</div>
		
		</div>
	</div>
	
		
	<div id="content3">
		<div class="centredcontent">
			<div id="content3image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/sslicon.png" /></div>
				<div id="content3title"><div class="mediumheader">TLS/SSL ENCRYPTION</div></div>
						
			<div class="content3text"><div class="alltext">Encryption safeguards transmitted data<br/> 
while ensuring complete compliance with<br/> 
enterprise grade security requirements.<br/></div></div>
		</div>
	</div>	
	
	<div id="content4">
		<div class="centredcontent">
			<div id="content4title"><div class="mediumheader">PRIVATE INPUT FIELD BLOCKING</div></div>
						
			<div class="content4text"><div class="alltext">Field blocking of sensitive input entries like passwords<br/> 
safeguards user privacy during co-browse sessions.</div></div>
				<div id="content4image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/fieldblock.png" /></div>
		</div>
	</div>	
	
	<div id="content5">
		<div class="centredcontent">
			<div id="content5image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/singletabshare.png" /></div>
				<div id="content5title"><div class="mediumheader">SINGLE TAB SHARING</div></div>
						
			<div class="content5text"><div class="alltext">Our offerings restrict sharing to a single<br/>browser tab with the option of toggling<br/> 
into screen sharing for offline content.<br/></div></div>
		</div>
	</div>		


