<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/services.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/services.js");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>
	<div id="content0">
		<div class="centredcontent">
			
			<div id=content0title><div class="mediumheader">SERVICES</div></div>				
				<div id="content0text"><div class="alltext">Samesurf provides a full suite of professional services<br/> 
that support custom features and app integrations. </div></div>
			<div id="servicesimage"></div>
			
		</div>	
	</div>	
	
	<div id="content1">
		<div class="centredcontent">
			<div id="content1title"><div class="mediumheader">WHY USE SAMESURF SERVICES?</div></div>
				<div id="grid">
					<div class="bulletbox">
						<div class="bulletptblue"></div>
						<p>
							Eliminated need to employ web designers and developers to complete Samesurf integrations.
						</p>
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptorange"></div>
					<p>Bespoke customization of features, messaging and design elements for the user experience.</p>
					</div>
					
					<div class="bulletbox">
						<div class="bulletptred"></div>
					<p>Assistance with integration into third party solutions like Live Chat and Virtual Worlds.</p>
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptgreen"></div>
					<p>Direction on tight integrations into existing web experiences and desktop or mobile applications. </p>
					</div>
				</div>
		
		</div>
	</div>
	
	<div id="content2">
		<div class="centredcontent">
			<div id="content2title"><div class="mediumheader">SITE INTEGRATION</div></div>
			
			<div class="content2text"><div class="alltext">Professional engineering services performed<br/>
			by our development team ensure seamless implementations the very first time.<br/>
			<a href="http://www.samesurf.com"><div class="bluebutton">Contact our Services Department</div></a></div></div>
				
			<div id="content2image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/sgllineintegration.png" /></div>
		</div>
	</div>	
	
	<div id="content3">
		<div class="centredcontent">
			<div id="content3image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/customsidebar.png" /></div>
				<div id="content3title"><div class="mediumheader">SPECIAL CUSTOMIZATION</div></div>
						
			<div class="content3text"><div class="alltext">
				Our developers can create custom<br/>features and UI elements to match<br/>divergent uses and requirements.  
			</div></div>
		</div>
	</div>
	
	<div id="content5">
		<div class="centredcontent">
			<div id="content5image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/appsync.png" /></div>
				<div id="content5title"><div class="mediumheader">CUSTOM APP INTEGRATIONS</div></div>
						
			<div class="content5text"><div class="alltext">
				Our engineering staff assists with seamless integrations into third party experiences and applications for desktop or mobile devices.
				</div>
			</div>
		</div>
	</div>	
		