<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/shop.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/shop.js");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>
	<div id="content0">
		<div class="centredcontent">
			
			<div id=content0title><div class="mediumheader">SHOP TOGETHER</div></div>
			<div id="content0text"><div class="alltext">Promote shared experiences by enabling visitors to</br>shop together with friends and trusted experts.</div></div>
			<a href="#" id="topdlbutton" class="enablesite">DEMO SAMESURF</a>
			<div id="shopimage"></div>
			
		</div>	
	</div>	
	
	<div id="content1">
		<div class="centredcontent">
			<div id="content1title"><div class="mediumheader">WHY USE SAMESURF TO SHOP TOGETHER?</div></div>
				<div id="grid">
					<div class="bulletbox">
						<div class="bulletptblue"></div>
					Ability to browse among multiple shopping sites
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptorange"></div>
					Communicating with friends through built-in chat
					</div>
					
					<div class="bulletbox">
						<div class="bulletptred"></div>
					Control sharing promotes active user participation 
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptgreen"></div>
					Seamless co-browsing without installs or latency
					</div>
					
					<div class="bulletbox">
						<div class="bulletptgreen"></div>
					Mouse tracking that trails each cursor in real-time
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptred"></div>
					Instant invites via email, social chat and mobile
					</div>
					
					<div class="bulletbox">
						<div class="bulletptorange"></div>
					Integrated social networks promote viral sharing</div>
					
					<div class="bulletbox2">
						<div class="bulletptblue"></div>
					Instant feedback from trusted circles of advisors
					</div>
				</div>
		
		</div>
	</div>
	
		
	
<div id="content2">
	<div class="centredcontent">
		<div id="content2title"><div class="mediumheader">FEATURES</div></div>
		<div id="grid2">
			<a href="/pages/features#content1" class="iconsq1">
				<div id="icon1"></div>
			</a>

			<a href="/pages/features#content6" class="iconsq2">
				<div id="icon2"></div>
			</a>

			<a href="/pages/features#content4" class="iconsq3">
				<div id="icon3"></div>
			</a>

			<a href="/pages/features#content12" class="iconsq4">
				<div id="icon4"></div>
			</a>

			<a href="/pages/features#content8" class="iconsq5">
				<div id="icon5"></div>
			</a>
		</div>		
			
		</div>
	</div>	
	
	<div id="content3">
		<div class="centredcontent">
			<div id="assistedsalesvid">
					<iframe src="//player.vimeo.com/video/77007215?title=0&amp;byline=0&amp;portrait=0" 
					width="917" height="516" allowfullscreen></iframe>
			</div>
			
		</div>
	</div>	
	
	<div id="content4">
		<div class="centredcontent">
			<div id="content4image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/insights.png" /></div>
				<div id="content4title"><div class="mediumheader">INSTANT FEEDBACK</div></div>
						
			<div class="content4text"><div class="alltext">Gain instant input on purchasing decisions<br/> 
from friends, family and live experts while<br/>browsing through products and services.</div></div>
		</div>
	</div>	
	
	<div id="content5">
		<div class="centredcontent">
			<div id="content5title"><div class="mediumheader">SHOP WITH FRIENDS</div></div>
						
			<div class="content5text"><div class="alltext">Redefine traditional notions of sharing<br/>by leveraging tools that promote shared<br/>interactions which occur in real-time.</div></div>
				<div id="content5image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/evangelists.png" /></div>
		</div>
	</div>	



