<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/ss_vs_screenshare.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/ss_vs_screenshare.js");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>	
	<div id="intro">
		<div class="centredcontent">
			<div class="title">
				<div class="mediumheader">SAMESURF vs. SCREENSHARING</div>
			</div>
			
			<div id="introtext">
				<div class="alltext">Samesurf co-browsing holds multiple advantages over<br/>applications that rely on 
			traditional screen sharing. 
				</div>
			</div>
			
			<div id="assistedsalesvid">
					<iframe src="//player.vimeo.com/video/77007215?title=0&amp;byline=0&amp;portrait=0" 
					width="917" height="520" frameborder="0" webkitallowfullscreen mozallowfullscreen 
					allowfullscreen></iframe>
			</div>	
		</div>
	</div>	
	
	<div id="maincontent">		
		<div class="centredcontent">
			
						
			<div id="grid">	
				<div id="samesurf">
					SAMESURF
				</div>
				<div class="contenttitle">
					<div class="mediumheader">
						WAIT TIMES
					</div>
				</div>
				<div id="screenshare">
					SCREEN SHARING
				</div>
					<div class="contentbox">
						<div class="contentboxtext"><div class="ssvssstext">Spans a two second average entry time for leaders and followers. For online support, samesurf only requires a single click for room initiation.
						</div></div>
					</div>
					
					<div class="samesurfsq">s</div>
					
					<div class="screensharesq">ss</div>
						
					<div class="contentbox2">
						<div class="contentboxtext"><div class="ssvssstext">Spans a thirty second average entry time on the leader
						side and a twenty second average entry time on the follower side to allow for required installs.
						</div></div>
					</div>
					
				<div class="contenttitle"><div class="mediumheader">INSTALLS</div></div>
				
					<div class="contentbox">
						<div class="contentboxtext"><div class="ssvssstext">Co-browsing requires no installs. Flash is required only for site-based audio and video chat. Java is required on Windows for screen sharing on the presenter side only while Macs require a one-time install for screen sharing. 
						</div></div>
					</div>
					
					<div class="samesurfsq">s</div>
					
					<div class="screensharesq">ss</div>
						
					<div class="contentbox2">
						<div class="contentboxtext"><div class="ssvssstext">Most screen sharing solutions require some form of install such as a full download or java-based applet on the leader side and a separate download, install or 
plugin on the follower side.<br/><br/>
						</div></div>
					</div>
					
				
				
				<div class="contenttitle"><div class="mediumheader">OPEN WINDOWS</div></div>
				
					<div class="contentbox">
						<div class="contentboxtext"><div class="ssvssstext">Requires no extraneous browser windows or tabs to remain open while co-browsing occurs directly on 
shared websites throughout the web.
						</div></div>
					</div>
					
					<div class="samesurfsq">s</div>
					
					<div class="screensharesq">ss</div>
						
					<div class="contentbox2">
						<div class="contentboxtext"><div class="ssvssstext">The majority of screen sharing solutions require that 
a separate browser window or application remain open for screen sharing to remain active. 
						</div></div>
					</div>
					
				
				
				<div class="contenttitle"><div class="mediumheader">MULTI-WAY INTERACTIVITY</div></div>
				
					<div class="contentbox">
						<div class="contentboxtext"><div class="ssvssstext">Supports the ability for all users to simultaneously interact with shared content in real-time to perform tasks such as joint form filling and control passing.
						</div></div>
					</div>
					
					<div class="samesurfsq">s</div>
					
					<div class="screensharesq">ss</div>
						
					<div class="contentbox2">
						<div class="contentboxtext"><div class="ssvssstext">Screen sharing solutions only enable the presenter 
to navigate and enter data within input fields while followers are only able to view the presenter screen.
						</div></div>
					</div>
			
				
				<div class="contenttitle"><div class="mediumheader">LATENCY</div></div>
				
					<div class="contentbox">
						<div class="contentboxtext"><div class="ssvssstext">Encounters minimal or no latency since shared content 
is independently loaded by each user. Co-browsing renders equally well on all screen types.<br/><br/>
						</div></div>
					</div>
					
					<div class="samesurfsq">s</div>
					
					<div class="screensharesq">ss</div>
						
					<div class="contentbox2">
						<div class="contentboxtext"><div class="ssvssstext">Screen sharing manifests lag and fuzzy rendering 
due to the constant encoding and decoding requirements and heavy CPU, GPU and bandwidth utilization.
						</div></div>
					</div>
					
				
				
				<div class="contenttitle"><div class="mediumheader">SYSTEM REQUIREMENTS</div></div>
				
					<div class="contentbox">
						<div class="contentboxtext"><div class="ssvssstext">Achieves screen coordination via the passing of tiny bits of data between browsers which results in low bandwidth utilization and effective content sharing even on less robust devices.<br/><br/>
						</div></div>
					</div>
					
					<div class="samesurfsq">s</div>
					
					<div class="screensharesq">ss</div>
						
					<div class="contentbox2">
						<div class="contentboxtext"><div class="ssvssstext">Constant encoding and decoding for screen sharing requires high bandwidth utilization which often 
causes choppiness and uneven rendering on the majority of systems and bandwidth connections.
						</div></div>
					</div>
					
				
				
				<div class="contenttitle"><div class="mediumheader">SCREEN MASKING AND USER PRIVACY</div></div>
				
					<div class="contentbox">
						<div class="contentboxtext"><div class="ssvssstext">Screen masking is not necessary since only a single tab is being shared. Sensitive text input entries like passwords and credit cards are programmatically blocked from being visible to followers during co-browse sessions.  
						</div></div>
					</div>
					
					<div class="samesurfsq">s</div>
					
					<div class="screensharesq">ss</div>
						
					<div class="contentbox2">
						<div class="contentboxtext"><div class="ssvssstext">Certain screen sharing solutions employ brute force masking of extraneous desktop elements to promote user privacy. These techniques can't effectively decipher which sensitive input fields require masking on shared pages.
						</div></div>
					</div>
					
			
				
				<div class="contenttitle"><div class="mediumheader">PASSING CONTROL</div></div>
				
					<div class="contentbox">
						<div class="contentboxtext"><div class="ssvssstext">Integrates seamless passing of controls by leaders and single click control requests for followers.<br/><br/>
						</div></div>
					</div>
					
					<div class="samesurfsq">s</div>
					
					<div class="screensharesq">ss</div>
						
					<div class="contentbox2">
						<div class="contentboxtext"><div class="ssvssstext">Passing controls usually requires several steps and inhibits the continuity and fluidity of the shared experience. 
						</div></div>
					</div>
					
				
				
				<div class="contenttitle"><div class="mediumheader">CROSS PLATFORM INTEROPERABILITY</div></div>
				
					<div class="contentbox">
						<div class="contentboxtext"><div class="ssvssstext">Functions seamlessly without installs across all of the major browsers and on virtually every computer, tablet, smartphone and web enabled appliance.
						</div></div>
					</div>
					
					<div class="samesurfsq">s</div>
					
					<div class="screensharesq">ss</div>
						
					<div class="contentbox2">
						<div class="contentboxtext"><div class="ssvssstext">Screen sharing functions well on most computers but renders poorly or not at all on mobile devices due to the high CPU, GPU and bandwidth utilization requirements.  
						</div></div>
					</div>
					
				
				
				<div class="contenttitle"><div class="mediumheader">AUDIO AND VIDEO CONTENT SHARING</div></div>
				
					<div class="contentbox">
						<div class="contentboxtext"><div class="ssvssstext">Audio and video content is shareable at the same quality that users would experience that content if they were watching or listening to it on their own.
						</div></div>
					</div>
					
					<div class="samesurfsq">s</div>
					
					<div class="screensharesq">ss</div>
						
					<div class="contentbox2">
						<div class="contentboxtext"><div class="ssvssstext">Screen sharing solutions don't promote effective real-time sharing of audio and video content due to technical restraints such as frame rate limitations.  

						</div></div>
					</div>
					
					
				
				<div class="contenttitle"><div class="mediumheader">SCREEN DRAWING</div></div>
				
					<div class="contentbox">
						<div class="contentboxtext"><div class="ssvssstext">Integrates seamless ability for multiple users to 
draw and erase their screen markings in real-time.<br/><br/>
						</div></div>
					</div>
					
					<div class="samesurfsq">s</div>
					
					<div class="screensharesq">ss</div>
						
					<div class="contentbox2">
						<div class="contentboxtext"><div class="ssvssstext">Screen sharing solutions do not offer this feature as collaborative screen drawing is unique to samesurf.
						</div></div>
					</div>
					
				
				
				<div class="contenttitle"><div class="mediumheader">CURSOR TRACKING</div></div>
				
					<div class="contentbox">
						<div class="contentboxtext"><div class="ssvssstext">Supports ability for all participants to track each other's mouse movements in real-time while leader movements are simulated via auto-scrolling.
						</div></div>
					</div>
					
					<div class="samesurfsq">s</div>
					
					<div class="screensharesq">ss</div>
						
					<div class="contentbox2">
						<div class="contentboxtext"><div class="ssvssstext">Most screen sharing solutions support the ability for followers to only view the leader's mouse movements while moving within pages causes screen distortion.
						</div></div>
					</div>
					
				
				
				<div class="contenttitle"><div class="mediumheader">DATA SECURITY</div></div>
				
					<div class="contentbox">
						<div class="contentboxtext"><div class="ssvssstext">All data tranmissions are protected with SSL encryption while sensitive input fields are never made viewable to followers. Co-browsing is supported for both http and https environments.
						</div></div>
					</div>
					
					<div class="samesurfsq">s</div>
					
					<div class="screensharesq">ss</div>
						
					<div class="contentbox2">
						<div class="contentboxtext"><div class="ssvssstext">Some screen sharing solutions promote data security by limiting screen sharing to https environments and by encrypting the broadcast transmission of the presenter's screen elements.
						</div></div>
					</div>
					
				
				
				<div class="contenttitle"><div class="mediumheader">MAXIMUM NUMBER OF USERS</div></div>
				
					<div class="contentbox">
						<div class="contentboxtext"><div class="ssvssstext">Supports and has successfully tested 5000 simultaneous users in a single room sharing content across 5 continents without enduring installs or latency.   
						</div></div>
					</div>
					
					
					<div class="samesurfsq">s</div>
					
					<div class="screensharesq">ss</div>
						
					<div class="contentbox2">
						<div class="contentboxtext"><div class="ssvssstext">Most screen sharing solutions support a much smaller number of users due to the CPU, GPU and bandwidth requirements related to these processes.
						</div></div>
					</div>
					
				
				
				<div class="contenttitle"><div class="mediumheader">PERSONALIZED CONTENT</div></div>
				
					<div class="contentbox">
						<div class="contentboxtext"><div class="ssvssstext">Can support personalized content and clickable ads 
for every co-browse participant in a group session.
						</div></div>
					</div>
					
					<div class="samesurfsq">s</div>
					
					<div class="screensharesq">ss</div>
						
					<div class="contentbox2">
						<div class="contentboxtext"><div class="ssvssstext">Allows followers only to observe the presenter's screen which includes non-clickable ads only relevant to one side.
						</div></div>
					</div>
					
		</div>	
	</div>	
	

