<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/support.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/support.js");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>
	<div id="content0">
		<div class="centredcontent">
			
			<div id=content0title><div class="mediumheader">ONLINE SUPPORT</div></div>
			<div id="content0text"><div class="alltext">Samesurf enables agents to provide exceptional<br/> 
support without enduring installs or delays.</div></div>			
			<a href="#" id="topdlbutton" class="enablesite">DEMO SAMESURF</a>
			<div id="supportimage"></div>
			
		</div>	
	</div>	
	
	<div id="content1">
		<div class="centredcontent">
			<div id="content1title"><div class="mediumheader">WHY USE SAMESURF FOR ONLINE SUPPORT?</div></div>
				<div id="grid">
					<div class="bulletbox">
						<div class="bulletptblue"></div>
					Significant reduction in support resolution times
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptorange"></div>
					Marked increase in first call issue resolution rates
					</div>
					
					<div class="bulletbox">
						<div class="bulletptred"></div>
					Elevated rates for conversions, cross and upsells
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptgreen"></div>
					Seamless, install-free platform for online support
					</div>
					
					<div class="bulletbox">
						<div class="bulletptgreen"></div>
					Educational tool promotes customer self-service 
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptred"></div>
					Heightened user security versus screen sharing
					</div>
					
					<div class="bulletbox">
						<div class="bulletptorange"></div>
					Seamless functionality across virtually all devices</div>
					
					<div class="bulletbox2">
						<div class="bulletptblue"></div>
					Simple integration into third party solutions
					</div>
				</div>
		
		</div>
	</div>
	
		
	
	<div id="content2">
		<div class="centredcontent">
			<div id="content2title"><div class="mediumheader">FEATURES</div></div>
			<div id="grid2">
				<a href="/pages/features#content1" class="iconsq1">
					<div id="icon1"></div>
				</a>

				<a href="/pages/features#content6" class="iconsq2">
					<div id="icon2"></div>
				</a>

				<a href="/pages/features#content4" class="iconsq3">
					<div id="icon3"></div>
				</a>

				<a href="/pages/features#content12" class="iconsq4">
					<div id="icon4"></div>
				</a>

				<a href="/pages/features#content8" class="iconsq5">
					<div id="icon5"></div>
				</a>
			</div>		
			
		</div>
	</div>	
	
	<div id="content3">
		<div class="centredcontent">
		<div id="assistedsalesvid">
					<iframe src="//player.vimeo.com/video/77007215?title=0&amp;byline=0&amp;portrait=0" 
					width="917" height="516" allowfullscreen></iframe>
			</div>
			
		</div>
		</div>
	<div id="content4">
		<div class="centredcontent">
			<div id="content4image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/instfreesupport.png" /></div>
				<div id="content4title"><div class="mediumheader">ONLINE SUPPORT REIMAGINED</div></div>
						
			<div class="content4text"><div class="alltext">Our solution is the first patented offering to immerse agents into the user experience so they're able to offer assistance in real-time.</div></div>
		</div>
	</div>	
	
	<div id="content5">
		<div class="centredcontent">
			<div id="content5title"><div class="mediumheader">SHOW AND TELL FOR THE MODERN AGE</div></div>
						
			<div class="content5text"><div class="alltext">Samesurf empowers agents to take the wheel and visually</br>lead customers through effective support solutions.</div></div>
				<div id="content5image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/showtell.png" /></div>
		</div>
	</div>	