<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/team.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/team.js");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>
	
	<div id="content1">
		<div class="centredcontent">
			<div id="samesurfvideo">
			<iframe src="//player.vimeo.com/video/53180842?title=0&amp;byline=0&amp;portrait=0" width="917" height="520" allowfullscreen></iframe>
			</div>
			
			<div id="content1title"><div class="mediumheader">ABOUT SAMESURF</div></div>
			<div id="content1text"><div class="alltext">Samesurf is an install-free co-browsing platform that enables multiple people to share their<br/>
				browsing experiences in real-time from virtually any device or browser. Our suite of products<br/> 
				transcend alternatives like screen sharing in terms of simplicity, security and performance.
			</div></div>
			
			<a href="/pages/boardofadvisors" id="topdlbutton" class="enablesite">VIEW ADVISORS</a>
			
		</div>
	</div>	
	
	
	<div id="content2">		
		<div class="centredcontent2">
			<div class="title"><div class="mediumheader">CO-FOUNDERS</div></div>
					
					<div class="contentbox">
						<div class="contentboxtitle">K. DAVID PIRNAZAR</div>
						<a href="http://www.linkedin.com/in/davidpirnazar" target="_blank"><div class="linkedinlogo"></div></a>
						<div id="logo1"></div>
						<div class="downarrow"></div>
						<div class="contentboxsubtitle">Co-Founder/CEO</div>
						<div class="contentboxtext"><div class="alltext">
						David Pirnazar is the Co-Founder, CEO and an investor in samesurf/Actual Worlds, Inc. 
						("samesurf") with ultimate responsibility for managing all aspects of the Company's 
						development and business pursuits. Prior to co-founding samesurf, he served as the 
						Founder and President of Epic Vids, Inc., an interactive publisher that developed video 
						games with partnered publishers and development studios in the interactive gaming space. 
						In the console arena, Mr. Pirnazar conceived and executive produced console and mobile 
						games such as Fear and Respect for Midway Games and Warner Brothers Interactive (PlayStation 3, 
						XBOX 360, PC, Handheld, and Mobile). Within this role, he served as an early entrant into the 
						mobile apps space and was among the first to recruit, negotiate and include in-world ads and 
						product placements within interactive products. Most recently, Mr. Pirnazar conceived and 
						developed a Unity-based application for Nike's Empire Tested brand. <br/><br/>

						Within the mobile apps space, Mr. Pirnazar co-founded Zen Interactive, LLC, a wireless game 
						and application publisher ("Zen"). He started Zen with the founder of the University of Southern 
						California Video Game Program and the president of a wireless game and application development 
						studio named Blue Label Interactive ("Blue Label"). At Zen, Mr. Pirnazar developed wireless games, 
						apps and related digital products that incorporated readily identifiable brands such as entertainment 
						and sports personalities. Zen entered into numerous license agreements with prominent partners such as 
						Viacom to develop a slew of mobile game properties. The company was sold to the remaining principals of 
						Blue Label in conjunction with the sale of Blue Label to Konami (NYSE: KNM) in June of 2006. <br/><br/>

						Mr. Pirnazar has also served as a transactional attorney with Mayer, Brown, Rowe & Mawe and Russ, August 
						& Kabat. He received his B.S. degree in finance and marketing from the University of Southern California, 
						graduating magna cum laude. Mr. Pirnazar received his J.D. from the University of Southern California 
						School of Law and is an active member of the California Bar.
						</div></div>
						
					</div>
						
					<div class="contentbox">
						<div class="contentboxtitle">JERRY A. GREENBERG</div>
						<a href="http://www.linkedin.com/pub/jerry-greenberg/2b/267/124" target="_blank">
							<div class="linkedinlogo">
							</div>
						</a>
						<div id="logo2"></div>
						<div class="downarrow"></div>
						<div class="contentboxsubtitle">Co-Founder</div>
						<div class="contentboxtext"><div class="alltext">
						Jerry A. Greenberg is the Co-Founder and an investor in samesurf. Prior to co-founding the company, 
						Mr. Greenberg also co-founded Sapient (NASDAQ: SAPE) in 1991 and served as Co-Chairman of the Board 
						of Directors and Co-Chief Executive Officer of the company until 2006. He rejoined Sapient's Board in 
						October 2010 and was elected as Co-Chairman of the Board in June 2012. <br/><br/>

						Mr. Greenberg and J. Stuart Moore started Sapient to pioneer a fundamentally different approach to 
						business and technology consulting. This approach delivered business and advanced technology solutions 
						that resulted in high-value, measurable business results - on time and on budget. During his tenure with 
						the company, he was at the forefront of many noteworthy changes in the industry that have affected the 
						way businesses and consumers engage with each other.  Mr. Greenberg led Sapient during the emergence of 
						the Internet and e-commerce and guided the company through a number of acquisitions, beginning in 1998, 
						that laid the foundation for the fusion of deep technology skills and rich creativity that characterizes 
						much of the company's work for clients today.   Along with Moore, Mr. Greenberg was also instrumental 
						in developing Sapient's vision and values and the company's unique approach to achieving dramatic results 
						for clients. <br/><br/>

						Since leaving Sapient in 2006, Greenberg has been part of the founding of three privately held companies, 
						two in which he serves as a strategic adviser and one as chief executive officer.  Mr. Greenberg graduated 
						from Harvard University with a degree in economics. 
						</div></div>
						
					</div>
	
					
				<div class="title"><div class="mediumheader" style="margin-top: -50px;">CORE TEAM</div></div>
				
				<div id="grid">	
					<div class="contentbox">
						<div class="contentboxtitle">ADAM FLAHERTY</div>
						<a href="http://uk.linkedin.com/pub/adam-flaherty/10/770/98" target="_blank">
							<div class="linkedinlogo">
							</div>
						</a>
						<div class="samesurflogo"></div>
						<div class="downarrow"></div>
						<div class="contentboxsubtitle">Chief Technology Officer</div>
						<div class="contentboxtext"><div class="alltext">Adam Flaherty is the Company's Chief Technology 
						Officer with primary responsibility for all development activities related to the
						Company's offerings. His expertise lies in the development of web applications 
						and their corresponding server side implementations. Specifically, Mr. Flaherty 
						has extensive experience with the following technology platforms: C/C++, Objective 
						C, Cocoa, C#, Open GL, Open AL, Java, J2EE, VB.NET, Adobe Flex, PHP, Perl, Javascript, 
						XML/XSD, Ajax, Linux, Unix, Z/OS, Mac OS X, Windows, Oracle, DB2, MySQL, Apache, Nginx, 
						IIS and Tomcat. Prior to joining samesurf, he was Development Manager for Liz Earle UK 
						(acquired by Avon) where he managed two development teams comprising of 14 developers and 
						design specialists. Prior to Liz Earle, Mr. Flaherty held high level development and managerial 
						roles at Integritie and The Met Office.</div></div>
					</div>
					
					<div class="contentbox">
						<div class="contentboxtitle">TYLER TARR</div>
						<a href="http://www.linkedin.com/pub/tyler-tarr/20/34a/34a" target="_blank">
							<div class="linkedinlogo">
							</div>
						</a>
						<div class="samesurflogo"></div>
						<div class="downarrow"></div>
						<div class="contentboxsubtitle">Chief Financial Officer</div>
						<div class="contentboxtext"><div class="alltext">
						Tyler Tarr is the Company's Chief Financial Officer with primary responsibility for the 
						development of its financial plans, business models, and monetization pursuits. Mr. Tarr 
						brings extensive financial and operational experience in a wide array of environments, from 
						early stage high technology companies to large multinational manufacturing enterprises. He 
						formerly held senior financial and operational positions at a variety of companies including 
						CFO for Brilliant Digital Entertainment (a publicly traded content distribution and peer-to-peer 
						technology company), Astro Business Solutions, Inc. (a wholly-owned subsidiary of Canon USA), 
						Packard Bell NEC Electronics, Inc. and EMI Music Worldwide. <br/><br/>

						During his career, Mr. Tarr has been involved in the analysis, structuring and negotiating of 
						secured financing transactions aggregating over $1.5 billion. In addition, he has successfully 
						helped design, negotiate and implement the integration of several acquisitions, including the 
						acquisition of SBK Records and Chrysalis Records while at EMI Music, the acquisition of Zenith 
						Data Systems and the North American PC operation of NEC while at Packard Bell. For the past five 
						years, Mr. Tarr has provided mergers and acquisitions advisory services to middle market clients 
						including the purchase of NEC's European PC operations, a company with sales in excess of $1 billion, 
						and subsequent sale to Acer, and the take private of InFocus, a projector company with sales in 
						excess of $200 million. Mr. Tarr earned his CPA while employed by the leading public accounting 
						firms of Arthur Andersen, LLC and Coopers & Lybrand, LLC.
						</div></div>
					</div>
					
					<div class="contentbox">
						<div class="contentboxtitle">RUSSELL FLAHERTY</div>
						<a href="http://www.linkedin.com/pub/russell-flaherty/67/271/1aa" target="_blank">
							<div class="linkedinlogo">
							</div>
						</a>
						<div class="samesurflogo"></div>
						<div class="downarrow"></div>
						<div class="contentboxsubtitle">Lead Developer</div>
						<div class="contentboxtext"><div class="alltext">Russell Flaherty is the Company's Lead Developer 
						with responsibility for programming and developing front end user interactions. Prior to joining 
						samesurf, he served as a Product Support Engineer at Brett Martin Daylight Systems. Mr. Flaherty 
						received his BEng in Mechanical Engineering from Coventry University.
						</div></div>
					</div>
					
					<div class="contentbox">
						<div class="contentboxtitle">FARZIN AGHAIPOUR</div>
						<div class="samesurflogo"></div>
						<div class="downarrow"></div>
						<div class="contentboxsubtitle">VP of Business Development</div>
						<div class="contentboxtext"><div class="alltext">Farzin Aghaipour is the Company's Vice President of 
						Business Development with responsibility for originating partnerships with publishers and prospective 
						business partners with an initial focus on companies in the travel and hospitality industries. Prior 
						to joining samesurf, he served as Vice President of Acquisitions and Chief Operating Officer of Santa 
						Monica Hotel Management, an owner and developer of several properties including the Huntley Hotel Santa 
						Monica Beach. Mr. Aghaipour currently sits on the Board of Directors of Transom Capital. He earned his 
						BA degree in political science from the University of California at Los Angeles and holds a Masters in 
						Real Estate Development (MRED) from the University of Southern California.
						</div></div>
					</div>
					
					<div class="contentbox">
						<div class="contentboxtitle">LUCAS KRIEBEL</div>
						<a href="http://www.linkedin.com/pub/lucas-kriebel/35/a3b/b43" target="_blank">
							<div class="linkedinlogo">
							</div>
						</a>
						<div class="samesurflogo"></div>
						<div class="downarrow"></div>
						<div class="contentboxsubtitle">Lead Designer</div>
						<div class="contentboxtext"><div class="alltext">Lucas Kriebel is the Company's Lead Designer with 
						responsibility for driving the direction of samesurf's 
						visual elements for user interface and graphical design. 
						Prior to joining samesurf, he co-founded and served as 
						a principal for IMK Creative Group, a design</div></div>
					</div>
					
					<div class="contentbox">
						<div class="contentboxtitle">FIONA FLAHERTY</div>
						<a href="http://uk.linkedin.com/pub/fiona-flaherty/44/617/b19/" target="_blank">
							<div class="linkedinlogo">
							</div>
						</a>
						<div class="samesurflogo"></div>
						<div class="downarrow"></div>
						<div class="contentboxsubtitle">Lead Software Tester</div>
						<div class="contentboxtext"><div class="alltext">Fiona Flaherty is the Company's Lead Software Tester
						with responsibility for testing samesurf's functionality
						across all platforms both manually and using automated test
						tools. She is also responsible for areas of Front End development and support. 
						Prior to joining samesurf, she held testing and support
						roles at Airborne Interactive, Cobweb Solutions and Rank Holidays.</div></div>
						
					</div>
					
					
				</div>	
		</div>	
	</div>	
