<?php
$this->setTitle("samesurf");
$this->addCSSFile("/static/css/pages/technology.css");
$this->addCSSFile("/static/css/pages/general.css");
$this->addJSFile("/static/js/pages/technology.js");
$this->addJSFile("/static/js/pages/lazyload.js");
$this->addJSFile("/static/js/pages/animate.js");
$this->addCSSFile("/static/css/pages/lazyload.css");
$this->addCSSFile("/static/css/pages/animate.css");
?>
<div id="content0">
	<div class="centredcontent">

		<div id=content0title><div class="mediumheader">TECHNOLOGY</div></div>
		<a href="/pages/workflow" id="topdlbutton" class="enablesite">PREVIEW OUR PATENTED TECHNOLOGY</a>		
		<div id="technologyimage"></div>

	</div>	
</div>	

<div id="content1">
	<div class="centredcontent">
		<div id="content1title"><div class="mediumheader">KEY POINTS</div></div>
		<div id="grid">
			<div class="bulletbox">
				<div class="bulletptblue"></div>
				Install-free co-browsing through the entire web
			</div>

			<div class="bulletbox2">
				<div class="bulletptorange"></div>
				Instant syncing of page elements without coding 
			</div>

			<div class="bulletbox">
				<div class="bulletptred"></div>
				Cutting edge speed, security and functionalities
			</div>

			<div class="bulletbox2">
				<div class="bulletptgreen"></div>
				Shared browsing of PDF content without installs
			</div>

			<div class="bulletbox">
				<div class="bulletptgreen"></div>
				Audio and video chat with parallel co-browsing
			</div>

			<div class="bulletbox2">
				<div class="bulletptred"></div>
				Co-browsing through every device and browser
			</div>

			<div class="bulletbox">
				<div class="bulletptorange"></div>
				Built-in screen sharing for offline collaboration </div>

			<div class="bulletbox2">
				<div class="bulletptblue"></div>
				Pixel-perfect mouse tracking and screen drawing
			</div>
		</div>

	</div>
</div>


<div id="content4">
	<div class="centredcontent">
		<div id="content2title"><div class="mediumheader">THE NEXT GENERATION OF SHARED BROWSING</div></div>
		<div id="content4image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/screenshare90s.png" /></div>
		<div id="content4subtitle"><div class="mediumheader">SCREEN SHARING <span>(1990s)</span></div></div>

		<div class="content4text"><div class="alltext">Fuzzy Screens<br/>
			Slow Rendering<br/>
			Resource Intensive<br/>
			Install Requirements<br/>
			Ineffective on Mobile<br/>
			One-Way Interactivity</div></div>
	</div>
</div>	

<div id="content3">
	<div class="centredcontent">
		<div id="content3subtitle"><div class="mediumheader">LEGACY CO-BROWSING <span>(2000)</span></div></div>

		<div class="content3text"><div class="alltext">Required Installations<br/>
			Constant Page Rebuilds<br/>
			Limited Across Platforms<br/>
			Ineffective on Modern Sites<br/>
			Lack of Personalized Content<br/>
			Inoperable on Mobile Devices</div></div>
		<div id="content3image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/legacy.png" /></div>
	</div>
</div>	

<div id="content2">
	<div class="centredcontent">
		<div id="content2image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/cobrowse2013.png" /></div>
		<div id="content2subtitle"><div class="mediumheader">SAMESURF <span>(TODAY)</span></div></div>

		<div class="content2text"><div class="alltext">No Installs<br/>
			Crystal Clear<br/>
			Lightning Fast<br/> 
			Cross Platform<br/>
			No Coding Required<br/>
			Multi-Way Interactivity<br/>
			</div>
		</div>	
	</div>
</div>


