<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addCSSFile("/static/css/pages/tour_pricing.css");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>


<div id="pricing_content">
	<div id="pricing_options_table">
		<div class="pricing_options_tablecell">
			<div class="pricing_option_box">
				<p class="pricing_box_head">FOR INDIVIDUALS</p>
				<p class="pricing_cost_text">Starting <span>$10/</span>month</p>
				<div class="pricing_circle">
					<div id="pricing_individual_img" class="pricing_circle_img"></div>
				</div>
				<p class="pricing_description_text">Use Samesurf in your Everyday</p>
				<p class="pricing_description_text">Work and Personal Life</p>
				<a href="/pages/forindividuals" id="pricing_indivdual_btn" class="pricing_button">Start Now</a>
			</div>
		</div>
		<div class="pricing_options_tablecell">
			<div class="pricing_option_box">
				<p class="pricing_box_head">FOR SUPPORT &amp; SALES</p>
				<p class="pricing_cost_text">Starting <span>$49/</span>month</p>
				<div class="pricing_circle">
					<div id="pricing_support_img" class="pricing_circle_img"></div>
				</div>
				<p class="pricing_description_text">Integrate Samesurf for Install-Free</p>
				<p class="pricing_description_text">Support and Assisted Selling</p>
				<a href="/pages/forsupportandsales" id="pricing_support_btn" class="pricing_button">Start Now</a>
			</div>
		</div>
		<div class="pricing_options_tablecell">
			<div class="pricing_option_box">
				<p class="pricing_box_head">FOR WEBSITES</p>
				<p class="pricing_cost_text">Starting <span>$99/</span>month</p>
				<div class="pricing_circle">
					<div id="pricing_websites_img" class="pricing_circle_img"></div>
				</div>
				<p class="pricing_description_text">Add Samesurf to your Website and</p>
				<p class="pricing_description_text">Socialize the User Experiance</p>
				<a href="/pages/forsiteintegration" id="pricing_websites_btn" class="pricing_button">Start Now</a>
			</div>
		</div>
	</div>
</div>
