<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/tour_features.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/tour_features.js");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>
<div id="titlebar">
	<div class="centredcontent">
		<div class="tour-btn-left">
			<a href="/pages/tour_different"><i class="fa fa-arrow-left"></i> Back: We're Different</a>
		</div>
		<div id="titlebartable">
			<div id=content0title><div class="mediumheader">FEATURES</div></div>
		</div>
		<div class="tour-btn-right">
			<a href="/pages/tour_howitworks">Next: How It Works <i class="fa fa-arrow-right"></i></a>
		</div>
	</div>	
</div>	

	<div id="content1">
		<div class="centredcontent">
			<div id="content1title"><div class="mediumheader">CO-BROWSING</div></div>
						
			<div class="content1text"><div class="alltext">Browse the web together in <br/>
real-time from virtually any <br/>device or browser.   </div></div>
				<div id="content1image"><img src="/static/images/pages/featcobrowsing.png" alt="Image" class="show-img" /></div>
		</div>
	</div>	
	
	<div id="content2">
		<div class="centredcontent">
			<div id="content2image"><img src="/static/images/pages/featmousetrack.png" alt="Image" class="show-img" /></div>
				<div id="content2title"><div class="mediumheader">MOUSE TRACKING</div></div>
						
			<div class="content2text"><div class="alltext">Track each other's cursors as you<br/>
			auto-scroll to follow the leader's movements within each page.</div></div>
		</div>
	</div>	
	
	<div id="content3">
		<div class="centredcontent">
			<div id="content3title"><div class="mediumheader">SCREEN DRAWING</div></div>
						
			<div class="content3text"><div class="alltext">Collaborate and guide one another<br/>
			by sharing your screen markings on<br/>each webpage and the whiteboard.</div></div>
				<div id="content3image"><img src="/static/images/pages/featscreendraw.png" alt="Image" class="show-img" /></div>
		</div>
	</div>	
	
	<div id="content4">
		<div class="centredcontent">
			<div id="content4image"><img src="/static/images/pages/feataudvidchat.png" alt="Image" class="show-img" /></div>
				<div id="content4title"><div class="mediumheader">AUDIO & VIDEO CHAT</div></div>
						
			<div class="content4text"><div class="alltext">Enhance the shared experience by<br/>
			leveraging webRTC technology for<br/>install-free audio and video chat.</div></div>
		</div>
	</div>	
	
	<div id="content5">
		<div class="centredcontent">
			<div id="content5title"><div class="mediumheader">SOCIAL INTEGRATION</div></div>
						
			<div class="content5text"><div class="alltext">Exchange social messages, posts <br/>
			and invites from a single place as <br/>
			you browse the web together. </div></div>
				<div id="content5image"><img src="/static/images/pages/featsocialint.png" alt="Image" class="show-img" /></div>
		</div>
	</div>	
	
	<div id="content6">
		<div class="centredcontent">
			<div id="content6image"><img src="/static/images/pages/featscreenshare.png" alt="Image" class="show-img" /></div>
				<div id="content6title"><div class="mediumheader">SCREEN SHARING</div></div>
						
			<div class="content6text"><div class="alltext">Toggle into screen sharing for<br/>applications and offline content<br/>
			that reside on your desktop.</div></div>
		</div>
	</div>	
	
	<div id="content7">
		<div class="centredcontent">
			<div id="content7title"><div class="mediumheader">UPLOAD & SHARE</div></div>
						
			<div class="content7text"><div class="alltext">Upload presentations to the cloud<br/>
			and drive others through each slide<br/>
			 without installs from any device.</div></div>
				<div id="content7image"><img src="/static/images/pages/featupload.png" alt="Image" class="show-img" /></div>
		</div>
	</div>	
	
	<div id="content8">
		<div class="centredcontent">
			<div id="content8image"><img src="/static/images/pages/featsecurity.png" alt="Image" class="show-img" /></div>
				<div id="content8title"><div class="mediumheader">SECURITY</div></div>
						
			<div class="content2text"><div class="alltext">Safeguard data via TLS encryption,<br/> 
input field blocking and by limiting<br/>shared browsing to a single tab.</div></div>
		</div>
	</div>	
	
	<div id="content9">
		<div class="centredcontent">
			<div id="content9title"><div class="mediumheader">AUTHENTICATED SHARING</div></div>
						
			<div class="content9text"><div class="alltext">Co-browse sites that require logins<br/>like
			Facebook and Dropbox with people you trust and know well.</div></div>
				<div id="content9image"><img src="/static/images/pages/featacctsharing.png" alt="Image" class="show-img" /></div>
		</div>
	</div>	
	
	<div id="content10">
		<div class="centredcontent">
			<div id="content10image"><img src="/static/images/pages/featanalytics.png" alt="Image" class="show-img" /></div>
				<div id="content10title"><div class="mediumheader">ANALYTICS</div></div>
						
			<div class="content2text"><div class="alltext">Garner valuable insights on site usage<br/>
			to develop products that better reflect<br/>your users' patterns and preferences.</div></div>
		</div>
	</div>	
	
		<div id="content11">
		<div class="centredcontent">
			<div id="content11title"><div class="mediumheader">TEXT CHAT</div></div>
						
			<div class="content11text"><div class="alltext">Elevate the co-browsing experience<br/>
			by instantly communicating reactions<br/>
			to shared content through text chat.</div></div>
				<div id="content11image"><img src="/static/images/pages/feattextchat.png" alt="Image" class="show-img" /></div>
		</div>
</div>

<div id="content12">
	<div class="centredcontent">
		<div id="content12image"><img src="/static/images/pages/featcontrolpass.png" alt="Image" class="show-img" /></div>
		<div id="content12title"><div class="mediumheader">CONTROL PASSING</div></div>

		<div class="content12text"><div class="alltext">Request and pass leader controls<br/>
			to take turns navigating through<br/>both online and offline content.</div></div>
	</div>
</div>