<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/tour_howitworks.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/tour_howitworks.js");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>
<div id="titlebar">
	<div class="centredcontent">
		<div class="tour-btn-left">
			<a href="/pages/tour_features"><i class="fa fa-arrow-left"></i> Back: Features</a>
		</div>
		<div id="content0title"><div class="mediumheader">HOW IT WORKS</div></div>
		<div class="tour-btn-right">
			<a href="/pages/pricing">Next: Start Now <i class="fa fa-arrow-right"></i></a>
		</div>
	</div>	
</div>	


<div id="content1">
	<div class="centredcontent">
		<div id="content1group">
			<div class="titletable">

				<div id="circle1">1</div>
				<div id="content1title"><div class="mediumheader">START OR JOIN A ROOM</div></div>
			</div>

			<div class="content"><div class="alltext">
				Initiate a session by clicking the Start<br/>
				button or join an existing one via the <br/>
				invite link or by entering the unique <br/>
				identifier into the Join a Room box.<br/><br/>


				<img src="/static/images/pages/joinexisting.png" alt="Image" class="show-img" /></div></div>
		</div>

		<!--<form>
			<div class="roomgobox">
				<textarea id="formtextarea">Enter Room Number</textarea>
				<div class="gobutton">
					GO
				</div>
			</div>
		</form>	-->

		<div class="imagetable">
			<div id="content1image"><img src="/static/images/pages/startmodal.png" alt="Image" class="show-img" /></div>
		</div>	
	</div>
</div>

<div id="content2">
	<div class="centredcontent">


		<div class="imagetable">
			<div id="content2image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/invitemodal.png" /></div>
		</div>	

		<div id="content2group">

			<div class="titletable">	

				<div id="circle2">2</div>	
				<div id="content2title"><div class="mediumheader">SEND INVITES</div></div>
			</div>

			<div class="content"><div class="alltext">
				Send out invites via your default <br/>
				email service, filling out the web <br/> 
				form or copying and pasting the <br/>
				invite link.  <br/>
				</div></div>
		</div>

		<!--<form>	
			<div class="roomgobox2">
				<textarea id="formtextarea">Enter Room Number</textarea>
				<div class="gobutton">
					GO
				</div>
			</div>	
		</form>-->
	</div>
</div>



<div id="content3">	
	<div class="centredcontent">
		<div id="content3group">
			<div class="titletable">	
				<div id="circle3">3</div>	
				<div id="content3title"><div class="mediumheader">BROWSE TOGETHER</div></div>
			</div>

			<div id="content3text"><div class="alltext">Browse together from page to page, pass leader controls <br/>
				and share the infinite beauty of the web in real-time.   </div></div>
		</div>
		<div id="content3image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/browsetogether.png" /></div>
	</div>	

</div>


<div id="content4">
	<div class="centredcontent">
		<div id="content4group">
			<div class="titletable">	
				<div id="circle4">4</div>	
				<div id="content4title"><div class="mediumheader">EXPLORE THE FEATURES</div></div>
			</div>
			<div class="content4view">
				<img src="/static/images/pages/hiwurl.png" alt="Image" />
				<div class="box">
					<div id="grid">
						<a href="/pages/features#content1" class="iconsq01">
							<div id="icon01"></div>
						</a>

						<a href="/pages/features#content2" class="iconsq02">
							<div id="icon02"></div>
						</a>

						<a href="/pages/features#content3" class="iconsq03">
							<div id="icon03"></div>
						</a>

						<a href="/pages/features#content4" class="iconsq04">
							<div id="icon04"></div>
						</a>

						<a href="/pages/features#content5" class="iconsq05">
							<div id="icon05"></div>
						</a>

						<a href="/pages/features#content6" class="iconsq06">
							<div id="icon06"></div>
						</a>

						<a href="/pages/features#content7" class="iconsq07">
							<div id="icon07"></div>
						</a>

						<a href="/pages/features#content8" class="iconsq08">
							<div id="icon08"></div>
						</a>

						<a href="/pages/features#content9" class="iconsq09">
							<div id="icon09"></div>
						</a>

						<a href="/pages/features#content10" class="iconsq10">
							<div id="icon10"></div>
						</a>
					</div>	
				</div>
			</div>
		</div>
	</div>
</div>	

<div id="content5">
	<div class="centredcontent">
		<div id="content5text">
			<div class="alltext">
				Preview <a href="/pages/HIWmobile">How It Works</a> on Mobile.
			</div>
		</div>
	</div>	
</div>		