<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/usabilitytesting.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/usabilitytesting.js");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>
	<div id="content0">
		<div class="centredcontent">
			
			<div id=content0title><div class="mediumheader">USABILITY TESTING</div></div>
			<div id="content0text"><div class="alltext">Conduct usability testing by leveraging diverse response<br/>pools to 
achieve cost efficiencies and deeper insights.</div></div>	
			<a href="#" id="topdlbutton" class="enablesite">DEMO SAMESURF</a>
			<div id="usabilitytestingimage"></div>
			
		</div>	
	</div>	
	
	<div id="content1">
		<div class="centredcontent">
			<div id="content1title"><div class="mediumheader">WHY USE SAMESURF FOR USABILITY TESTING?</div></div>
				<div id="grid">
					<div class="bulletbox">
						<div class="bulletptblue"></div>
					Seamless remote testing for multiple respondents
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptorange"></div>
					Real-time solution for analyzing user interactions
					</div>
					
					<div class="bulletbox">
						<div class="bulletptred"></div>
					Significant resource, expense and time savings
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptgreen"></div>
					Built-in features like video chat & screen drawing
					</div>
					
					<div class="bulletbox">
						<div class="bulletptgreen"></div>
					Install-free testing reduces incidence of user error
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptred"></div>
					Ability for clients to preview results in real-time
					</div>
					
					<div class="bulletbox">
						<div class="bulletptorange"></div>
					Platform for collaborative user interface testing</div>
					
					<div class="bulletbox2">
						<div class="bulletptblue"></div>
					Support across virtually all devices and browsers
					</div>
				</div>
		
		</div>
	</div>
	
		
	
	<div id="content2">
		<div class="centredcontent">
			<div id="content2title"><div class="mediumheader">FEATURES</div></div>
				<div id="grid2">
				<a href="/pages/features#content1" class="iconsq1">
					<div id="icon1"></div>
				</a>

				<a href="/pages/features#content6" class="iconsq2">
					<div id="icon2"></div>
				</a>

				<a href="/pages/features#content4" class="iconsq3">
					<div id="icon3"></div>
				</a>

				<a href="/pages/features#content12" class="iconsq4">
					<div id="icon4"></div>
				</a>

				<a href="/pages/features#content8" class="iconsq5">
					<div id="icon5"></div>
				</a>
				</div>		
			
		</div>
	</div>	
	
	<div id="content3">
		<div class="centredcontent">
			<div id="assistedsalesvid">
					<iframe src="//player.vimeo.com/video/77007215?title=0&amp;byline=0&amp;portrait=0" 
					width="917" height="516" allowfullscreen></iframe>
			</div>
			
		</div>
	</div>	
	
	<div id="content4">
		<div class="centredcontent">
			<div id="content4image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/sitetesting.png" /></div>
				<div id="content4title"><div class="mediumheader">ONLINE SITE TESTING</div></div>
						
			<div class="content4text"><div class="alltext">Samesurf transcends in-person testing by<br/> 
giving life to remote sessions that engage<br/> 
larger and more diverse response pools.</div></div>
		</div>
	</div>	
	
	<div id="content5">
		<div class="centredcontent">
			<div id="content5title"><div class="mediumheader">SIMULTANEOUS UI TESTING</div></div>
						
			<div class="content5text"><div class="alltext">Samesurf enables testing organizations to<br/>evaluate a virtually unlimited number of<br/>
remote respondents at the same time.</div></div>
				<div id="content5image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/multiinsights.png" /></div>
		</div>
	</div>	
