<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/uses.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/uses.js");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>
	<div id="content0">
		<div class="centredcontent">
			
			<div id=content0title><div class="mediumheader">PRIMARY USES</div></div>
				<a href="#" id="topdlbutton" class="enablesite">DEMO SAMESURF</a>
								
		</div>	
	</div>	
	
	<div id="content1">
		<div class="centredcontent">
			<div id="content1title"><div class="mediumheader">ONLINE SUPPORT</div></div>
						
			<div class="content1text"><div class="alltext">Empower agents to provide real-time<br/> 
			support to customers without enduring<br/>installs, site modifications and delays.   
			<br><a href="/pages/support">Learn More</a></div></div>
				<div class="bluecircle">
					<div id="pic1"></div>
				</div>
		</div>
	</div>	
	
	<div id="content2">
		<div class="centredcontent">
			<div class="greencircle">
				<div id="pic2"></div>
			</div>
			
			<div id="content2title"><div class="mediumheader">ASSISTED SALES</div></div>
			<div class="content2text"><div class="alltext">Simulate the store experience within the<br/>virtual realm by seamlessly connecting<br/>clients and agents on the same page.<br><a href="/pages/sales">Learn More</a></div></div>
				
		</div>
	</div>
	
	<div id="content3">
		<div class="centredcontent">
			<div id="content3title"><div class="mediumheader">PRESENTATIONS</div></div>
						
			<div class="content3text"><div class="alltext">Deliver install-free presentations from<br/> 
			virtually any device or browser without<br/>the hassles or latency of screen sharing.  
			
			<br><a href="/pages/presentations">Learn More</a></div></div>
				<div class="redcircle">
					<div id="pic3"></div>
				</div>
		</div>
	</div>	
	
	<div id="content4">
		<div class="centredcontent">
			<div class="bluecircle2">
				<div id="pic4"></div>
			</div>
			
			<div id="content4title"><div class="mediumheader">MEETINGS</div></div>
			<div class="content4text"><div class="alltext">Transform any web experience into an<br/>install-free platform for presentations,<br/>meetings and inspired collaboration.<br><a href="/pages/meetings">Learn More</a></div></div>
				
		</div>
	</div>
	
	
	<div id="content5">
		<div class="centredcontent">
			<div id="content5title"><div class="mediumheader">SHOP TOGETHER</div></div>
						
			<div class="content5text"><div class="alltext">Bring the store experience online by<br/>enabling visitors to shop together in<br/>real-time with friends and experts. 
			<br><a href="/pages/shop">Learn More</a></div></div>
				<div class="yellowcircle">
					<div id="pic5"></div>
				</div>
		</div>
	</div>	
	
	<div id="content6">
		<div class="centredcontent">
			<div class="redcircle2">
				<div id="pic6"></div>
			</div>
			
			<div id="content6title"><div class="mediumheader">COLLABORATION</div></div>
			<div class="content6text"><div class="alltext">Infuse visual elements into online<br/>interactions via a truly simple yet<br/>robust platform for collaboration.<br><a href="/pages/collaboration">Learn More</a></div></div>
				
		</div>
	</div>
	
	<div id="content7">
		<div class="centredcontent">
			<div id="content7title"><div class="mediumheader">CORPORATE TRAINING</div></div>
						
			<div class="content7text"><div class="alltext">Empower instructors to simultaneously<br/>educate a multitude of trainees without<br/>requiring installs or coding of any kind.  
			<br><a href="/pages/corptraining">Learn More</a></div></div>
				<div class="purplecircle">
					<div id="pic7"></div>
				</div>
		</div>
	</div>
	
	<div id="content8">
		<div class="centredcontent">
			<div class="pinkcircle">
				<div id="pic8"></div>
			</div>
			
			<div id="content8title"><div class="mediumheader">REMOTE CONTROL</div></div>
			<div class="content8text"><div class="alltext">Remotely control screens that span<br/>the globe from any device without<br/>additional hardware or coding.<br><a href="/pages/remotecontrol">Learn More</a></div></div>
				
		</div>
	</div>
	
	<div id="content9">
		<div class="centredcontent">
			<div id="content9title"><div class="mediumheader">BROWSE TOGETHER</div></div>
						
			<div class="content9text"><div class="alltext">Unleash crystal clear co-browsing<br/>while you
shop, watch videos and<br/>book travel together in real-time.
			<br><a href="/pages/browse">Learn More</a></div></div>
				<div class="greencircle2">
					<div id="pic9"></div>
				</div>
		</div>
	</div>
	
	<div id="content10">
		<div class="centredcontent">
			<div class="bluecircle2">
				<div id="pic10"></div>
			</div>
			
			<div id="content10title"><div class="mediumheader">WATCH VIDEOS TOGETHER</div></div>
			<div class="content10text"><div class="alltext">Stay in perfect sync with one another<br/>while watching
videos and live events<br/>on rich media sites that span the web.<br/>
			<a href="/pages/watchvideos">Learn More</a></div></div>
				
		</div>
	</div>		
	
	<div id="content11">
		<div class="centredcontent">
						
			<div class="content11text"><div class="alltext">View <a href="/pages/secondaryuses">Secondary Uses</a>.</div></div>
			
		</div>
	</div>	

