<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/videos.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/videos.js");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>

<div id="pic_bg">
	<h1>
		VIDEOS
	</h1>
</div>

<div class="block light">
	<div class="container">
		<div class="row">
			<div class="col-md-4">
				<a href="#" class="modal" id="videos_video1">
					<img src="/static/images/pages/videos_placeholder.png" alt="PDF" />
					<div class="title">
						Online Support 
					</div>
					<div class="time">
						0:33
					</div>
				</a>
			</div>
			<div class="col-md-4">
				<a href="#" class="modal" id="videos_video1">
					<img src="/static/images/pages/videos_placeholder.png" alt="PDF" />
					<div class="title">
						Everyday Collaboration:<br/>
						Donata 
					</div>
					<div class="time">
						0:33
					</div>
				</a>
			</div>
			<div class="col-md-4">
				<a href="#" class="modal" id="videos_video1">
					<img src="/static/images/pages/videos_placeholder.png" alt="PDF" />
					<div class="title">
						Collaborate in Real-Time<br/>
						from Anywhere: Tommy 
					</div>
					<div class="time">
						0:33
					</div>
				</a>
			</div>
			<div class="col-md-4">
				<a href="#" class="modal" id="videos_video1">
					<img src="/static/images/pages/videos_placeholder.png" alt="PDF" />
					<div class="title">
						Make House Calls 
					</div>
					<div class="time">
						0:33
					</div>
				</a>
			</div>
			<div class="col-md-4">
				<a href="#" class="modal" id="videos_video1">
					<img src="/static/images/pages/videos_placeholder.png" alt="PDF" />
					<div class="title">
						Beam Mobile Content to<br/>
						the Big Screen
					</div>
					<div class="time">
						0:33
					</div>
				</a>
			</div>
			<div class="col-md-4">
				<a href="#" class="modal" id="videos_video1">
					<img src="/static/images/pages/videos_placeholder.png" alt="PDF" />
					<div class="title">
						Shop with Girls and Agent 
					</div>
					<div class="time">
						0:33
					</div>
				</a>
			</div>
			<div class="col-md-4">
				<a href="#" class="modal" id="videos_video1">
					<img src="/static/images/pages/videos_placeholder.png" alt="PDF" />
					<div class="title">
						Shop Together: Just Girls 
					</div>
					<div class="time">
						0:33
					</div>
				</a>
			</div>
			<div class="col-md-4">
				<a href="#" class="modal" id="videos_video1">
					<img src="/static/images/pages/videos_placeholder.png" alt="PDF" />
					<div class="title">
						Watch Videos Together 
					</div>
					<div class="time">
						0:33
					</div>
				</a>
			</div>
			<div class="col-md-4">
				<a href="#" class="modal" id="videos_video1">
					<img src="/static/images/pages/videos_placeholder.png" alt="PDF" />
					<div class="title">
						Web Designer and Client
					</div>
					<div class="time">
						0:33
					</div>
				</a>
			</div>
		</div>
	</div>
</div>

