<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/watchvideos.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/watchvideos.js");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>
	<div id="content0">
		<div class="centredcontent">
			
			<div id=content0title><div class="mediumheader">WATCH VIDEOS TOGETHER</div></div>
			<div id="content0text"><div class="alltext">Stay in perfect sync with one another while watching<br/>
videos and live events from across the web.</div></div>				
			<a href="http://stage-video.samesurf.com/video" class="enablesite" id="topdlbutton">VISIT PUBLICROOMS.COM</a>
			<div id="watchvideosimage"></div>
			
		</div>	
	</div>	
	
	<div id="content1">
		<div class="centredcontent">
			<div id="content1title"><div class="mediumheader">WHY USE SAMESURF TO WATCH VIDEOS TOGETHER?</div></div>
				<div id="grid">
					<div class="bulletbox">
						<div class="bulletptblue"></div>
					Seamless video sharing across the entire web
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptorange"></div>
					Pristine rendering without choppiness or latency
					</div>
					
					<div class="bulletbox">
						<div class="bulletptred"></div>
					Instant socialization for videos and live events 
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptgreen"></div>
					Seamless control passing between multiple users
					</div>
					
					<div class="bulletbox">
						<div class="bulletptgreen"></div>
					Parallel video chat while watching media content
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptred"></div>
					Eliminated need for special hardware and installs
					</div>
					
					<div class="bulletbox">
						<div class="bulletptorange"></div>
					Cross platform for all major browsers and devices
					</div>
					
					<div class="bulletbox2">
						<div class="bulletptblue"></div>
					Crystal clear audio rendering of synced content
					</div>
				</div>
		
		</div>
	</div>
	
		
	
	<div id="content2">
		<div class="centredcontent">
			<div id="content2title"><div class="mediumheader">FEATURES</div></div>
				<div id="grid2">
				<a href="/pages/features#content1" class="iconsq1">
					<div id="icon1"></div>
				</a>

				<a href="/pages/features#content6" class="iconsq2">
					<div id="icon2"></div>
				</a>

				<a href="/pages/features#content4" class="iconsq3">
					<div id="icon3"></div>
				</a>

				<a href="/pages/features#content12" class="iconsq4">
					<div id="icon4"></div>
				</a>

				<a href="/pages/features#content8" class="iconsq5">
					<div id="icon5"></div>
				</a>
			</div>	
			
		</div>
	</div>	
	
	<div id="content3">
		<div class="centredcontent">
			<div id="assistedsalesvid">
					<iframe src="//player.vimeo.com/video/77007215?title=0&amp;byline=0&amp;portrait=0" 
					width="917" height="516" allowfullscreen></iframe>
				</div>
			
		</div>
	</div>	
	
	<div id="content4">
		<div class="centredcontent">
			<div id="content4image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/watchtogether.png" /></div>
				<div id="content4title"><div class="mediumheader">PRIVATE ROOMS</div></div>
						
			<div class="content4text"><div class="alltext">Samesurf supports invite-only sessions<br/>which simulate private screening rooms<br/>made for smaller groups of viewers.
</div></div>
		</div>
	</div>	
	
	<div id="content5">
		<div class="centredcontent">
			<div id="content5title"><div class="mediumheader">PLAY, PAUSE & SKIP TOGETHER</div></div>
						
			<div class="content5text"><div class="alltext">PublicRooms.com allows users to co-browse<br/>perfectly synced videos from the Youtube and</br>Vimeo libraries together in real-time.</div></div>
				<div id="content5image"><img src="/static/images/pages/transparent.png" alt="Image" data-src="/static/images/pages/syncedvids2.png" /></div>
				<a href="http://www.samesurf.com/publicrooms.html"><div id="pubroomsbutton">VISIT PUBLICROOMS.COM</div></a>
		</div>
	</div>	
	

