<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/whitepapersdetail.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/whitepapersdetail.js");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>

<div class="block dark">
	<div class="container">
		<div class="back">
			<a href="#" class="back-btn" id="topdlbutton">BACK TO WHITEPAPERS</a>
		</div>
		<div class="whitepaper-image">
			<img src="/static/images/pages/pdf-ss_vs_cobrowsing.jpg" alt="Preview" />
		</div>
		<div class="whitepaper-description">
			<div class="whitepaper-subtitle">
				Samesurf Flows
			</div>
			<div class="whitepaper-title">
				Demo Samesurf
			</div>
			<p>
				Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla felis, ornare sit amet euismod a, lacinia egestas sem. Fusce finibus non tellus non lacinia. Sed vitae enim ac tellus malesuada congue. Donec rutrum efficitur ornare rhoncus nibh quis, iaculis velit...
			</p>
			<p class="continue">
				Continue reading? Please write your e-mail to download the PDF
			</p>
			<form id="requestpdf">
				<label>Your Email</label>
				<input type="text" name="email" />
				<label>Phone Number</label>
				<input type="text" name="phone" />
				<label>Company</label>
				<input type="text" name="company" />
				<label>Country</label>
				<input type="text" name="country" />
				<input type="submit" value="Download Now" />
			</form>
		</div>
	</div>
</div>

