<?php
	$this->setTitle("samesurf");
	$this->addCSSFile("/static/css/pages/whitepapers.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/whitepapers.js");
	$this->addJSFile("/static/js/pages/lazyload.js");
	$this->addJSFile("/static/js/pages/animate.js");
	$this->addCSSFile("/static/css/pages/lazyload.css");
	$this->addCSSFile("/static/css/pages/animate.css");
?>

<div id="pic_bg">
	<h1>
		White Papers
	</h1>
</div>

<div class="block light">
	<div class="container">
		These White Papers serve as an illustrative review<br/>
		of the inner workings of the Samesurf Platform.
		 
	</div>
</div>

<div class="block dark">
	<div class="container">
		<div class="row">
			<div class="col-md-4">
				<a href="#">
					<img src="/static/images/pages/pdf-ss_vs_cobrowsing.jpg" alt="PDF" />
				</a>
			</div>
			<div class="col-md-4">
				<a href="#">
					<img src="/static/images/pages/pdf-placeholder.jpg" alt="PDF" />
				</a>
			</div>
			<div class="col-md-4">
				<a href="#">
					<img src="/static/images/pages/pdf-placeholder.jpg" alt="PDF" />
				</a>
			</div>
		</div>
	</div>
</div>


