<?php $this->setTitle("samesurf"); $this->addCSSFile("/static/css/pages/workflow.css"); $this->addCSSFile("/static/css/pages/general.css"); $this->addJSFile("/static/js/pages/workflow.js"); $this->addJSFile("/static/js/pages/lazyload.js"); $this->addJSFile("/static/js/pages/animate.js");
$this->addCSSFile("/static/css/pages/lazyload.css"); $this->addCSSFile("/static/css/pages/animate.css"); ?>

<div id="content1">
	<div class="centredcontent">
		<div id="content1title">
			<div class="mediumheader">WORKFLOW FOR SAMESURF CO-BROWSING</div>
		</div>
		<div id="content1subtitle">
			<div class="mediumheader">UNITED STATES PATENT NO. 8,527,591</div>
			<div class="mediumheader" style="font-size: 14px;">MULTIPLE PATENTS AND PCT APPS PENDING</div>
		</div>
		<div class="content1text">
			<div class="alltext">Samesurf detects and transmits event changes on the leader<br/> side and instantly simulates those events for followers.</div>
		</div>
	</div>
</div>

<div id="content2">
	<div class="centredcontent">

		<div class="content2text">
			<div class="alltext"><strong>Step 1(a):</strong> For syncing webpages, the leader navigates to a new page and that page content is fetched directly from the web server.
			</div>
		</div>
		<div id="content2image"><img src="/static/images/pages/transparent.png" class="show-img" data-src="/static/images/pages/1Aworkflow.png" alt="Image" /></div>

		<div id="content2imagea"><img src="/static/images/pages/transparent.png" class="show-img" data-src="/static/images/pages/1Bworkflow.png" alt="Image" /></div>
		<div class="content2texta">
			<div class="alltext"><strong>Step 1(b):</strong>The leader's web addresses are instantly pushed to the Samesurf synchronization server.</div>
		</div>

		<div class="content2textb">
			<div class="alltext"><strong>Step 2:</strong>The leader's URL is then sent via the Samesurf server to the other session participants.</div>
		</div>
		<div id="content2imageb"><img src="/static/images/pages/transparent.png" class="show-img" data-src="/static/images/pages/2workflow.png" alt="Image" /></div>

		<div id="content2imagec"><img src="/static/images/pages/transparent.png" class="show-img" data-src="/static/images/pages/3workflow.png" alt="Image" /></div>
		<div class="content2textc">
			<div class="alltext"><strong>Step 3:</strong>Each attendee independently fetches the content of the webpage from the web server for that page.</div>
		</div>

		<div class="content2textd">
			<div class="alltext"><strong>NOTE:</strong>For authenticated co-browsing, the Samesurf server fetches the content from the web server on behalf of each follower and then distributes it to each of the participants.</div>
		</div>
		<div id="content2imaged"><img src="/static/images/pages/transparent.png" class="show-img" data-src="/static/images/pages/4workflow.png" alt="Image" /></div>
	</div>
</div>


<div id="content3">
	<div class="centredcontent">


		<div id="content3title">
			<div class="mediumheader">EVENT PASSING WORKFLOW</div>
		</div>

		<div class="content3text">
			<div class="alltext">Once an attendee types a chat message or types into a text field, these events are</br> sent to the Samesurf server and distributed to the other attendees. Custom </br>configurations can limit the passing of certain events based upon type.</div>
		</div>
	</div>
</div>

<div id="content4">
	<div class="centredcontent">


		<div class="content4text">
			<div class="alltext"><strong>Step 1:</strong> The occurrence of an individual event on the leader side is pushed to the Samesurf server.</div>
		</div>
		<div id="content4image"><img src="/static/images/pages/transparent.png" class="show-img" data-src="/static/images/pages/eventpassstep1.png" alt="Image" /></div>

		<div id="content4imagea"><img src="/static/images/pages/transparent.png" class="show-img" data-src="/static/images/pages/eventpassstep2.png" alt="Image" /></div>
		<div class="content4texta">
			<div class="alltext"><strong>Step 2:</strong> If the leader is authorized to pass the event, it is then distributed and simulated on the follower side.</div>
		</div>
	</div>
</div>

<div id="content5">
	<div class="centredcontent">


		<div id="content5title">
			<div class="mediumheader">FORM SUBMISSION WORKFLOW</div>
		</div>

		<div class="content5text">
			<div class="alltext">When a leader submits an HTML form, the contents are distributed to the followers by default. However, data passing can be programmatically blocked for sensitive input fields that are specifically designated as non-shareable. An algorithm automatically blocks passwords from view during entry.
			</div>
		</div>
	</div>
</div>

<div id="content6">
	<div class="centredcontent">
		<div class="content6text">
			<div class="alltext"><strong>Step 1:</strong> The leader submits an HTML form by inputting text data into an input box for a site search or other form of text-based submission.</div>
		</div>
		<div id="content6image"><img src="/static/images/pages/transparent.png" class="show-img" data-src="/static/images/pages/formsub1.png" alt="Image" /></div>

		<div id="content6imagea"><img src="/static/images/pages/transparent.png" class="show-img" data-src="/static/images/pages/formsub2.png" alt="Image" /></div>
		<div class="content6texta">
			<div class="alltext"><strong>Step 2:</strong> If allowed, the form contents are pushed to the Samesurf server and distributed to each attendee.</div>
		</div>

		<div class="content6textb">
			<div class="alltext"><strong>Step 3:</strong> Each attendee's browser automatically and independently submits the form.</div>
		</div>
		<div id="content6imageb"><img src="/static/images/pages/transparent.png" class="show-img" data-src="/static/images/pages/formsub3.png" alt="Image" /></div>
	</div>
</div>




