<?php
	$this->setTitle("admin");
	$this->addCSSFile("/static/css/common.css");
	$this->addCSSFile("/static/css/signup_steps_common.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addCSSFile("/static/css/admin_instructions.css");

?>

	<div id="sub_header">
		<div id="sub_nav">
			<div id="sub_navlinks">
					<a href="#">HOW IT WORKS</a>
					<a href="#">REQUEST DEMO</a>
					<a href="#">PRICING</a>
					<a href="#">CONTACT US</a>
			</div>
		</div>
	</div>
<div class="banner">
	<div class="banner_main">
		<div class="banner_title">
			HOW TO ENABLE YOUR WEBSITE
		</div>
	</div>
</div>

<div class="centre_content">
	<div id="progressbox">
		<div id="progressbox_title">TRACK YOUR PROGRESS</div>
		<p id="progressbox_text">Track your progress through the implementation process by making reference to the action items below:
		</p>
		<div id="signup_step_tabs">
			<div id="signup_step1_tab">1. ADD DOMAINS</div>
			<div id="signup_step2_tab">2. GRANT PERMISSIONS</div>
			<div id="signup_step3_tab">3. CONFIGURE SETTINGS</div>
			<div id="signup_step4_tab">4. DEPLOY</div>
		</div>
	</div>
	<div class="box_white">
		<div class="instruction_steps_header"><div class="info_dot">1</div><div class="instruction_steps_header_text">Add Domains</div></div>
		<p class="instruction_steps_body_text">Input eligible domains for co-browsing or click the checkbox to allow Co-Browsing of the Entire Web.
		</p>
	</div>
	
	<div class="box_white">
		<div class="instruction_steps_header"><div class="info_dot">2</div><div class="instruction_steps_header_text">Grant Permissions</div></div>
		<p class="instruction_steps_body_text">Add authorized users like webmasters to assist with integration or to modify settings in your account.
		</p>
	</div>
	
	<div class="box_white">
		<div class="instruction_steps_header"><div class="info_dot">3</div><div class="instruction_steps_header_text">Configure Settings</div></div>
		<p class="instruction_steps_body_text">Configure or modify features, settings, buttons and theming for your custom samesurf implementation.
		</p>
	</div>
	
	<div class="box_white">
		<div class="instruction_steps_header"><div class="info_dot">4</div><div class="instruction_steps_header_text">Deploy your Code</div></div>
		<p class="instruction_steps_body_text">Get the custom code you'll integrate onto your website that will make the Start Button appear on your site.
		</p>
	</div>
	
	<a href="/account/add">
		<div id="instructions_next" class="button_blue">
			GET STARTED
		</div>
	</a>
</div>
