<?php
	$this->setTitle("admin");
	$this->addCSSFile("/static/css/common.css");
	$this->addCSSFile("/static/css/common_form.css");
	$this->addCSSFile("/static/css/signup_steps_common.css");
	$this->addCSSFile("/static/css/account_default.css");
?>

	<div id="sub_header">
		<div id="sub_nav">
			<div id="sub_navlinks">
					<a href="#">HOW IT WORKS</a>
					<a href="#">REQUEST DEMO</a>
					<a href="#">PRICING</a>
					<a href="#">CONTACT US</a>
			</div>
		</div>
	</div>
<div class="banner">
	<div class="banner_main">
		<div class="banner_title">DASHBOARD</div>
		<a href="/logout"><div id="logout_button">LOG OUT</div></a>
	</div>
</div>

<div class="centre_content">
	
	<div class="box_white" id="accont_container">
		<div class="box_white_head">Welcome,</div>
		<div class="box_white_body" id="account">
			<div id="split_box1">
				<div id="split_box1_head">Account Details:
					<a href="/account/updatedetails"><div id="edit_details">Edit</div></a>
				</div>
				<?php 
					$firstname = $view->defaults->details->first_name;
					$lastname = $view->defaults->details->last_name;
					$organization = $view->defaults->details->organization;
					$location = $view->defaults->details->location;
					$services = $view->defaults->details->services;
					
					$email = $view->defaults->email;
				?>
					<p class="details_text">Name: <span class="details_span"><?php echo $firstname . " " . $lastname ?></span></p>
					<p class="details_text">Organization: <span class="details_span"><?php echo $organization ?></span></p>
					<p class="details_text">Email: <span class="details_span"><?php echo $email ?></span></p>
					<p class="details_text">Location: <span class="details_span"><?php echo $location ?></span></p>
					<p class="details_text">Service(s): <span class="details_span"><?php echo $services ?></span></p>
				
			</div>
			<div id="split_box2">
				<p class="account_options">Clear my Browsing History</p>
				<p class="account_options"><a href="/login/reset">change password</a></p>
				<p class="account_options"><a href="">upgrade to pro</a></p>
				<p class="account_options"><a href="">edit payment</a></p>
				<p class="account_options"><a href="">logout</a></p>
			</div>
		</div>
	</div>
	<div class="box_white_container">
		<div id="domains" class="box_white">
			<div class="box_white_head">My Domains:
				
				<a href="/account/add">
		<div id="adddomain_submit">Add Domain</div>
	</a>

			</div>
			<div class="box_white_body">
				<ol>
					<?php
						$domains = $view->defaults->domains;
						foreach($domains as $domain) : 
					?>
						<li class="existing_domain">
							<input class="listed_domain" type=text value="<?= $domain->domain() ?>" readonly>
								<a href="/account/auth/pid/<?= $domain->publicid()?>"><div class="domain_box domain_edit"></div></a>
								<a href="http://<?= $domain->domain() ?>"><div class="domain_box domain_go"></div></a>
							</input>
						</li>
					<?php endforeach?>
				</ol>
			</div>
		</div>
		<div id="spacer"></div>
		<div id="publicrooms" class="box_white">
			<div class="box_white_head">My Public Rooms:</div>
			<div class="box_white_body"></div>
		</div>
	</div>
	<div class="box_white">
		<div class="box_white_head">Browsing History:</div>
		<div class="box_white_body">
			<div class="body_space_saver"></div>
		</div>
	</div>
	<div class="tabbed_box">
			<div class="tabbed_box_tabs">
				<div class="tab">My Presentations</div>
				<div class="tab">My Files</div>
			</div>
			<div class="box_white_body">
				<div class="body_space_saver"></div>
			</div>
	</div>

</div>		

