<?php
	$this->setTitle("update details");
	$this->addCSSFile("/static/css/common.css");
	$this->addCSSFile("/static/css/common_form.css");
	$this->addCSSFile("/static/css/account_update.css");
?>
	<div id="sub_header">
		<div id="sub_nav">
			<div id="sub_navlinks">
					<a href="#">HOW IT WORKS</a>
					<a href="#">REQUEST DEMO</a>
					<a href="#">PRICING</a>
					<a href="#">CONTACT US</a>
			</div>
		</div>
	</div>
<div class="banner">
	<div class="banner_main">
		<div class="banner_title">UPDATE DETAILS</div>
	</div>
</div>

<div class="centre_content">

	<form id="update" method="post" action="">
	
		<fieldset>
			<div id="update_first_name" class="input_field">
				<label>First Name</label>
				<div class="input_style">
					<input name="first_name" type="text" <?php util_html::attr("value", $view->defaults, "email")?>> 
				</div>
				<span class="error"><?php util_html::text($view->errors, "first_name")?></span>
			</div>
		
			<div id="update_last_name" class="input_field">	
				<label>Last Name</label>
				<div class="input_style">
					<input name="last_name" type="text"> 
				</div>
				<span class="error"> <?php util_html::text($view->errors, "last_name")?><span>
			</div>
			
			<div id="update_last_name" class="input_field">	
				<label>Location</label>
				<div class="input_style">
					<input name="location" type="text"> 
				</div>
				<span class="error"> <?php util_html::text($view->errors, "location")?><span>
			</div>
			
			<div id="update_last_name" class="input_field">	
				<label>Company</label>
				<div class="input_style">
					<input name="company" type="text"> 
				</div>
				<span class="error"> <?php util_html::text($view->errors, "company")?><span>
			</div>
	
			<input type="submit" class="button_blue">
	
		</fieldset>
	</form>
</div>