<?php
	$this->setTitle("admin");
	$this->addCSSFile("/static/css/common.css");
	$this->addCSSFile("/static/css/account_start.css");
	$this->addCSSFile("/static/css/pages/general.css");
	$this->addJSFile("/static/js/pages/homepage.js");

?>

	<div id="sub_header">
		<div id="sub_nav">
			<div id="sub_navlinks">
					<a href="#">HOW IT WORKS</a>
					<a href="#">REQUEST DEMO</a>
					<a href="#">PRICING</a>
					<a href="#">CONTACT US</a>
			</div>
		</div>
	</div>

<div id="next_generation_box_container">
	<div id="next_generation_box">
		<div id="next_gen_text">
			<div class="heading">
				ENABLE YOUR SITE
			</div>
			<div class="homepagetext"><div class="alltext">
				Add install free co-browsing directly on your website to enable<br /> 
				activities like web sharing, online support and co-shopping.
			</div></div>
			<a href="/account/instructions">
			<div class="start_now_button">
				<div class="start_now_text">
					GET STARTED
				</div>
			</div>
			</a>
		</div>
	</div>
</div>
<div id="key_uses_box_container">
	<div id="key_uses_box">
		<div id="key_uses_text">
			KEY USES
		</div>
		<div id="circles_div">
			<a href="">
			<div class="key_uses_circles">
				<div id="headphones_circle">
				</div>
			</div>
			</a>
			<div class="key_uses_circles">
				<div id="hand_shake">
				</div>
			</div>
			<div class="key_uses_circles">
				<div id="high_five">
				</div>
			</div>
			<div class="key_uses_circles">
				<div id="whiteboard">
				</div>
			</div>
			<div class="key_uses_circles">
				<div id="trolley">
				</div>
			</div>
			<div class="key_uses_circles">
				<div id="blackboard">
				</div>
			</div>
			<div class="key_uses_circles">
				<div id="three_heads">
				</div>
			</div>
			<div class="key_uses_circles">
				<div id="mortar_board">
				</div>
			</div>
		</div>	
	</div>
</div>

<div id="topbuttoncontainer">
	<div class="centredcontent">
			<p id="additionaluses">View <a href="#">additional uses</a> for samesurf</p>
		</div>
	</div>
