<?php
	$this->setTitle("admin");
	$this->addCSSFile("/static/css/common.css");
	$this->addCSSFile("/static/css/signup_steps_common.css");
//  	$this->addCSSFile("/static/css/account_step1.css");
	$this->addCSSFile("/static/css/common_form.css");
	$this->addCSSFile("/static/css/account_config.css");
	$this->addJSFile("/static/js/account_config.js");
?>

	<div id="sub_header">
		<div id="sub_nav">
			<div id="sub_navlinks">
					<a href="#">HOW IT WORKS</a>
					<a href="#">REQUEST DEMO</a>
					<a href="#">PRICING</a>
					<a href="#">CONTACT US</a>
			</div>
		</div>
	</div>
<div class="banner">
	<div class="banner_main">
		<div class="banner_title">
				<?php echo $blocks->progress ?>
		</div>
	</div>
</div>

<div class="centre_content">
	<div id="config_options">
		<div id="options_head">
			<div id="main" class="options_tab options_tab_active"><span>MAIN FEATURES</span></div>
			<div id="premium" class="options_tab"><span>PREMIUM FEATURES</span></div>
			<div id="theme" class="options_tab"><span>THEME</span></div>
			<div id="domains" class="options_tab"><span>RELATED DOMAINS</span></div>
		</div>
		<div id="options_body">
			<form method="POST" id="config_form">
				<div id="theme_body" class="options_body">
					<ul>
						<li>
							<div class="feature" id="color_picker">
								<div class="feature_head">
									<div class="about_feature_wrap">
										<div class="about_feature">?</div>
									</div>
									<label>Color <span>(Default theme is samesurf blue)</span></label>
									<div class="divider"></div>
								</div>
								<span class="sub_head_text sub_header">Default Themes:</span>
								<div id="color_blue" class="color_select color_selected"></div>
								<div id="color_red" class="color_select"></div>
								<div id="color_yellow" class="color_select"></div>
								<div id="color_green" class="color_select"></div>
								<div id="color_purple" class="color_select"></div>
								<div class="color_select_or">OR</div>
								<span class="sub_header">Custom:</span>
								<div id="color_custom">
									<div id="color_custom_foreground" class="color_select"></div>
								</div>
								<div class="custom_color_wrap">
									<p>R,G,B or #HEX</p>
									<div class="input_style">
										<input type="text" id="custom" value="0000000"></input>
									</div>
									<input type="hidden" name="button_color" id="button_color"></input>
									<div class="custom_color_submit button_blue">SUBMIT</div>
								</div>

							</div>
						</li>
						<li>
						<div class="feature" id="logo_upload">
							<div class="feature_head">
								<div class="about_feature_wrap">
									<div class="about_feature">?</div>
								</div>
								<label>Logo <span>(Default Logo is Samesurf )</span></label>
								<div class="divider"></div>
							</div>
							<div class="sub_head_text">Choose a file:</div>
							<div id="logo_main">
								<div class="logo_img_container">
									<div class="logo_img_background">
										<div id="logo_img"></div>
									</div>
								</div>
								<div id="browse_button" class="upload_buttons">UPLOAD FROM DEVICE</div>
								<input type="file" name="logo" ></input>
								<span class="span_text">OR</span>
								<div class="upload_buttons">ADD EXISTING FILES</div>
							</div>
						</li>
						<li>
						<div class="feature" id="button_location">
							<div class="feature_head">
								<div class="about_feature_wrap">
									<div class="about_feature">?</div>
								</div>
								<label>Button Position <span>(Default Position is Lower Left)</span></label>
								
								<div class="custom_checkbox">
									<input type="checkbox" name="button_location" value="bl"></input>
									<div class="custom_checkbox_tick"></div>
								</div>
									<div class="checkbox_text">Left</div>
								<div class="custom_checkbox">
									<input type="checkbox" name="button_location" value="bm"></input>
									<div class="custom_checkbox_tick"></div>
								</div>
									<div class="checkbox_text">Middle</div>
								<div class="custom_checkbox">
									<input type="checkbox" name="button_location" value="br"></input>
									<div class="custom_checkbox_tick"></div>
								</div>
									<div class="checkbox_text">Right</div>
								<div class="custom_checkbox">

									<input type="checkbox" name="button_location" value="none"></input>
									<div class="custom_checkbox_tick"></div>
								</div>
									<div class="checkbox_text">None</div>

							</div>
							<div class="divider"></div>
							<a id="custom_button_link" href="">Create your custom button</a>
							<div class="sub_head_text">Example:</div>
							<div class="example_button_wrap">
								<div class="example_button" id="example_blue">surf together</div>
								<div class="example_button" id="example_red">shop together</div>
								<div class="example_button" id="example_yellow">live assist</div>
								<div class="example_button" id="example_green">live chat</div>
							</div>
						</li>
						
					</ul>
				</div>
				<div id="main_body" class="options_body">
					<ul>
						<?php
							$domain = $view->defaults->domain;
							$config = $domain->get_config();
			
							foreach ($config->bool_setting as $bool_setting):
								if($bool_setting->private == 0){
									$checked = "";
									if ($bool_setting->value) $checked = "checked";
							?>
							<li>
								<div class="feature">
									<div class="feature_content">
										<div class="about_feature_wrap">
											<div class="about_feature">?</div>
										</div>
										<label><?=$bool_setting->name?></label>
										
										<div class="custom_checkbox">
											<input type='checkbox' name=<?=$bool_setting->key?> <?=$checked?>>
											<div class="custom_checkbox_tick" value="<?=$checked?>"></div>
										</div>
										<div class="checkbox_text">Enable</div>
									</div>
								</div>
							</li>
						<?php } endforeach; ?>
					</ul>
				</div>
				<div id="premium_body" class="options_body">
					<ul>
						<?php
							
							foreach ($config->bool_setting as $bool_setting): 
								if($bool_setting->private == 1){
									$checked = "";
									if ($bool_setting->value) $checked = "checked";
							?>
							<li>
								<div class="feature">	
									<div class="about_feature_wrap">
										<div class="about_feature">?</div>
									</div>
									<label><?=$bool_setting->name?></label>
									<div class="custom_checkbox">
											<input type='checkbox' name=<?=$bool_setting->key?> <?=$checked?>>
											<div class="custom_checkbox_tick" value="<?=$checked?>"></div>
										</div>
									<div class="checkbox_text">Enable</div>
								</div>
							</li>
						<?php } endforeach; ?>
					</ul>
				</div>
				</form>
			<div id="domains_body" class="options_body">

			<ul>
					<li class="existing_domain_li">
						<?php 
							$domain = $view->defaults->domain->domain();
							echo "<div class='primary_domain_box'>".$domain."</div>"
						?>
					</li>
					<?php 
						foreach ($view->defaults->domain->list_authorized_domains() as $domain) {
							echo "<li class='existing_domain_li auth_domain_li'>
									<div class='auth_domain_img'></div>
									<div class='existing_domain_wrap'>
										<div class='authed_domain_box'>"
												. $domain->domain . 
											"
										</div>
										<div class='existing_domain_remove'>
												<div class='existing_domain_remove_icon'></div>
												<form method='post' action='/account/deauth/pid/".$view->defaults->domain->publicid()."/type/domain' class='remove_domain'>
													<input type='hidden' name='remove' value='$domain->domain'></input>
												</form>
									</div>
								</li>";
						}
					?>
				</ul>
			
			
			
			<div>
				<form id="auth_domain_form" method="post" action="/account/auth/pid/<?= $view->defaults->domain->publicid() ?>/type/domain">
					<div id="add_domains_input"  class="input_style"><input name="allowed" type="text" /></div>
				</form>
				<div class="submit button_blue">ADD</div>
			</div>
				</div>
			</div>
		</div>
		<div id="navbuttons">
			<div class="navbuttons_align">
				<a href="/account/auth/pid/<?= $view->defaults->domain->publicid()?>"><div class="back button_black">BACK</div></a>
				<input class="forward button_blue" type="submit" value="NEXT STEP: DEPLOY"/>
			</div>
		</div>
</div>
<div class="info_box">
	<div class="info_box_point_outer"></div>
	<div class="info_box_point"></div>
	<div class="info_box_wrap">
		<div class="info_box_title">INFO TITLE TEXT</div>
		<div class="info_box_body">
			aenean lacinia bibendum nulla sed consectetur. Etiam porta sem malesuada magna mollis euismod. Faucibus mollis interdum. Nullam id dolor id nibh ultricies vehicula ut id elit. Sed posuere consectetur est at.
		</div>
	</div>
</div>
