<!doctype html>
<html>
	<head>
		<title><?=$view->title?></title>
		<meta charset="utf-8">
		<link rel="shortcut icon" href="/static/favicon.ico" />
		<link rel='stylesheet' type='text/css' href='/static/fonts/stylesheet.css'/>
		<link rel='stylesheet' type='text/css' href='/static/css/layout.css'/>
		<link  rel='stylesheet' href='//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css'>
		<script type='text/javascript' src="/static/jquery.min.js"></script>
		<script type='text/javascript' src="/static/js/layout.js"></script>
		<script type='text/javascript' src="/static/js/videoModal.js"></script>
		<?php $this->include_css_files() ?>
		<?php $this->include_js_files() ?>
	</head>

	<body>
	
		<div class="scrollup"></div>
		
		<div id="sticky_footer_wrapper">
			<div id="modal_video" class="window player_frame">
				<div class="close"><img id="close" src="/static/images/modal-close.png" alt="close X"></div>
				<div class="player-container"></div>
			</div>
			<div id="mask"></div>
			<div id="header">
				<div id="nav">
					<div id="site_nav">
						<div id="navlogo"></div>
						<div id="navlogo_arrow"></div>
						<div class="top_chop header_site_choose">
							<div id="header_site_drop" class="drop_menu">
								<a href="/"><div id="site_samesurf" class="site_drop_content">
									<div id="logo_samesurf" class="link_logo"></div>
									<div class="site_title">Samesurf.com</div>
									<div class="site_description">Co-Browse Websites</div>
									</div></a>
								<a href="#"><div id="site_sameslide" class="site_drop_content">
									<div id="logo_sameslide" class="link_logo"></div>
									<div class="site_title">Sameslide.com</div>
									<div class="site_description">Co-Browse Presentations</div>
									</div></a>
								<a href="http://stage-video.samesurf.com/video"><div id="site_videos" class="site_drop_content">
									<div id="logo_samesurfvideo" class="link_logo"></div>
									<div class="site_title">Samesurf Videos</div>
									<div class="site_description">Co-Browse Videos</div>
									</div></a>
								<a href="http://stage-video.samesurf.com"><div id="site_publicrooms" class="site_drop_content">
									<div id="logo_publicrooms" class="link_logo"></div>
									<div class="site_title">PublicRooms.com</div>
									<div class="site_description">Co-Browse with the Masses</div>
									</div></a>
							</div>
						</div>
					</div>
					<div id="whats_samesurf">WHAT'S SAMESURF
						<div class="whats_samesurf_chop">
							<div id="whatssamesurf-dropdown" class="dropdown-nav">
								<div class="dropdown-header clearfix">
									<div class="w-66">
										What's Samesurf
									</div>
									<div class="w-33">
										Company
									</div>
								</div>
								<div class="dropdown-body clearfix">
									<div class="w-33 left">
										<a href="/pages/tour_different">Start Tour</a>
										<a href="/pages/howitworks">How It Works</a>
										<a href="/pages/features">Features</a>
										<a href="/pages/integration">Integration</a>
										<a href="/pages/security">Security</a>
										<a href="/pages/different">We're Different</a>
									</div>
									<div class="w-33 center">
										<a href="/pages/technology">Technology</a>
										<a href="/pages/customization">Customization</a>
										<a href="/pages/workflow">Workflow</a>
										<a href="/pages/phonesupport">Phone Support</a>
										<a href="/pages/livechat">Live Chat</a>
										<a href="/pages/benefits">Benefits</a>
									</div>
									<div class="border-left w-33 right">
										<a href="/pages/team">About Us</a>
										<a href="/pages/contactus">Contact Us</a>
										<a href="/pages/pricing">Pricing</a>
										<a href="#">Help Center</a>
										<a href="/pages/legal">Policies</a>
										<a href="/pages/whitepapers">Whitepapers</a>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div id="uses">USES
						<div class="uses_chop">
							<div id="uses-dropdown" class="dropdown-nav">
								<div class="dropdown-header clearfix">
									<div class="w-66">
										<a href="/pages/uses">PRIMARY USES</a>
									</div>
									<div class="w-33">
										<a href="/pages/secondaryuses">Uses by Industry</a>
									</div>
								</div>
								<div class="dropdown-body clearfix">
									<div class="w-33 left">
										<a href="/pages/forwebsites">For Websites</a>
										<a href="/pages/support">Online Support</a>
										<a href="/pages/sales">Assisted Sales</a>
										<a href="/pages/presentations">Presentations</a>
										<a href="/pages/meetings">Meetings</a>
										<a href="/pages/shop">Shop Together</a>
									</div>
									<div class="w-33 center">
										<a href="/pages/collaboration">Collaboration</a>
										<a href="/pages/search">Search Together</a>
										<a href="/pages/remotecontrol">Remote Control</a>
										<a href="/pages/browse">Browse Together</a>
										<a href="/pages/watchvideos">Watch Together</a>
										<a href="http://stage-video.samesurf.com/">Public Rooms</a>
									</div>
									<div class="border-left w-33 right">
										<a href="/pages/education">Education</a>
										<a href="/pages/medical">Health Care</a>
										<a href="/pages/corptraining">Corporate Training</a>
										<a href="/pages/marketresearch">Market Research</a>
										<a href="/pages/browsertesting">Browser Testing</a>
										<a href="/pages/usabilitytesting">Usability Testing</a>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div id="header_account">
						<div id="header_account_head">
							<div id="account_head_icon"></div>
							<div id="account_head_text"></div>
							<div id="account_head_arrow"></div>
						</div>
						<div id="header_account_body" class="drop_menu">
							<a href="/login"><div class="login_default header_account_body_content">LOG IN</div></a>
							<a href="/signup"><div class="login_default header_account_body_content">SIGN UP</div></a>
							<a href="/help"><div class="login_default header_account_body_content">HELP</div></a>
							<a href="/account"><div class="login_account header_account_body_content">ACCOUNT</div></a>
							<a href="#"><div class=" login_account header_account_body_content">PREFERENCES</div></a>
							<a href="#"><div class=" login_account header_account_body_content">ENABLE SITE</div></a>
							<a href="/logout"><div class=" login_account header_account_body_content">LOG OUT</div></a>
							<div id="header_account_bottom">
								<div id="header_account_session">JOIN A SESSION</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div id="sub_header">
				<div id="sub_nav">
					<div id="sub_navlinks">
						<a href="/pages/tour_different">START TOUR</a>
						<a href="/pages/pricing">BUY NOW</a>
						<a href="/pages/howitworks">HOW IT WORKS</a>
						<a href="/pages/requestdemo">REQUEST DEMO</a>
						<a href="/pages/contactus">CONTACT US</a>
					</div>
				</div>
			</div>

			<div id="content">
				<?php echo $blocks->main ?>
				<div id="bottombar">
					<div class="centredcontent">
						<div id="buttoncontainer-3">

							<div id="leftbuttoncontainer">
								<div class="buttoncontainertext">
									<h1>
										FOR INDIVIDUALS
									</h1>
									Use Samesurf in your everyday<br/>work and personal life.
								</div>
								<a href="/pages/forindividuals" id="cobrowse-1" class="button blue">START NOW</a>
							</div>

							<div id="centerbuttoncontainer">
								<div class="buttoncontainertext">
									<h1>
										FOR BUSINESS
									</h1>
									Leverage Samesurf for Install-Free<br/>Support, Sales and Collaboration.
								</div>
								<a href="/pages/forsupportandsales" id="sameslide-3" class="button yellow sameslide">START NOW</a>
							</div>

							<div id="rightbuttoncontainer">
								<div class="buttoncontainertext">
									<h1>
										FOR WEBSITES
									</h1>
									Embed Samesurf onto your site to socialize the customer experience.
								</div>
								<a href="/pages/forsiteintegration" id="enablesite-2" class="button red enable">START NOW</a>
							</div>

						</div>
					</div>
				</div>
			</div>

			<div id="sticky_footer_pushdown"></div>
		</div>
		<div id="footer">
			<div id="footer_content">
				<div id="footer_links">
					<div class="footer_links_column">
						<a href="/"><div class="footertitle">SAMESURF</div></a>
						<a href="/pages/howitworks">HOW IT WORKS</a>
						<a href="/pages/features">FEATURES</a>
						<a href="/pages/integration">INTEGRATION</a>
						<a href="/pages/security">SECURITY</a>
						<a href="/pages/different">WE'RE DIFFERENT</a>
						<a href="/pages/technology">TECHNOLOGY</a>
						<a href="/pages/customization">CUSTOMIZATION</a>
						<a href="/pages/workflow">WORKFLOW</a>
						<a href="/pages/phonesupport">PHONE SUPPORT</a>
						<a href="/pages/livechat">LIVE CHAT</a>
						<a href="/pages/benefits">BENEFITS</a>
					</div>
					<div class="footer_links_column">
						<a href="/pages/uses"><div class="footertitle">USES</div></a>
						<a href="/pages/support">ONLINE SUPPORT</a>
						<a href="/pages/sales">ASSISTED SALES</a>
						<a href="/pages/presentations">PRESENTATIONS</a>
						<a href="/pages/meetings">MEETINGS</a>
						<a href="/pages/shop">SHOP TOGETHER</a>
						<a href="/pages/collaboration">COLLABORATION</a>
						<a href="/pages/corptraining">CORPORATE TRAINING</a>
						<a href="/pages/remotecontrol">REMOTE CONTROL</a>
						<a href="/pages/browse">BROWSE TOGETHER</a>
						<a href="/pages/watchvideos">WATCH VIDEOS</a>
						<a href="/pages/secondaryuses">SECONDARY USES</a>
					</div>
					<div class="footer_links_column">
						<a href="/pages/#"><div class="footertitle">COMPANY</div></a>
						<a href="/pages/team">ABOUT US</a>
						<a href="/pages/#">START DEMO</a>
						<a href="/pages/contactus">CONTACT US</a>
						<a href="/pages/jobs">CAREERS</a>
						<a href="/pages/pricing">PRICING</a>
						<a href="/pages/faqs">FAQS</a>
						<a href="/pages/partners">PARTNERS</a>
						<a href="/pages/legal">LEGAL</a>
						<a href="/pages/press">PRESS</a>
						<a href="/pages/whitepapers">PAPERS</a>
						<a href="/pages/videos">VIDEOS</a>
					</div>
				</div>
				
				
				<div id="borderbox">
					<div id="joinroombox">
						<form>
							<input type="text" />
						</form>	
					</div>
				
					<div id="blacktextbox">
						GOT AN INVITE? JOIN AN EXISTING ROOM
					</div>
				
					<a href="/pages/#">
						<div id="gobox">
							GO
						</div>
					</a>
				</div>
				
				
			</div>
			<div id="footer_copyrights">
				<div id="footer_center">
					<div id="footer_patent">
						U.S. Patent #8,527,591 / Multiple Patents pending<br/>
						Filed PCT Application
					</div>
					<div id="footer_rights">
						Copyright &copy; 2009-2014 Samesurf, Inc. All referenced logos and trademarks are property of their respective owners.
					</div>
				</div>
			</div>
		</div>
	</body>
</html>
