	<div id="sub_header">
		<div id="sub_nav">
			<div id="sub_navlinks">
					<a href="#">HOW IT WORKS</a>
					<a href="#">REQUEST DEMO</a>
					<a href="#">PRICING</a>
					<a href="#">CONTACT US</a>
			</div>
		</div>
	</div>
<div>

<?php
	$access = $view->defaults->access;
	$domain = $view->defaults->domain;

	foreach($access as $user) {
		echo $user->email;
		echo "&nbsp";
		echo "<a href=\"/domain/removeaccess/pid/" . $domain->publicid() . "/id/" . $user->id . "\">remove</a>";
		echo "<br />";
	}
	
	$pid = $view->defaults->domain->publicid();

	echo "<a href=\"/domain/addaccess/pid/$pid\">add another user</a>";
?>

</div>
