	<div id="sub_header">
		<div id="sub_nav">
			<div id="sub_navlinks">
					<a href="#">HOW IT WORKS</a>
					<a href="#">REQUEST DEMO</a>
					<a href="#">PRICING</a>
					<a href="#">CONTACT US</a>
			</div>
		</div>
	</div>
<div>

<form method="POST">
<?php
	$domain = $view->defaults->domain;
	$config = $domain->get_config();

	foreach ($config->bool_setting as $bool_setting) {
		$checked = "";
		if ($bool_setting->value) $checked = "checked";
		echo "$bool_setting->name<input type='checkbox' name='$bool_setting->key' $checked><br />";
	}
?>
<input type="submit">
</form>
</div>
