--goldfinch-alt-boundary
Content-Type: text/plain; charset="iso-8859-1" 
Content-Transfer-Encoding: 7bit

Thanks for registering with samesurf

please click this link to complete you signup

<?=$view->defaults->confirmationlink?></a>

Thanks

--goldfinch-alt-boundary
Content-Type: text/html; charset="iso-8859-1" 
Content-Transfer-Encoding: 7bit

<table style="width:100%;">
	<tr>
		<td>
			<table width="636px" style="font-family: arial; margin: auto;">
				<tr>
					<td style="text-align: center; padding-top: 39px; padding-bottom: 12px;">
						<img src="http://127.0.0.1/static/images/email/samesurf.png" alt="samesurf" style="width:306px; height: 63px" >
					</td>
				</tr>
				<tr>
					<td style="border-width: 1px; border-style: solid; border-color: rgb(222,222,222); border-radius: 8px;">
						<table width="100%" style="text-align: center">
							<tr>
								<td>
									<p style="padding-top: 50px; padding-bottom: 30px; color: rgb(72,72,72); font-size: 20px;">THANKS FOR REGISTERING WITH SAMESURF.</p>
								</td>
							</tr>
							<tr>
								<td>
									<p style="color: rgb(121,121,121);"> To activate your account click here: <a style="color: rgb(58,110,179);" href="<?=$view->defaults->confirmationlink?>"><?=$view->defaults->confirmationlink?></a></p>
								</td>
							</tr>
							<tr>
								<td style="padding-top: 50px; padding-bottom: 60px;">
									<a style="text-decoration: none;" href="<?=$view->defaults->confirmationlink?>"><div style="width:324px; height:73px; font-size: 22px; line-height: 73px; background-color: rgb(87,142,216); color: #ffffff; margin: auto; border-radius: 4px;">VALIDATE</div></a>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>
