<?php
	$this->setTitle("reset your password");
	$this->addCSSFile("/static/css/common.css");
	$this->addCSSFile("/static/css/common_form.css");
	$this->addCSSFile("/static/css/account_update.css");
	$this->addJSFile("/static/js/login_resetform.js");
?>
	<div id="sub_header">
		<div id="sub_nav">
			<div id="sub_navlinks">
					<a href="#">HOW IT WORKS</a>
					<a href="#">REQUEST DEMO</a>
					<a href="#">PRICING</a>
					<a href="#">CONTACT US</a>
			</div>
		</div>
	</div>
<div class="banner">
	<div class="banner_main">
		<div class="banner_title">PASSWORD RESET</div>
	</div>
</div>

<div class="centre_content">
	<form id="login_reset" method="post" action="">
		<fieldset>
			<div id="password" class="input_field">
				<label>NEW PASSWORD</label>
				<div class="input_style common_update">
					<input name="password" type="password" <?php util_html::attr("value", $view->defaults, "password")?>> 
					<div class="input_validate_icon">
						<div class="input_tick"></div>
						<div class="input_cross"></div>
					</div>
				</div>
				
				<span class="error"><?php util_html::text($view->errors, "password")?></span>
			</div>
			<div id="verify_password" class="input_field">
				<label>CONFIRM NEW PASSWORD</label>
				<div class="input_style common_update">
					<input name="verify_password" type="password" <?php util_html::attr("value", $view->defaults, "password")?>> 
					<div class="input_validate_icon">
						<div class="input_tick"></div>
						<div class="input_cross"></div>
					</div>
				</div>
				<span class="error"><?php util_html::text($view->errors, "password")?></span>
			</div>
			<input type="submit" class="button_red">
		</fieldset>
	</form>
</div>
