<?php
	$this->setTitle("please login");
	
	$this->addCSSFile("/static/css/common.css");
	$this->addCSSFile("/static/css/common_form.css");
	$this->addCSSFile("/static/css/login_default.css");

	$this->addJSFile("/static/js/login/default.js");
?>

<div id="login_container_center">
	<div id="login_container_wrap">
		<div id="login_container">
			<div id="login_head">
				<a href="/"><div id="login_logo"></div></a>
				<div id="signup_text">
					Not a member? <a href="/signup">Sign Up</a>
				</div>
			</div>
			<div id="login_body">
				<div id="login_body_title">LOGIN</div>
				<div id="login_body_main">
					<div id="login_form">
						<form method="POST" action="">
								<div class="field" id="email">
									<div class="field_label">Email Address:</div>
									<div class="input_style">
										<input type="text" name="email" <?php util_html::attr("value", $view->defaults, "email")?> />
										<div class="input_validate_icon">
											<div class="input_tick"></div>
											<div class="input_cross"></div>
										</div>
									</div>	
								</div>
			
								<div class="field" id="password">
									<div class="field_label">Password:</div>
									<div class="input_style">
										<input type="password" name="password"/>
										<div class="input_validate_icon">
											<div class="input_tick"></div>
											<div class="input_cross"></div>
										</div>
									</div>	
								</div>
								
						</form>
					</div>
			
					<div id="login" class="button_blue">
							<div>LOGIN</div>
					</div>
			
					<div class="errors">
						<div class="error" id="email_error">
							<div>You must enter an email.</div>
						</div>
						<div class="error" id="password_error">
							<div>You must enter a password.</div>
						</div>
			
						<?php if (isset($view->errors->email) && $view->errors->email == "login_error"): ?>
							<div class="error vis_error" id="email_inuse_error">
								<div>Username or password incorrect</div>
							</div>
						<?php endif; ?>
					</div>
				</div>
			</div>	
	
			<div id="password_reset">
				<a href="/login/reset">forgotten password?</a>
			</div>
		</div>
	</div>
</div>
