<html>
	<head>
		<title><?=$view->title?></title>
		<link rel="shortcut icon" href="/static/favicon.ico" />
		<link rel='stylesheet' type='text/css' href='/static/fonts/stylesheet.css'/>
		<link rel='stylesheet' type='text/css' href='/static/css/layout.css'/>
<!-- 	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script> -->
		<script type='text/javascript' src="/static/jquery.min.js"></script>
		<script type='text/javascript' src="/static/js/layout.js"></script>
				
		<?php $this->include_css_files() ?>
		<?php $this->include_js_files() ?>
		
	</head>

	<body>
		<div id="content">	
			<?php echo $blocks->main ?>	
		</div>
	<body>
</html>
