<?php
	$this->setTitle("enter you email address to reset your password");
	$this->addCSSFile("/static/css/common.css");
	$this->addCSSFile("/static/css/common_form.css");
	$this->addCSSFile("/static/css/account_update.css");
?>
	<div id="sub_header">
		<div id="sub_nav">
			<div id="sub_navlinks">
					<a href="#">HOW IT WORKS</a>
					<a href="#">REQUEST DEMO</a>
					<a href="#">PRICING</a>
					<a href="#">CONTACT US</a>
			</div>
		</div>
	</div>
<div class="banner">
	<div class="banner_main">
		<div class="banner_title">PASSWORD RESET</div>
	</div>
</div>

<div class="centre_content">
	<form id="login_reset" method="post" action="">
		<fieldset>
			<div id="login_reset_name" class="input_field">
				<label>EMAIL</label>
				<div class="input_style common_update">	
					<input name="email" type="text" <?php util_html::attr("value", $view->defaults, "email")?>> 
				</div>
				<span class="error"><?php util_html::text($view->errors, "email")?></span>
			</div>
			<input type="submit" class="button_red">
		</fieldset>
	</form>
</div>
