<?php
	$this->setTitle("enter you email address to reset your password");
	$this->addCSSFile("/static/css/common.css");
	$this->addCSSFile("/static/css/account_update.css");
?>
	<div id="sub_header">
		<div id="sub_nav">
			<div id="sub_navlinks">
					<a href="#">HOW IT WORKS</a>
					<a href="#">REQUEST DEMO</a>
					<a href="#">PRICING</a>
					<a href="#">CONTACT US</a>
			</div>
		</div>
	</div>
<div class="banner">
	<div class="banner_main">
		<div class="banner_title">RESET EMAIL SENT</div>
	</div>
</div>

<div class="centre_content">
	<div id="step2_message">
		Your Password reset email has been sent.
	</div>
	
	<div id="step2_instructions">
		Please follow the instructions in the email to continue through the reset process.
	</div>
	
</div>