<?php
	$this->setTitle("please register");
	$this->addCSSFile("/static/test.css");
	$this->addJSFile("/static/test.js");
?>
	<div id="sub_header">
		<div id="sub_nav">
			<div id="sub_navlinks">
					<a href="#">HOW IT WORKS</a>
					<a href="#">REQUEST DEMO</a>
					<a href="#">PRICING</a>
					<a href="#">CONTACT US</a>
			</div>
		</div>
	</div>
<form id="register" method="post" action="">

	<fieldset>
		<div id="register_name" class="input_field">
    		<label>email</label>
			<input name="email" type="text" <?php util_html::attr("value", $view->defaults, "email")?>> 
			<span class="error"><?php util_html::text($view->errors, "email")?></span>
		</div>
	
		<div id="register_password" class="input_field">	
    		<label>password</label>
			<input name="password" type="password"> 
			<span class="error"> <?php util_html::text($view->errors, "password")?><span>
		</div>

		<input type="submit">

    </fieldset>
</form>
