<?php
	$this->setTitle("admin - step 1");
	$this->addCSSFile("/static/css/common.css");
	$this->addCSSFile("/static/css/common_form.css");
	$this->addCSSFile("/static/css/signup_steps_common.css");
	$this->addCSSFile("/static/css/signup_step1.css");

	$this->addJSFile("/static/js/signup_step1.js");
?>
<div id="login_container_center">
	<div id="login_container_wrap">
		<div id="login_container">
			<div id="login_head">
				<a href="/"><div id="login_logo"></div></a>
				<div id="signup_text">
					Already a member? <a href="/login">Log In</a>
				</div>
			</div>
			<div id="login_body">
				<div id="login_body_title">NEW MEMBER SIGN UP</div>
				<div id="login_body_main">
					<div id="signup_step1_form">
						<form method="POST" action="">
							<div class="field" id="first_name">
								<div class="field_label">First Name:</div>
								<div class="input_style">
									<input type="text" name="first_name" <?php util_html::attr("value", $view->defaults, "first_name")?> />
									<div class="input_validate_icon">
										<div class="input_tick"></div>
										<div class="input_cross"></div>
									</div>
								</div>	
							</div>
							
							<div class="field" id="last_name">
								<div class="field_label">Last Name:</div>
								<div class="input_style">
									<input type="text" name="last_name" <?php util_html::attr("value", $view->defaults, "last_name")?>/>
									<div class="input_validate_icon">
										<div class="input_tick"></div>
										<div class="input_cross"></div>
									</div>
								</div>	
							</div>
							
							<div class="field" id="email">
								<div class="field_label">Email Address:</div>
								<div class="input_style">
									<input type="text" name="email" <?php util_html::attr("value", $view->defaults, "email")?>/>
									<div class="input_validate_icon">
										<div class="input_tick"></div>
										<div class="input_cross"></div>
									</div>
								</div>	
							</div>
							
							<div class="field" id="location">
								<div class="field_label">City:</div>
								<div class="input_style">
									<input type="text" name="location" <?php util_html::attr("value", $view->defaults, "location")?>/>
									<div class="input_validate_icon">
										<div class="input_tick"></div>
										<div class="input_cross"></div>
									</div>
								</div>	
							</div>
							
							<div class="field" id="company">
								<div class="field_label">Company:</div>
								<div class="input_style">
									<input type="text" name="company" <?php util_html::attr("value", $view->defaults, "company")?>/>
									<div class="input_validate_icon">
										<div class="input_tick"></div>
										<div class="input_cross"></div>
									</div>
								</div>	
							</div>
							
							<div class="field" id="password">
								<div class="field_label">Password:</div>
								<div class="input_style">
									<input type="password" name="password" <?php util_html::attr("value", $view->defaults, "password")?>/>
									<div class="input_validate_icon">
										<div class="input_tick"></div>
										<div class="input_cross"></div>
									</div>
								</div>	
							</div>
							
							<div class="field" id="verify_password">
								<div class="field_label">Verify Password:</div>
								<div class="input_style">
									<input type="password" name="verify_password" <?php util_html::attr("value", $view->defaults, "password")?>/>
									<div class="input_validate_icon">
										<div class="input_tick"></div>
										<div class="input_cross"></div>
									</div>
								</div>	
							</div>
						</form>
						<div id="login" class="button_blue">
							<div>SIGN UP</div>
						</div>
					</div>
				</div>

	<!-- 
<div id="field_required">*All fields required</div>
	
	<div class="errors">
		<div class="error" id="first_name_error">
			<div>You must enter a first name.</div>
		</div>
		<div class="error" id="last_name_error">
			<div>You must enter a last name.</div>
		</div>
		<div class="error" id="password_match_error">
			<div>Your passwords do not match.</div>
		</div>
		<div class="error" id="password_length_error">
			<div>Your password must be at least 6 characters long.</div>
		</div>
		<div class="error" id="email_error">
			<div>You must enter a valid email address.</div>
		</div>

		<?php if (isset($view->errors->email) && $view->errors->email == "email_in_use"): ?>
			<div class="error vis_error" id="email_inuse_error">
				<div>This email address is already in use. Please login.</div>
			</div>
		<?php endif; ?>

	</div>
-->

			</div>
		</div>	
	</div>
</div>		

