<?php
	$this->setTitle("admin - step 1");
	$this->addCSSFile("/static/css/common.css");
	$this->addCSSFile("/static/css/common_form.css");
	$this->addCSSFile("/static/css/signup_steps_common.css");
	$this->addCSSFile("/static/css/signup_step1.css");

	$this->addJSFile("/static/js/validate_invite.js");
?>
	<div id="sub_header">
		<div id="sub_nav">
			<div id="sub_navlinks">
					<a href="#">HOW IT WORKS</a>
					<a href="#">REQUEST DEMO</a>
					<a href="#">PRICING</a>
					<a href="#">CONTACT US</a>
			</div>
		</div>
	</div>
<div class="banner">
	<div class="banner_main">
		<div class="banner_title">SELF SERVICE PORTAL</div>
	</div>
</div>

<div class="centre_content">

	<div id="signup_step1_form">
			<form method="POST" action="">
					<div class="field" id="first_name">
						<div class="field_label">FIRST NAME:</div>
						<div class="input_style">
							<input type="text" name="first_name" <?php util_html::attr("value", $view->defaults, "first_name")?> />
							<div class="input_validate_icon">
								<div class="input_tick"></div>
								<div class="input_cross"></div>
							</div>
						</div>	
					</div>

					<div class="field" id="password">
						<div class="field_label">PASSWORD:</div>
						<div class="input_style">
							<input type="password" name="password" <?php util_html::attr("value", $view->defaults, "password")?>/>
							<div class="input_validate_icon">
								<div class="input_tick"></div>
								<div class="input_cross"></div>
							</div>
						</div>	
					</div>
					
					<div class="field" id="last_name">
						<div class="field_label">LAST NAME:</div>
						<div class="input_style">
							<input type="text" name="last_name" <?php util_html::attr("value", $view->defaults, "last_name")?>/>
							<div class="input_validate_icon">
								<div class="input_tick"></div>
								<div class="input_cross"></div>
							</div>
						</div>	
					</div>

					<div class="field" id="verify_password">
						<div class="field_label">VERIFY PASSWORD:</div>
						<div class="input_style">
							<input type="password" name="verify_password" <?php util_html::attr("value", $view->defaults, "password")?>/>
							<div class="input_validate_icon">
								<div class="input_tick"></div>
								<div class="input_cross"></div>
							</div>
						</div>	
					</div>
			</form>
		</div>

		<div id="continue">
			<div>CONTINUE</div>
		</div>

		<div class="errors">
			<div class="error" id="first_name_error">
				<div>You must enter a first name.</div>
			</div>
			<div class="error" id="last_name_error">
				<div>You must enter a last name.</div>
			</div>
			<div class="error" id="password_match_error">
				<div>Your passwords do not match.</div>
			</div>
			<div class="error" id="password_length_error">
				<div>Your password must be at least 6 characters long.</div>
			</div>
			<div class="error" id="email_error">
				<div>You must enter a valid email address.</div>
			</div>

		</div>

</div>		

